### ISSUE TITLE
Problems Alongside Multiverse-Portals [DBO 526]

### ISSUE THREAD

**Issue by MyPictures** [NoCheatPlus/Issues#10]
What is the problem, What do you expect to see instead?
Problems alongside Multiverse-Portals. Players who try to enter a portal that lead to a world they don't have access to shouldn't do anything. Problem is, NoCheatPlus flips out and kicks players for trying to move too fast or teleport to a location. It doesn't recognize that the the information is coming from a plugin.

Can it be reproduced systematically and if so: how?
Yeah, add Multiverse-Core and Multiverse-Portals to a bukkit server, and also add NoCheatPlus. Create a multiverse portal that leads to a world that players don't have access to in a permissions plugin (Doesn't matter which). Then as a player, try walking through the portal.

Normally without NoCheatPlus, nothing happens because the player doesn't have access to the world. With NoCheatPlus, the admins are spammed with movement violations and the player is kicked. Which is very annoying for both our staff and players.

Which version of NC+ are you using? (Check with /version NoCheatPlus on your server)
Currently we are using The latest 1.5.1 build v2, however the problem still occurs with earlier versions of NCP.

On which Craftbukkit/Craftbukkit++/Spigot build do you run your server on?
Craftbukkit

How easy is it to reproduce? Does it always happen? Does it happen to all players? Does it happen with vanilla clients?
Easy to reproduce, happens 100% of the time, happens to all players who don't have access to the world it leads to, and it does happen to vanilla clients.

**Comment by MyPictures** [comment]
**Jcheatgamer17:** "same thing happens on my server...

18.05 01:42:30 [Server] INFO (CONSOLE) Kicked A1v1n1 : Kicked for flying (or related) 18.05 01:42:30 [Server] INFO A1v1n1 failed SurvivalFly: tried to move from 928.19, 102.00, -164.53 to 928.19, 102.00, -164.53 over a distance of 0.00 block(s). VL 7147."

**Comment by MyPictures** [comment]
**MyPictures:** "I can't reproduce this issue because if I link 2 Multiverse portals (across worlds) and deny permissions on myself to use them then MV wont even move me. You should directly deny them to use portals instead of worlds over this: https://github.com/Multiverse/Multiverse-Portals/wiki/Permissions 
MultiVerse seems to do strange movings if you only prevent them from entering world so that would be a job for CompatNoCheatPlus to exempt players if they enter a portal or something."

**Comment by MyPictures** [comment]
**asofold:** "This might be related to latency issues (player keeps sending moving packets while he is already teleported server side but has not yet noticed).

If Minecraft does not fix this, we might have to build in some heuristic thing to check if moves are near a "recent position" and just skip the violation handling for those. (Probably related: https://mojang.atlassian.net/browse/MC-30489)"

**Comment by asofold** [comment]
Assume fixed/superseded with latest.
