### ISSUE TITLE
1.9: Elytra causes survival-fly + creative-fly false positives

### ISSUE THREAD

**Issue by Platinteufel** [NoCheatPlus/Issues#100]
00:23:27 INFO: ---- Version information ----
00:23:27 INFO: #### Server ####
00:23:27 INFO: git-Spigot-dd155ed-3e3516e ~MC: 1.9~
00:23:27 INFO: detected: 1.9
00:23:27 INFO: #### NoCheatPlus ####
00:23:27 INFO: Plugin: 3.14.0-SNAPSHOT-sMD5NET-b933
00:23:27 INFO: MCAccess: 1.9 / Spigot-CB-1.9_R1

00:23:27 INFO: blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
00:23:27 INFO: checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
00:23:27 INFO: defaults: pvpKnockBackVelocity
00:23:27 INFO: packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter
00:23:27 INFO: Hooks: AllViolations~NCP~ 1.0
00:23:27 INFO: #### Related Plugins ####
00:23:27 INFO: ProtocolLib v3.7-SNAPSHOT-b239

![2016-03-04_02 03 31](https://cloud.githubusercontent.com/assets/13700636/13514940/6970ad52-e1ad-11e5-859c-605b53be4426.png)

![2016-03-04_02 10 37](https://cloud.githubusercontent.com/assets/13700636/13515045/79ffc828-e1ae-11e5-92fd-cc88da2c0b01.png)

**Comment by asofold** [comment]
Please update Spigot (note: https://hub.spigotmc.org/jira/browse/SPIGOT-1646)! And do keep checking for updates (also note: https://twitter.com/Spigot_MC).

Current Spigot when writing this comment (soon to be outdated): git-Spigot-87e2f47-ef13ca4

(I hope you don't mind the copy and paste :).)

**Comment by asofold** [comment]
This duplicates the 1.9 ticket, please check that one for reference: https://github.com/NoCheatPlus/Issues/issues/56

**Comment by asofold** [comment]
Making this ticket the detailed reference for Elytra.

**Comment by asofold** [comment]
Current state: build 952 started adjusting speed + adding workarounds. 'Still doesn't work'.

On a local test server i can glide well, transitions to not using elytra (taking either end rod or elytra off) don't result in a violation loop and death by fall damage anymore, at least on 'some testing'.

Elytra on ground is awful, as all the workarounds from the survivalfly check are needed, but are not implemented in the creativefly check. In addition the client would move slightly differently (e.g. lift off with with jumping, differing gravity/friction behavior).

**Comment by asofold** [comment]
Build 952 will activate creativefly for elytra whenever in-air. Should resolve much of gliding to death.

**Comment by asofold** [comment]
At 955 elytra should be mostly workable. What follows should be minor adjustments and preventing cheating .
