### ISSUE TITLE
Shulker causes survival-fly false positives

### ISSUE THREAD

**Issue by Platinteufel** [NoCheatPlus/Issues#103]
00:23:27 INFO: ---- Version information ----
00:23:27 INFO: #### Server ####
00:23:27 INFO: git-Spigot-dd155ed-3e3516e ~MC: 1.9~
00:23:27 INFO: detected: 1.9
00:23:27 INFO: #### NoCheatPlus ####
00:23:27 INFO: Plugin: 3.14.0-SNAPSHOT-sMD5NET-b933
00:23:27 INFO: MCAccess: 1.9 / Spigot-CB-1.9_R1

00:23:27 INFO: blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
00:23:27 INFO: checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
00:23:27 INFO: defaults: pvpKnockBackVelocity
00:23:27 INFO: packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter
00:23:27 INFO: Hooks: AllViolations~NCP~ 1.0
00:23:27 INFO: #### Related Plugins ####
00:23:27 INFO: ProtocolLib v3.7-SNAPSHOT-b239

![2016-03-04_02 28 30](https://cloud.githubusercontent.com/assets/13700636/13515351/de82a5c0-e1b0-11e5-9f5d-318645b80b4a.png)

**Comment by asofold** [comment]
Please update Spigot (note: https://hub.spigotmc.org/jira/browse/SPIGOT-1646)! And do keep checking for updates (also note: https://twitter.com/Spigot_MC).

Current Spigot when writing this comment (soon to be outdated): git-Spigot-87e2f47-ef13ca4

(I hope you don't mind the copy and paste :).)

-> this very case could be interesting - is it a block or an entity?

**Comment by asofold** [comment]
All shape related stuff needs to be retested with NCP build 934...

**Comment by Platinteufel** [comment]
Still doesn't work if the shulker move out (so that they are 2 blocks high)

**Comment by asofold** [comment]
It's an entity, so there needs to be a special case for this one, extra to minecart and boat.

**Comment by Platinteufel** [comment]
Hm maybe, but are there any problems if you treat them as block? It's an entity in block-form, so you can walk on it - and depending on their state they are one or two blocks high.

**Comment by asofold** [comment]
If we know a shulker is there, we can just treat it like boats/minecarts, it'll also use their bounding boxes. This case just needs to be added without breaking backwards compatibility.

**Comment by asofold** [comment]
I'll push a fix attempt with build 936.

**Comment by Platinteufel** [comment]
confirmed fix in 936
