### ISSUE TITLE
Stairs & slabs cause survival-fly false positives (slabs only if they are at the upper blockside)

### ISSUE THREAD

**Issue by Platinteufel** [NoCheatPlus/Issues#104]
00:23:27 INFO: ---- Version information ----
00:23:27 INFO: #### Server ####
00:23:27 INFO: git-Spigot-dd155ed-3e3516e ~MC: 1.9~
00:23:27 INFO: detected: 1.9
00:23:27 INFO: #### NoCheatPlus ####
00:23:27 INFO: Plugin: 3.14.0-SNAPSHOT-sMD5NET-b933
00:23:27 INFO: MCAccess: 1.9 / Spigot-CB-1.9_R1

00:23:27 INFO: blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
00:23:27 INFO: checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
00:23:27 INFO: defaults: pvpKnockBackVelocity
00:23:27 INFO: packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter
00:23:27 INFO: Hooks: AllViolations~NCP~ 1.0
00:23:27 INFO: #### Related Plugins ####
00:23:27 INFO: ProtocolLib v3.7-SNAPSHOT-b239

![2016-03-04_02 57 33](https://cloud.githubusercontent.com/assets/13700636/13515836/2a7e3008-e1b5-11e5-8485-7a1e77f9f6aa.png)
![2016-03-04_02 55 00](https://cloud.githubusercontent.com/assets/13700636/13515838/2d896434-e1b5-11e5-85f3-0f7fcbd7c5d3.png)
![2016-03-04_02 57 15](https://cloud.githubusercontent.com/assets/13700636/13515840/307b6764-e1b5-11e5-984c-c73d22f3b8d4.png)

Slaps at the upper blockside:

![2016-03-04_03 08 52](https://cloud.githubusercontent.com/assets/13700636/13516062/e9d62842-e1b6-11e5-9774-55f02b05dcde.png)

**Comment by asofold** [comment]
Please update Spigot (note: https://hub.spigotmc.org/jira/browse/SPIGOT-1646)! And do keep checking for updates (also note: https://twitter.com/Spigot_MC).

Current Spigot when writing this comment (soon to be outdated): git-Spigot-87e2f47-ef13ca4

(I hope you don't mind the copy and paste :).)

**Comment by asofold** [comment]
Confirmed: wooden slabs placed on top part of the block.

**Comment by asofold** [comment]
Please check with build 934 ...

**Comment by Platinteufel** [comment]
confirmed fix in 934
