### ISSUE TITLE
Folded trapdoor causes survival-fly false positives

### ISSUE THREAD

**Issue by Platinteufel** [NoCheatPlus/Issues#105]
Sorry for my ticket spam, but I'm testing ncp with the latest spigot 1.9 right now.

00:23:27 INFO: ---- Version information ----
00:23:27 INFO: #### Server ####
00:23:27 INFO: git-Spigot-dd155ed-3e3516e ~MC: 1.9~
00:23:27 INFO: detected: 1.9
00:23:27 INFO: #### NoCheatPlus ####
00:23:27 INFO: Plugin: 3.14.0-SNAPSHOT-sMD5NET-b933
00:23:27 INFO: MCAccess: 1.9 / Spigot-CB-1.9_R1

00:23:27 INFO: blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
00:23:27 INFO: checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
00:23:27 INFO: defaults: pvpKnockBackVelocity
00:23:27 INFO: packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter
00:23:27 INFO: Hooks: AllViolations~NCP~ 1.0
00:23:27 INFO: #### Related Plugins ####
00:23:27 INFO: ProtocolLib v3.7-SNAPSHOT-b239

![2016-03-04_03 21 33](https://cloud.githubusercontent.com/assets/13700636/13516246/a3388ea0-e1b8-11e5-88e8-5cf1b0468763.png)

**Comment by asofold** [comment]
Please update Spigot (note: https://hub.spigotmc.org/jira/browse/SPIGOT-1646)! And do keep checking for updates (also note: https://twitter.com/Spigot_MC).

Current Spigot when writing this comment (soon to be outdated): git-Spigot-87e2f47-ef13ca4

(I hope you don't mind the copy and paste :).)

**Comment by asofold** [comment]
Confirmed: Shapes don't seem to be recognized right.

**Comment by asofold** [comment]
Please check with build 934...

**Comment by Platinteufel** [comment]
confirmed fix in 934
