### ISSUE TITLE
Players get stucked, "failed passable moved into a block"

### ISSUE THREAD

**Issue by StraightUpKnives** [NoCheatPlus/Issues#108]
My NoCheatPlus is stucking players at spawn, players can't move, please fix it..
I've lost alot of players caused that.

**Comment by Platinteufel** [comment]
If you want to use NCP in 1.9, use the latest dev build. It fixes a few bugs, but it's still buggy anyway.
http://ci.md-5.net/job/NoCheatPlus/lastBuild/

**Comment by StraightUpKnives** [comment]
Not working...

**Comment by asofold** [comment]
Please always post the full ouput of the 'ncp version' command, text much preferred. It really helps to judge things much faster for most cases.

Block shapes should be mostly resolved with NCP build 935, if you're using one of the latest spigot builds (not the early ones!).

Ensure you have the latest spigot for 1.9, and keep checking+rebuilding. Same for NCP, there'll be more updates.

**Comment by asofold** [comment]
Assume this fixed with ncp + spigot updated.
