### ISSUE TITLE
Permission to bypass cmd from action [DBO 542]

### ISSUE THREAD

**Issue by MyPictures** [NoCheatPlus/Issues#11]
Just a good way to prevent trusted players from hacking but with sure that they wouldn't be banned by NCP command due to lagg or whatever. 
Someting like nocheatplus.cmd.cmdnamehere
Player with this permission shouldn't trigger this cmd.

**Comment by MyPictures** [comment]
**asofold:** "You need fine grained control to just exempt a few players from some commands (instead of exempting them from all commands or to just ignore certain commands for all players)?"

**Comment by MyPictures** [comment]
**Apple_columb:** "asofold: Sure it could be done like that. But I don't think that exempt from ban for any user is a good idea. Moderators should be still able to ban anyone. But not NCP."

**Comment by MyPictures** [comment]
**"Mypictures:** "Apple_columb:

Not sure how Evenprime implemented the whole "actions" idea but maybe its possible to do something like this. However this is going quite advanced now, thats already like having "player based actions". At the moment NC+ does only have a silent permission like this: nocheatplus.checks.moving.nofall.silent which excludes this player/group from getting logged by NC+, however the checks/actions will still work as before just without thorwing out any notifications. 
I would say its an interesting idea and quite cool to have but depends all on asofolds opinion."

**Comment by MyPictures** [comment]
**asofold:** "In fact bypassing individual actions or individual log messages could be an interesting option, referencing it by name is simple.

It does increase the number of permission checks for violations though."

**Comment by asofold** [comment]
I could imagine adding such (despite probably much outdated) with the following condition:
* Both checkbypasspermission.silent and the command bypass permission (specific to the command?) will have to be enabled via configuration, with the default state being 'disabled'.

This wouldn't hurt much and also improve performance for the default configuration, because the .silent permissions aren't checked anymore :).

**Comment by asofold** [comment]
https://github.com/NoCheatPlus/Issues/projects/6
