### ISSUE TITLE
1.8.8: Players can not move properly

### ISSUE THREAD

**Issue by PAINmatrix** [NoCheatPlus/Issues#113]
In NCP version 3.14.0 players can not move at all. It spams the ops with "failed more packets: sent too many moves 10 epacc vl 10". Before it has also said that they are flying, which is also not  true. I am using the newest spigot version.
I am not sure if this has anything to do with it but i am getting this warn message in the console:

`[Server thread/WARN]: [NoCheatPlus] NoCheatPlus supports ProtocolLib 3.6.4 on Minecraft 1.7.10 and earlier, ProtocolLib 3.6.4 or 3.6.5 on Minecraft 1.8, ProtocolLib 3.7 on Minecraft 1.9 [EXPERIMENTAL].`

**Comment by asofold** [comment]
Please get used to post the full output of the 'ncp version' command (text preferred). Version information is very coarse this way.

Which build of NCP have you been using? What kind of moving ~ what blocks , anything specific, can they move at all, do they get stuck an can't go on or do they get set back now and then ...?

On morepackets violations, there might well be collateral survivalfly violations, but i assume something else is wrong. Are you using ProtocolLib? Are you using latest development builds of ProtocolLib for 1.9?

**Comment by PAINmatrix** [comment]
---- Version information ----
     Server 
git-Spigot-db6de12-18fbb24 ~MC: 1.8.8~
detected: 1.8.8
     NoCheatPlus
Plugin: 3.14.0-SNAPSHOT-sMD5NET-b938
MCAccess: 1.8.4-1.8.8 / Spigot-CB-1.8_R3
Features:
  blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
defaults: pvpKnockBackVelocity
AllViolations~NCP~ 1.0

Before the error I was using 3.13.6-BETA-sMD5NET-b924. Walking, Sprinting, flying, anything with the exception of vehicles and sneaking and it does not seem to be any specific blocks. They can move but no more than a block before it sends them back to the last place they where. They do not seem to be stuck but it does send them back.

I am sure they are not using survivalfly. I do have ProtocolLib and I do have the latest dev build.

**Comment by asofold** [comment]
Build 924 will be problematic on 1.9, as it's too much outdated and not adapted to 1.9 in any way.

Build 939 should be the reference, but i don't see how players not being able to move should happen with latest Spigot (pls. ensure) and latest NCP (pls. also ensure not to have a duplicate jar there).

Please also post the full output that NCP is generating including the 'related plugins' part, we do need to ensure the ProtocolLib version is compatible with 1.9 as well.

**Comment by Dtrain3455** [comment]
Im one of the owners on that server with painmatrix. If there is something you need me to find so we can figure this problem out. Ill test something out and give u all what it is saying for you if that helps any?

**Comment by Dtrain3455** [comment]
The only error i see to get is a MorePacket and a Movepacket issue.

**Comment by asofold** [comment]
I overlooked this is 1.8.8.

Could you re-post the full output of 'ncp version' ? I do need the 'related plugins' part as well, to exclude certain incompatibilities (ProtocolLib version for instance).

**Comment by asofold** [comment]
Do any issues persist with NCP around build 960?

**Comment by PAINmatrix** [comment]
@asofold 

They do not seem to. Thanks.
