### ISSUE TITLE
Players Can't Seem To Move

### ISSUE THREAD

**Issue by Dtrain3455** [NoCheatPlus/Issues#116]
For some odd reason when i have the plugin enabled they players can not move. Everyone else that is oped can. But anyone that is not is stuck in place. Once we unable it everyone can move just fine.

**Comment by asofold** [comment]
Could you post the full output of the 'ncp version' command, including 'related plugins' (just all)?

It'll help identifying some kind of issues instantly. It'll be much relevant what MCAccess version is set, what verision of NCP, what version of Minecraft, what type of server (Spigot/CraftBukkit/PaperSpigot), ... and also the version of ProtocolLib ... in short: 'ncp version' :).

**Comment by asofold** [comment]
Closing as 'invalid', assuming either spigot or NCP (development builds needed for 1.9!) are outdated.
