### ISSUE TITLE
1.9 Players getting rubber banded on any movement, can't walk/jump

### ISSUE THREAD

**Issue by christheking** [NoCheatPlus/Issues#117]
14.03 01:25:39 [Server] INFO ProtocolLib v3.7.0-SNAPSHOT-b258
14.03 01:25:39 [Server] INFO #### Related Plugins ####
14.03 01:25:39 [Server] INFO Hooks: AllViolations~NCP~ 1.0
14.03 01:25:39 [Server] INFO packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter
14.03 01:25:39 [Server] INFO checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
14.03 01:25:39 [Server] INFO blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9
14.03 01:25:39 [Server] INFO Features:
14.03 01:25:39 [Server] INFO MCAccess: 1.9 / Spigot-CB-1.9_R1
14.03 01:25:39 [Server] INFO Plugin: 3.14.0-SNAPSHOT-sMD5NET-b942
14.03 01:25:39 [Server] INFO #### NoCheatPlus ####
14.03 01:25:39 [Server] INFO detected: 1.9
14.03 01:25:39 [Server] INFO git-Spigot-7d15d07-c194444 ~MC: 1.9~
14.03 01:25:39 [Server] INFO #### Server ####
14.03 01:25:39 [Server] INFO ---- Version information ----
14.03 01:25:38 [Server] INFO ProtocolLib v3.7.0-SNAPSHOT-b258
14.03 01:25:38 [Server] INFO #### Related Plugins ####
14.03 01:25:38 [Server] INFO Hooks: AllViolations~NCP~ 1.0
14.03 01:25:38 [Server] INFO packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter

However, when the player get rubberbanded there is no violation notification in-game. It is the plugin though, since when I remove it movement is fine.

**Comment by Puremin0rez** [comment]
Update your Spigot. Your build is 125 versions behind as I'm writing this comment.

**Comment by christheking** [comment]
This right?

**Comment by asofold** [comment]
I assume getting the latest is best.

**Comment by asofold** [comment]
This should already be resolved, latest Spigot + dev build of NCP, ProtocolLib 3.7 dev builds.
