### ISSUE TITLE
Slab lag back

### ISSUE THREAD

**Issue by olesien** [NoCheatPlus/Issues#118]
Hello!
So I have been noticing an issue (it is possible that I have done something wrong)
with NoCheatPlus.
Whenever I try (I have tested this on two different servers in 1.9 with nocheatplus, same results)
to jump over any kind of slab block (like stone slab) I lag back and if I fly on one I will get stuck in that block until I get kicked.
So here is my information.
OS: (this shouldn't really matter..) Windows 10 ultimate
Nocheatplus version: NoCheatPlus 3.13.7-RC-sMD5NET-b925 (1.9 compatible)
Game version (server): Spigot 1.9
My game version: Mincraft 1.9 (PC), also tested with 1.9 the 5zig mod
Error log: https://gyazo.com/2d3259d9d66c12678b3aaadc48cda070
Logs (startup only): http://pastebin.com/ubEhsHGd
Plugins: https://gyazo.com/2c2c428435d1e2e7c8740ba417b11e73
Ncp config: http://pastebin.com/LhnsTkht
Thanks!

Best regards,
oleisen

**Comment by asofold** [comment]
Build 925 of NCP isn't really meant for 1.9 though. Actual 1.9 support is built into the latest development builds. Please also ensure to use the more or less latest spigot build. ProtocolLib should be latest/3.7 or so.

**Comment by olesien** [comment]
Thanks! I actually didn't know that download site (The build tool one)! Issue solved :)

**Comment by asofold** [comment]
Thanks a lot :).
