### ISSUE TITLE
Player can't move without him being restrained for SurvivalFly & MorePackets

### ISSUE THREAD

**Issue by loslobos1234** [NoCheatPlus/Issues#119]
Well.... i downloaded your latest build on bukkit for the plugin NoCheatPlus and my players can't seem to be able to move without being kicked for survivalfly or morepackets i dont know how to fix this issue

**Comment by asofold** [comment]
I don't even know what version of Minecraft you're using. Please in future include the full output of the 'ncp version' command in your reports (text much preferred).

Assuming you are using 1.9, please ensure to use the latest Spigot build and keep checking for development builds of NCP on the jenkins location: http://ci.md-5.net/job/NoCheatPlus/

We'll release on BukkitDev, once somehow convinced the basic features/edges are covered, until then it's development builds only. Currently elytra needs much more care.
