### ISSUE TITLE
1.9: FastHeal false positives

### ISSUE THREAD

**Issue by PhanaticD** [NoCheatPlus/Issues#122]
https://gyazo.com/0d96a9947a1e2c38c23a0a014132931e

nocheat 942
git-Paper-489

issue is happening constantly spamming chat on all my servers

**Comment by asofold** [comment]
That paper build is 1.9 i assume?

**Comment by PhanaticD** [comment]
yes

**Comment by asofold** [comment]
Disabled FastHeal, assuming that player ticking changes fix fast healing anyway. If i'm wrong, we'll soon see :).

**Comment by MyPictures** [comment]
Hmmm I shal have a look at this since regen is easy to cheat.

**Comment by asofold** [comment]
I think this has been tested by now (regen doesn't work on 1.9).

**Comment by MyPictures** [comment]
@asofold Yep back the day I messaged you when I live tested. Forgot to add it to this ticket.
