### ISSUE TITLE
1.9: sword sweep attack doesn't work

### ISSUE THREAD

**Issue by asofold** [NoCheatPlus/Issues#124]
Report by players, original issue: https://github.com/NoCheatPlus/Issues/issues/120

**Comment by asofold** [comment]
Build 951 contains a fix amttempt. If there is other edge values for damage it'll fail there, couldn't produce other, so i'll wait on feedback.

**Comment by asofold** [comment]
Can the fix be confirmed (build 955 roughly)?

**Comment by RoboMWM** [comment]
Not the case for me: https://gist.github.com/RoboMWM/3a99f096a5b886bf83f47fce88c0687c

**Comment by asofold** [comment]
Why is this showing up in the notifications!? There is no update-reference here (comment / referenced-by / ...)...

**Comment by RoboMWM** [comment]
Sorry, I commented here and then deleted, and moved my report to #137

**Comment by asofold** [comment]
No problem :) - i was just wondering, because there is no trace of an edit shown here.
