### ISSUE TITLE
Slabs

### ISSUE THREAD

**Issue by christheking** [NoCheatPlus/Issues#126]
Players can't walk up slabs, they go to walk up and it just pushes them back down. Survival fly false positives.

---- Version information ----
#### Server ####
git-Spigot-23e921f-8b69bdd ~MC: 1.9~
detected: 1.9
#### NoCheatPlus ####
Plugin: 3.13.7-RC-sMD5NET-b925
MCAccess: 1.4.5-1.8.8|? / CB-Reflect
Features:
blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
checks: FastConsume | Gutenberg
Hooks: AllViolations~NCP~ 1.0
#### Related Plugins ####
ProtocolLib v3.7.0-SNAPSHOT-b258

**Comment by Platinteufel** [comment]
Fixed in dev builds.

**Comment by asofold** [comment]
Please update to development builds of NCP for 1.9: http://ci.md-5.net/job/NoCheatPlus/
Please also keep checking for updates for 1.9, as things will get fixed. Change list might help judging if it is more or less risky to advance to the next development build:
* Jenkins: http://ci.md-5.net/job/NoCheatPlus/changes
* Build infos: https://github.com/NoCheatPlus/Docs/wiki/Build-Infos

We'll release once we have ironed out the biggest issues.

**Comment by christheking** [comment]
I am using the latest build and it's still effecting the server.

**Comment by asofold** [comment]
Assume fixed in dev builds.

**Comment by craftrise** [comment]
Problem continuing with spigot 1.8.8.
@asofold 

and console message:

[NoCheatPlus] PacketPlayOutPosition: Teleport confirm id not available, field mismatch: 0

**Comment by asofold** [comment]
You can't walk on slabs with MC 1.8.8 ? Could you perhaps add the full output of the 'ncp version' command?

**Comment by craftrise** [comment]
@asofold Yes: http://prntscr.com/fm52qz

**Comment by asofold** [comment]
Probably some cross-plugin thing with ViaVersin - slabs shouldn't be a problem normally.

**Comment by craftrise** [comment]
I removed the "Viaversion" plugin, but the problem persists.
