### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by niqoar** [NoCheatPlus/Issues#127]
Hi!
How I can optimize this?

![timings](http://i.imgur.com/XiNmmgI.png)

server version: craftbukkit 1.8.8
ncp version: 3.13.7-RC-sMD5NET-b925

**Comment by asofold** [comment]
The sample size is very small, and there is likely other side effect that affect the timings on that account, such as JIT not being 'warmed up', or thread switches. We suggest to get at least 200000 better 1000000+ moving events for a better reference on the average processing time.

We'd also prefer to see the full output of the 'ncp version' command, please include it whenever opening a new issue (server + ncp versions are most essential, but some other things might be of relevance too).

**Comment by niqoar** [comment]
output of the ncp version

![ncp version](http://i.imgur.com/64nyUK1.png)

**Comment by asofold** [comment]
Did you take a longer sample, with >200000 or better >1000000 on the  PlayerMoveEvent  count (might show as 100k or 1M then).

**Comment by niqoar** [comment]
![timings2](http://i.imgur.com/cVDJTQD.png)

**Comment by Platinteufel** [comment]
Wow .. could you paste your full timings? There must be another cause ..

**Comment by asofold** [comment]
This selection looks strange, i'd also like to see the full timings. For one thing it shows 800 k event per tick - i assume that's due to pasting part of the log, or do i misinterpret the report!?

The Pct total could be correct, though it would be slightly beyond the the heavy side of what we've seen so far.

**Comment by niqoar** [comment]
Sorry for the delay: http://timings.aikar.co/?url=15416883

**Comment by asofold** [comment]
Those timings still look odd/warped, e.g. it reports everything as if happened within one server tick. 

Did you really paste the full timings report into the web interface thing? Perhaps it's easiest to create a new report and ensure to paste the full one...

**Comment by asofold** [comment]
Closing as 'invalid', despite not knowing what/why. I assume timings produced the ordinary way would look much different. If this/similar stays an issue, please add a link to the timings without any editing taking place (raw data is also usable).
