### ISSUE TITLE
Violation Notifications not functioning

### ISSUE THREAD

**Issue by DiarchDiandi** [NoCheatPlus/Issues#128]
For the past few dev builds, notifications for violations have not been working. Even with the notification permission. I have even tried /ncp notify on and still nothing.

**Comment by asofold** [comment]
Could you still post the full output of the 'ncp version' command, just to have some reference for comparison?

In addition:

- Which build did the notifications still work?
- Which permission plugin are you using, and

**Comment by DiarchDiandi** [comment]
---- Version information ----
#### Server ####
git-Spigot-104c8c8-00d3334 ~MC: 1.9~
detected: 1.9
#### NoCheatPlus ####
Plugin: 3.14.0-SNAPSHOT-sMD5NET-b950
MCAccess: 1.9 / Spigot-CB-1.9_R1
Features:
blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9
checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter
Hooks: AllViolations~NCP~ 1.0 | Citizens2~cncp~ 2.0 | mcMMO~cncp~ 2.3
#### Related Plugins ####
CompatNoCheatPlus v6.6.3-SNAPSHOT-sMD5NET-b84 | ProtocolLib v3.7.0-SNAPSHOT-b258

I am using PermissionsEX and there's been no updates for that.
Last version that notifications were working for me was build #931.
About CompatNoCheatPlus, notifications were not working before that was added. Only added it 3 days ago.

**Comment by asofold** [comment]
Quite odd. You could still try setting subscriptions to true in the configuration (logging section ~ ingame, just search for subscriptions).

**Comment by DiarchDiandi** [comment]
Enabling logging in my configuration fixed it. Thanks!

**Comment by asofold** [comment]
Oh, hehe.
