### ISSUE TITLE
No Slowdown [DBO 808]

### ISSUE THREAD

**Issue by MyPictures** [NoCheatPlus/Issues#13]
What is the problem? What do you expect to see instead?
There is a new mod called NoSlowDown (Also found in hack clients) where a player continues running as they eat or shoot a bow.
Mod link: http://www.minecraftforum.net/topic/1605239-152-noslowdown-works-in-smp/

Can it be reproduced systematically and if so: How?
The only for it to happen, is that if the player has the mod or has enabled the hack in a client.

Which version of NC+ are you running? (Check with /version NoCheatPlus or /ncp version on your server)
543 Dev build

What's your NoCheatPlus configuration file version? (config.yml copy the first line in here)
 Configuration generated by NoCheatPlus 3.9.4-DEV-b543.

Did you change anything in your NC+ configuration file? If yes: What did you change?
I have only changed up the fight-setting of the config, to attempt to make them more accurate, so it should not effect this, as this is an interact event?

On which Craftbukkit/Craftbukkit++/Spigot build do you run your server on? (Simple execute /version)
937 Dev

How easy is it to reproduce? Does it always happen? Does it happen to all players? Does it happen with vanilla clients?
Only happens with the mod/hack client that has the feature

Do you run any other special plugin next to NC+ (Spout, mcmmo, heroes and others)?
Nope

Please provide any additional information below (logs, screenshots, plugin list, player amount, .....)?
 (Use http://dev.bukkit.org/paste/ or http://pastebin.com/ and add the link here if linked resources are longer than a few lines.)<<<

http://youtu.be/V6p3NQKNpzQ?t=42s

Small vid showing the actual hack/mod in use.

I have attempted to make a small update to one of my plugins, to try and stop it, and it kind of works, but not great.
I basically check to see if the use is holding a bow, if yes, then it waits 10 ticks, and checks if they are sprinting and if they are holding the bow, and have arrows in their inv (Since players continue to run if they don't have Arrows to shoot.), if they are then it kicks them for NoSlowDown. This could maybe be a way to avoid the hack, but the player may enable NoSlowDown after the 10 ticks, so I am not sure if it will work then.

An additional question:
I don't know if this is possible, but is there a way to know if a player is using sprint hacks and Aimbot attack? Aimbot attack is when the player looks at the target and hits, unlike Aura where the player does not need to look (Aura is detectable, but ForceField is not). Also how can I make direction more sensitive? Do I increase 'penalty' or decrease it?

Thank you

**Comment by MyPictures** [comment]
**ProdigyOG:** "NoSlowDown bypass (allows you to sprint while blocking your sword): http://pastebin.com/zmPQ6azh "

**Comment by MyPictures** [comment]
**asofold:** "I'd like people to consider this:

https://www.youtube.com/watch?v=Ulr5rhdCCfM "

**Comment by asofold** [comment]
Closing as superseded: Check the [INDEV issue](https://github.com/NoCheatPlus/Issues/issues/418) instead.
