### ISSUE TITLE
Hungry + Creative = Not work sprint on creative.

### ISSUE THREAD

**Issue by andris155** [NoCheatPlus/Issues#136]
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/13960529/fb91f75e-f058-11e5-82ba-76d0be3e5268.PNG)

**Comment by asofold** [comment]
This is for normal moving, not flying?

**Comment by andris155** [comment]
sprint and press space walk on the floor.

**Comment by andris155** [comment]
https://hub.spigotmc.org/jira/browse/SPIGOT-2051

**Comment by andris155** [comment]
Fixed latest spigot 1.9.

**Comment by asofold** [comment]
Oh great, thanks for noting.
