### ISSUE TITLE
NoCheatPlus 1.9 Unable To Walk

### ISSUE THREAD

**Issue by gustavwww** [NoCheatPlus/Issues#139]
I am running an minecraft 1.9 server. I am using NoCheatPlus.

NoCheatPlus (http://ci.md-5.net/job/NoCheatPlus/955/)
CompatNoCheatPlus (http://ci.md-5.net/job/CompatNoCheatPlus/84/)
Protocollib (http://ci.dmulloy2.net/job/ProtocolLib/258/)

Players cannot move for real. I have tried this alot. I am using the versions above.
It is NoCheatPlus that occures the issue. This is checked!

Thank you!

**Comment by asofold** [comment]
Is your spigot version up to date? Best post the full output of the 'ncp version' command with new , it'll also clarify on server versions :).

**Comment by gustavwww** [comment]
I am using the version of spigot that my server host has as an default. But maybe i can try to change?

**Comment by asofold** [comment]
Could you post the spigot version? Please also ensure to check if your hoster has updated it/something for 1.9.

The spigot project keeps fixing bugs and it's not been such a long time since 1.9 'started', so it's quite recommendable to run the latest spigot build rather.

If the version your hoster provides is too old, i'd suggest getting BuildTools.jar to work and build your own version. There has been a related issue with the early builds of spigot, and there has been other issues as well. Can't know 100%, but with a hoster-provided spigot version i'd not be surprised.

**Comment by gustavwww** [comment]
Okay, when running buildtools. Should i pick the one named Spigot-1.9. Or should i go to Spigot > Spigot-Server > target > and pick the one named Spigot-1.9-SNAPSHOP?

**Comment by asofold** [comment]
I'll post the relevant links:
* https://www.spigotmc.org/wiki/buildtools/
* https://hub.spigotmc.org/jenkins/job/BuildTools/
* https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

You might need to install some of the prerequisites, as explained on the wiki page linked above. I'd use the latest BuildTools.jar from their jenkins.

**Comment by gustavwww** [comment]
Yes, thanks, i know, but would i use the spigot jar thats not generating in a map?? :)

**Comment by asofold** [comment]
I don't understand 'the spigot jar thats not generating in a map' :). 

Once you've run the BuildTools, there might be copies of the generated jars put into the starting directory. I usually use the Spigot/Spigot-Server/target/spigot-1.9R0.1-SNAPSHOT.jar !

**Comment by gustavwww** [comment]
Yes, it is. Just forget it xD
I Will try to use the latest

**Comment by gustavwww** [comment]
I mean the, spigot-1.9.jar

**Comment by gustavwww** [comment]
Becuse thats what i think other servers is using, else, i Will try the one you are using.

**Comment by asofold** [comment]
Those jars are identical (spigot-1.9...). Just use the one with the same name as your hoster already put there, or rename it to what they normally use for the server jar. Some hosters (most?) only allow a certain name for the server jar, such as minecraft-server.jar or craftbukkit.jar. whatever.

**Comment by gustavwww** [comment]
Just changed version and it do now works! Thanks alot!

**Comment by asofold** [comment]
Wonderful, thanks for cooperating :).
