### ISSUE TITLE
Command logging [DBO 606]

### ISSUE THREAD

**Issue by MyPictures** [NoCheatPlus/Issues#14]
==What is the problem? What do you expect to see instead?==
Currently there is no way to tell what command NoCheatPlus has been executing over strings because of curtain violation level.

It would be nice to have a feature which throws out debug information if a command has been executed by NoCheatPlus and which command exactly. Could be handled by debug=true in the config or a own flag would be fine also.

**Comment by asofold** [comment]
Always look out for the curtain violation level!

**Comment by asofold** [comment]
Added in 1090. For command actions.
