### ISSUE TITLE
Issue with 1.9 pvp

### ISSUE THREAD

**Issue by LaughNgamez** [NoCheatPlus/Issues#140]
Seems like there's many many more false positives particularly users being pulled back when moving while being hit. It also seems that knockback items above 1 level cause a user to be pulled back.

Seems like there's many more false positives in respect to moving/moving while pvping

**Comment by asofold** [comment]
Could you add the full output of the 'ncp version' command (including related plugins and all)? It's just needed :) , and we always have to ask back a couple of times, making things much slower.

For a wild guess: If you're on 1.9, checks.fight.pvp.knockbackvelocity could be set to true, to see what it'll do to the matter.

**Comment by LaughNgamez** [comment]
![untitled](https://cloud.githubusercontent.com/assets/12781929/14042559/3a9a2b52-f238-11e5-8094-780bd9f9c19c.png)


There's the output of the version. Only related plugin is compactnocheatplus. I'll look into that check thanks, but it seems before updating to 1.9 NCP & spigot this was not an issue.

**Comment by LaughNgamez** [comment]
Currently the check is set to:
pvp:
knockbackvelocity: default

I'll see what setting it to true does, I also looked for documentation on the check but couldn't find any. Could you please describe it?

**Comment by asofold** [comment]
That seems to be still undocumented. The knockbackvelocity switch allows to control, if NCP assumes the server-side velocity events to be broken for pvp. This concerns knockback/velocity dealt with melee attacks, just for pvp.

Force-enabling it will risk that NCP allows cheaters about twice or two times in a row the velocity. We might update it to always work such, that it'll update the next velocity event instead of assuming velocity to be added each hit, so the risk of activating this is minimized.

**Comment by asofold** [comment]
Why haven't i mentioned...

Your version of cncp might be outdated. Ensure to at least use build 83: http://dev.bukkit.org/bukkit-plugins/compatnocheatplus-cncp/files/40-cncp-6-6-2-rc-smd5net-b83/

Your version of ProtocolLib also is outdated, you should consider updating to 3.7 or later: http://ci.dmulloy2.net/job/ProtocolLib/

(If your spigot version is provided by the hoster, you should also check how old it is, might check on IRC. If possible build the latest one yourself - just in case.)

**Comment by Kakifrucht** [comment]
Is the knockback issue something you still want to fix or an issue on the users side?

**Comment by asofold** [comment]
@Kakifrucht What is an issue on user side :) ? The question is, what/why this happens, and what we have to d about it.

Have you tried if it works with setting checks.fight.pvp.knockbackvelocity to true instead of default?

**Comment by Kakifrucht** [comment]
Oh nice that apparently fixed the issues! Thanks

**Comment by asofold** [comment]
I'll change the default behavior then, just needed the confirmation that this is related.

**Comment by asofold** [comment]
Assume fixed, please open a new issue report for specific issues with development builds around build number 960 and later.
