### ISSUE TITLE
NCP stops End-Portal regeneration

### ISSUE THREAD

**Issue by minoneer** [NoCheatPlus/Issues#142]
When respawning the Enderdragon in 1.9 by placing the four crystals, the portal is usually regenerated. This doesn't work with NCP enabled for players without override permissions. Debug log:

`[23:19:02 INFO]: NCP: [VL] [BLOCKPLACE_REACH] [minoneer] [->(+)minoneer] VL=1.7(+1.7) health=19.399999618530273/20.0 reachdistance=1.7407996302969542 `

Placing the last crystal actually causes a MultiBlockPlaceEvent to be fired for the player with Material type Bedrock and all portal blocks as blocks being placed. Might be the cause for this.

Server version: CraftBukkit version git-Spigot-90839e6-1865896 (MC: 1.9)
NCP-Version: 3.14.0-SNAPSHOT-sMD5NET-b955

**Comment by asofold** [comment]
Need to add extra logging and reproduce...
