### ISSUE TITLE
Walking on slabs bug  [NoCheatPlus]

### ISSUE THREAD

**Issue by noobskills** [NoCheatPlus/Issues#148]
If you go on a slab, it teleports you away from it. And if it is a 3x3 slab area and you jump in the middle, you will be stuck there.

**Comment by MyPictures** [comment]
Could you upload a screenshot how exactly you build it? Are the slaps in the upper or lower area of a block?

**Comment by noobskills** [comment]
Lower

**Comment by Platinteufel** [comment]
Invalid, update to the latest dev build

**Comment by Platinteufel** [comment]
#126

**Comment by noobskills** [comment]
does still not work....

**Comment by asofold** [comment]
Currently for MC 1.9 NCP development build 959 should work.

**Comment by asofold** [comment]
Setting to 'invalid', assuming it's already been fixed.
