### ISSUE TITLE
1.9 Teleportation 

### ISSUE THREAD

**Issue by MyPictures** [NoCheatPlus/Issues#154]
From IRC, we can poke Thinkofname if more infos are required:

<Thinkofname> MyPictures|AFK: doesn't appear NCP handles 1.9 style teleports correctly

<Thinkofname> 1.9 changed teleporting from Ack'ing the teleport packet with an identical packet from the player to a the new TeleportConfirm packet
<Thinkofname> looks like NCP's protocollib handling still expects the old way

<Thinkofname> I looked at the code. In practice the old way should work (most of the time) for now but that can change later

<Thinkofname> ( the packet is this one btw http://wiki.vg/Protocol#Teleport_Confirm )

**Comment by asofold** [comment]
I had been looking forward to the packet, but i found it not to work as well as the 'ack move'.

It was missing very often and lead to more inconsistent tracking (not sure on 1.9.2, would need to re-check with new logs).

**Comment by Thinkofname** [comment]
@asofold It should be sent in the same places as the old ack move was sent. If it was inconsistent the server would ignore all the movement packets from the player until it was sent

**Comment by asofold** [comment]
@Thinkofname  Perhaps the skipped replies meant all following packets got ignored on server side then. Are you sure this logic really applies to all special places like cancelled moving events, where the server used to send back a simple position packet instead of engaging in the teleport (+bukkit event) logic?

I should log these and test things out again.

**Comment by Thinkofname** [comment]
I replaced all those cases with teleports to handle this system, maybe this happened after you tested though

**Comment by asofold** [comment]
Yes, i will want to re-test and adjust then.

**Comment by asofold** [comment]
Implemented around 1090 - not sure to which impact.
