### ISSUE TITLE
NCP doesn't kick for Spam and results in server crash.

### ISSUE THREAD

**Issue by Darkfield** [NoCheatPlus/Issues#159]
Logs: https://gist.github.com/Darkfield/e830aba2a7748005c5d10846adeca58d
Config: http://pastebin.com/AD1GWUR4

Logs when NCP succesfully blocked attack: https://gist.github.com/Darkfield/51fd382a063afc6256e7f2e8cf82f7ba

Currently: 3 times crashed, 1 time blocked.

Why NC+ doesn't block all attacks?

Seems like they are able to spam 18k messages and server runs out of threads, rams and crashes, but why NC+ doesn't kick them for these so many times? Event were cancelled, but still NC+ should ignore it and kick for these kind of numbers

**Comment by asofold** [comment]
So your suggestion is, that NCP still checks cancelled events? 

Why are messages cancelled before NCP receives them, is it a muting or chat manager plugin?

**Comment by Darkfield** [comment]
Would be nice if you would add in config option for chat/command messages to not ignore cancelled events.

I have disabled chat function in where you /spawn it's kind of protection to prevent appearing spam messages in chat.

**Comment by asofold** [comment]
Are you in control of that plugin code? I'd suggest running anti cheating on 'lowest' event priority and muting and other on higher priority, e.g. 'low' , so anti cheating is first.

Checking cancelled events can lead to other problems, like compatibility issues with cancelled-by-default events, e.g. a plugin fires events/packets and intercepts them early.  Code complexity might become unfeasible, in case we have listeners on multiple priorities, some of which are intended to skip cancelled events. So i am somewhat reluctant to have cancelled events be processed. In this case it may not be such a big issue, adding an option.

**Comment by Darkfield** [comment]
Seems like I found temp solution for my problem, but it's only temp. I were logging cancelled messages with Bukkit.getLogger().info, removed this line and they are unable to crash server anymore, but still I need to log cancelled messages.

**Comment by asofold** [comment]
Logging messages or sending messages without rate-limiting has more often been a cause of trouble.

If you cancel the messages on EventPriority.LOW (and perhaps/preferably log on EventPriority.MONITOR), NCP can do the other stuff on EventPriority.LOWEST before the other stuff is running. So you are in control of that plugin code, or am i wrong?

**Comment by Darkfield** [comment]
Yes I'm in control and removing cancelled messages logging resulted in fixing the crash with bots.

**Comment by asofold** [comment]
Alright, thank you for the reference - will close as 'resolved' then.
