### ISSUE TITLE
Horizontal clipping through doors and fencegates [DBO 636]

### ISSUE THREAD

**Issue by MyPictures** [NoCheatPlus/Issues#16]
==What is the problem? What do you expect to see instead?==
If you have a hacked client on, you can stand ~ 5 blocks away from a door or fencegate and open it on your client screen. Hop out of freecam, walk over to the door (best is to have a quicker running speed hack on), run into the door then enable fly and you will end up on the other side of the door eventually. On some occasions the player flags survival fly when trying to fly through the door.

==Can it be reproduced systematically and if so: How?==
It can be reproduced by doing what I said above, if you need assistance I can make a video.

==How easy is it to reproduce? Does it always happen? Does it happen to all players? Does it happen with vanilla clients?==
It's very easy to reproduce,  it's successful almost every time. It's only do-able with a hacked client.

==Versions of NCP and server: Post the output of the "ncp version" command!==
3.10.2-RC-sMD5NET-b620 (latest version of today)

==Details about the configuration file of NCP.==
//(Examples: What version of NCP was the config generated with? Did you change anything - if so: add a quick description.)//\\
Newly genned config, strict passable, survival fly, etc. and custom vclipping plugin on the server.

==Do you run any other special plugin next to NC+ (adding skills, machines, adding/changing blocks)?==
//(Examples: SpoutPlugin, mcMMO, Heroes, MachinaCraft and others.)//\\
No.

**Comment by MyPictures** [comment]
**asofold:** "Doors and fence gates are not safe to use, in order to make them safe a lot of caching would be necessary to prevent players not being able to pass through them at all, thus we won't fix this quickly.

This is similar to the pistons problem, due to latency the time window for the player may well be "zero", i.e. the door is closed on server side due to redstone at the time the player has received a packet telling that there is an open door. Thus we would have to monitor redstone and all block changes and cache recently open doors/trapdoors/moved-pistons etc. in order to allow players to pass through a short time even after the door close, otherwise it would be unplayable.

So this is all complicated and leads to more memory and cpu consumption, though fancy to have.

Though this is a known issue on the lists, i still suggest not to rely on ordinary doors for real safety..."

**Comment by MyPictures** [comment]
**asofold:** "Apart from fence gates, are fences protected by the latest (beta) release on BukkitDev?"

**Comment by MyPictures** [comment]
**Jyystin1337:** "The vanilla door glitch is very easy. How it's done: http://youtu.be/uIYTehVSntE

If you can't get through the iron door like i did with the wooden door (going inside the block a little, and after that breaking the block under), you can try to lag your internet in some way to be able to break both of the iron door blocks, move into them just a tiny bit and then stop the net lag. After that you just break the block under you as i did in the video."

**Comment by asofold** [comment]
Will somewhat be part of the block change tracking system, but can keep open until we are there.

**Comment by asofold** [comment]
Closing as fixed, due to deprecating the ignorepassable part (and having a new implementation of passable in place). So soon we'll have 'can't move through door' with redstone and timer-driven stuff.
