### ISSUE TITLE
Kicked with DecoderException (protocol/bungeeprotocolsupport 1.5.2-1.8.8)

### ISSUE THREAD

**Issue by SliderKP** [NoCheatPlus/Issues#162]
17.04 23:47:04 [Disconnect] User Lugatup has disconnected, reason: Internal Exception: io.netty.handler.codec.DecoderException: NettyChannelInjector.decode() did not read anything but decoded a message.

My server is a mininetwork 1.8.8 with protocolsupport and bungeeprotocolsupport (supports 1.5.2 to 1.8.8) and my users get this error only when NCP is active.

Edit by NCP: Changed title to reflect known side conditions better.

**Comment by asofold** [comment]
Could you post the full output of the 'ncp version' command (text much preferred)?

We need everything, extra to the fact that protocol compatibility is used. Specifically the build of NCP and the version of ProtocolLib are important here (if used), but best paste the whole thing.

**Comment by asofold** [comment]
Assume both server and plugin versions to be superseded by new ones.
