### ISSUE TITLE
SurvivalFly kick with Jump Boost effect false positive is back!

### ISSUE THREAD

**Issue by Zaino60** [NoCheatPlus/Issues#163]
This was fixed before but it seems to be back with the 1.9 NCP update. Example of how false positive happens: https://gyazo.com/d4948c503137fe7ccffcfb9daa437895

**Comment by asofold** [comment]
Could you post the full output of the 'ncp version' command (please prefer text over screenshots, client or server logs have it)?

**Comment by Zaino60** [comment]
NCP Version: https://pastee.org/nn7sq
Yes, it happens without blocks above

**Comment by asofold** [comment]
Just to clarify: The server version shows MC 1.8.8 - so with '1.9 NCP update' you refer to using latest NCP on MC 1.8?

Need to reproduce + debug log - unfortunately i am in the middle of slightly larger additions+changes, so i hope @MyPictures can produce a debug log. You could too, having a look at: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players

**Comment by asofold** [comment]
Has this been resolved with the latest dev builds of NCP (988+) ?

**Comment by asofold** [comment]
Assuem fixed.
