### ISSUE TITLE
BHopping, a new form of movement speed hacking

### ISSUE THREAD

**Issue by MarkElf** [NoCheatPlus/Issues#165]
**What is the problem? What do you expect to see instead?**
It seems that clients such as wolfram have a new method of allowing players to move at a slightly higher speed (http://prntscr.com/ay1rub). Through the client likely spamming spacebar while sprinting, players are able to move quicker through a natural looking jump, making it somewhat harder to pick up that said players are moving faster. Not quite sure if anything could be done about it as it is similar to vanilla moment in some respect, just sprinting and spamming spacebar.

**If it can be reproduced please try to explain as detailed as possible (video, text or images are always welcome):**
Video someone had made for me: https://www.youtube.com/watch?v=mDIS05m6onU
Another video with BHopping shown to me, also includes other blunt hacks functioning, of which I am aware Jesus' and Blink's progress under issue 34/37 - https://youtu.be/xQVAxGXm3YA?t=120
**a) Does it affect all players on your server?** It generates an unfair advantage under any speed related circumstances, such as running towards/away from others pvp'ing.
**b) Is it easy to reproduce?/Does it always happen?** With a client, yes - just begin sprinting and the client jumps for you.
**c) Does it also happen if you use a unmoded vanilla client?** Possibly, however, I've been yet to reproduce it without a client in terms of how smooth it is from jump to jump.

**Have you made any (noteworthy) changes to the default configuration of NCP?** Tested it with the default configuration - works flawlessly.

**Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?** Ran with just the latest development build, build 960.

**What is your NoCheatPlus version? Server version? (/ncp version)** http://prntscr.com/ay1rdb (Default Configuration, Paper Spigot 1.8.8, from March 6, 2016)

**Comment by asofold** [comment]
How much faster do they move? Can it be estimated... 10% 50% 100%?

**Comment by MarkElf** [comment]
After a bit of extensive testing, it does seem to be roughly about the same speed, perhaps 1-2% faster, with wolfram, than the average player due to it likely spamming spacebar, or forcing the player to jump perfectly once it reaches the ground, reducing the time between jumps. I suppose it isn't a large issue but it does provide a minor advantage as the average player cannot sprint over randomized snow piles as well as someone with BHop, players without BHop tend to get stuck when hitting 3-4 stacked while a player with BHop isn't stopped but instead is allowed to jump over the pile.

With Wurst, it seems to be roughly 3-5% faster. ~13 seconds to go over a 100 block line while normally it takes roughly 14 seconds. Wolfram seems to be 1-2%, faster as I stated before. I suppose it may very, but I was specifically asked to test the following clients: Glade B4, Virtue, and Midnight which may have a larger difference.

**Comment by asofold** [comment]
Previously we have been assuming that they can speed up to 30% with packet speeding, possibly combined with other methods (move distance).

So 5% would be a great improvement for us :). Likely thew  bunnyhopping method is meant to stay under the radar of many different kind of checks, thus it isn't pushing all sorts of limits.

Best reference would be a debug log of using that cheat (checks.debug set to true for a local/private test, or on-the-fly debugging: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players). If you could gist/zip-link such a test run, it could be very interesting (please no downloads from obscure sites with java script  needed :p). It needs a little bit of experience how to confine the log to what is needed, a 100 blocks run should be ok with log file set to a folder and using ncp reload before and afterwards. If you can't do this, perhaps @MyPictures or someone else could test the Wurst or other clients with logging on.

**Comment by MarkElf** [comment]
Debug log: http://paste.md-5.net/yiveyoxige.coffee
I would like to note the following:
-The player has to run at first to sprint full speed for wurst, otherwise, they end up just jumping and moving forward, wolfram's is much smoother. The log is with wurst.
-Within the first trialt, I ran for a few milliseconds then toggled bunny hopping. and ended up accidentally jumping off the 1x100 platform.
-Within the second trial, I ran for a few milliseconds and toggled Bhopping, ending on the 100th block.
-Within the Third trial, I ran for a few milliseconds and toggled Bhopping and ended up walking the few remaining blocks.

**Comment by asofold** [comment]
I'd like to announce, that ...

the latest build contains a new command, which is useful for rough time measurement.

'ncp stopwatch ...'  abbreviate with sw, examples:
* 'ncp sw start'  and 'ncp sw stop', stop can be done with other types too (!).
* 'ncp sw distance (distance)' <- The clock stops automatically with having taken that distance. Very useful for speed estimation, think of 100 blocks for very reliable time (for horses include 300 blocks as well, is better :p).
* 'ncp sw return (radius)' Will stop automatically, once you return to that position within the specified diameter. Useful for parkour.

I'd love to see timings for both vanilla (depending on base of comparison... is it walking, plain sprinting or bunnyhopping) and specific cheats/clients, preferably for a standard measure of 100 blocks (meters). So we can finally have some reliable measure of comparing speed cheats.

From there on we'll tackle this topic.
* ''

**Comment by VrektHF** [comment]
I've ran this test with my own 'bhop' speed, (does work on NCP). Keep in mind people are able to go faster then me, aswell if I had a speed potion it would probably be half the time.

http://prntscr.com/bh5npi

The first result is using 'Bhop' and the second result is normal sprint jumping.

**Comment by asofold** [comment]
@VrektHF I get 14.2@100 with a local test server (normal flag ground), so that's realistic then. So bhop gets people to roughly 40% speed up, which is a little more than our assumption of 30% from a couple of years ago. I'll soon try to patch this down below 10% somehow.

**Comment by CheatSupport** [comment]
Yeah, please try and fix this. It's a really bad issue (not blaming the issue on you) and I am hoping it can be patched soon enough.

**Comment by asofold** [comment]
Should be confined to bout 15% max by now. More may be following.

Closing as (partly) fixed, currently not intending to:
* Detect the specific cheat (patterns/ban).
* Prevent pseudo bhop (like appear to be sprinting without jumping).
