### ISSUE TITLE
Stacktrace on event

### ISSUE THREAD

**Issue by Kakifrucht** [NoCheatPlus/Issues#170]
https://pastebin.com/ishKfbbR

This one happens pretty frequently, I don't know when exactly though. I'm using your latest dev build on git-Spigot-e6f93f4-935f18b.

**Comment by asofold** [comment]
Thanks a lot!

Next build will contain changes that hopefully resolve this issue.

**Comment by Kakifrucht** [comment]
Appears to be fixed, thanks!

**Comment by asofold** [comment]
Thanks :).
