### ISSUE TITLE
Add You are temporarily denied to join this server. as translatable phrase

### ISSUE THREAD

**Issue by EvilOlaf** [NoCheatPlus/Issues#172]
I noticed that  `You are temporarily denied to join this server.` as phrase seems to be hardcoded as I can not find it in the `config.yml`.
Would be nice if this message becomes adjustable.

Thanks for reading.

**Comment by asofold** [comment]
Good point. These probably shouldn't be postponed until we add extra files for translations.

**Comment by asofold** [comment]
This has just been implemented (~ 967). See strings section msgtempdenylogin.

**Comment by EvilOlaf** [comment]
Nice. Are there any known show stopper issues in the latest dev or is it halfway save to use?

**Comment by asofold** [comment]
It's certainly [BLEEDING]. Few people may be using/testing those and there have been experimental additions for vehicles, in addition to a couple of ordinary bug fixes.

So there is a good bit of uncertainty, possibly rather increasing with upcoming builds. If you focus on stability, you might rather want to stay on 960.

Upcoming changes will concern vehicles in the first place.

**Comment by EvilOlaf** [comment]
Aight. Thanks.
