### ISSUE TITLE
Labymod Support

### ISSUE THREAD

**Issue by Kakifrucht** [NoCheatPlus/Issues#176]
I was wondering if the Mod disable function of Nocheat is still functional? And if so, do you plan to add any support for Labymod, to disable any functionality that gives players an edge?

**Comment by asofold** [comment]
Is there a web page for that mod? Do they support the server communicating feature support?

**Comment by Kakifrucht** [comment]
It's a very popular mod with good functionality, however it also comes with certain PvP functions, such as damage indicators and some more. I really would like people to use it, as I feel that it certainly improves the whole Minecraft experience, but at the same time I would like certain features disabled.
Website https://www.labymod.net/
It does come with support to disable mods server side, there is also a plugin for this on spigot (https://www.spigotmc.org/resources/antilaby-1-9-disable-labymod-functions.21345/).

**Comment by asofold** [comment]
Out of range at present, left to contributors. Closing as postponed: https://github.com/NoCheatPlus/Issues/projects/6
