### ISSUE TITLE
Entity handle error

### ISSUE THREAD

**Issue by rErEaT** [NoCheatPlus/Issues#179]
WARN [NoCheatPlus] [MOVING_VEHICLE_ENVELOPE] Can't handle entity type: MINECART
 WARN [NoCheatPlus] [MOVING_VEHICLE_ENVELOPE] Can't handle entity type: HORSE
 WARN [NoCheatPlus] [MOVING_VEHICLE_ENVELOPE] Can't handle entity type: BOAT

NoCheatPlus 3.13.7-RC-sMD5NET-b972

**Comment by asofold** [comment]
Nothing to worry about, we'll remove those or replace them by actual checks. Currently latest dev builds have a boat fly check, and the other types of vehicles are not handled, so we have a warning printed. We might confine the warning to worlds where flying is enabled (vanilla setting, legit players can't fly just with that on) Keep checking for updates.

**Comment by asofold** [comment]
This has been removed/fixed.
