### ISSUE TITLE
Inventory.fastclick Bug [DBO 655]

### ISSUE THREAD

**Issue by MyPictures** [NoCheatPlus/Issues#18]
==What is the problem? What do you expect to see instead?==
If you fill up your inventory with any block, hold down shift and spam click and certain inventory slot, it begins to start flagging fastclick and gets up to pretty high ranges.

==Can it be reproduced systematically and if so: How?==
See above.

==How easy is it to reproduce? Does it always happen? Does it happen to all players? Does it happen with vanilla clients?==
Always happens to every player even on vanilla clients.

==**Versions of NCP and server: Post the output of the "ncp version" command!**==
spgiot 1107 3.10.2

==Details about the configuration file of NCP.==
//(Examples: What version of NCP was the config generated with? Did you change anything - if so: add a quick description.)//\
Latest config

==Do you run any other special plugin next to NC+ (adding skills, machines, adding/changing blocks)?==
//(Examples: SpoutPlugin, mcMMO, Heroes, MachinaCraft and others.)//\
None

**Comment by MyPictures** [comment]
**asofold:** "Basically NCP is using old compatibility workarounds still - CraftBukkit does provide a lot of useful stuff by now (at least i think so).

Using the latest CB events means to either doing another partial redesign or to scrap backwards compatibility, so i am not entirely sure when / how to bring such in, though we will recode the fastclick stuff for sure in the future."

**Comment by asofold** [comment]
Can happen with lag etc - will rather be question of recode or other latency/lag estimation.
