### ISSUE TITLE
Wurst hacked client bypass every checks!

### ISSUE THREAD

**Issue by rErEaT** [NoCheatPlus/Issues#185]
my players can cheat with "wurst client"

I am using the latest nocheatplus dev build.

**Comment by asofold** [comment]
What do you mean by 'can cheat' and what do you mean by 'bypass every check'?

**Comment by rErEaT** [comment]
fly checks, freecam etc

so they can use cheats, test it yourself :)

**Comment by asofold** [comment]
-> freecam: can't be prevented, it's (at first) entirely client side. Perhaps you have other specific cheats in mind?
-> fly checks: this would be very severe, could be an indicator that NCP isn't running at all.

Proceed:
* Please post the complete output you get with running the 'ncp version' command! We need the information to judge things quickly.
* Please check your server log for any kind of warnings or errors (might be translated to your language, english would be 'warning', 'error', 'severe', or also search for the word 'exception').

**Comment by rErEaT** [comment]
25.05 14:05:09 [Server] INFO ---- Version information ---- 
25.05 14:05:09 [Server] INFO #### Server #### 
25.05 14:05:09 [Server] INFO git-Spigot-e000104-4cb3258 ~MC: 1.9.2~ 
25.05 14:05:09 [Server] INFO detected: 1.9.2 
25.05 14:05:09 [Server] INFO #### NoCheatPlus #### 
25.05 14:05:09 [Server] INFO Plugin: 3.14.0-SNAPSHOT-sMD5NET-b978 
25.05 14:05:09 [Server] INFO MCAccess: 1.9-1.9.3 / Spigot-CB-1.9_R1 
25.05 14:05:09 [Server] INFO Features: 
25.05 14:05:09 [Server] INFO blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 
25.05 14:05:09 [Server] INFO checks: FastConsume | AttackFrequency | FlyingFrequency | KeepAliveFrequency
25.05 14:05:09 [Server] INFO defaults: pvpKnockBackVelocity 
25.05 14:05:09 [Server] INFO packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter 
25.05 14:05:09 [Server] INFO #### Related Plugins #### 
25.05 14:05:09 [Server] INFO ProtocolLib v4.0.1

there is no error or warn in the log :/

**Comment by asofold** [comment]
And you are sure they are actually able to fly?

Is there any legitimate game mode changing or flying features/plugins involved? Also with changing worlds between game mode change or fly-nofly change?

**Comment by asofold** [comment]
People didn't happen to be op or having bypass/wildcard/'*' permissions during testing?

**Comment by asofold** [comment]
I assume this isn't really bypassing, and perhaps some bypass was set accidentally (or unpatched offline mode issues).

Of course they can still activate their fight cheats, but the checks in NCP should still be in place, as effective they are right now.

Thus closing as 'invalid', feel free to add details or open a new ticket, if this can be tracked down to be the case without any bypass permissions etc.
