### ISSUE TITLE
Launching players with TNTdoesn't work

### ISSUE THREAD

**Issue by Nubebuster** [NoCheatPlus/Issues#187]
As the title says, placing tnt below a player so launch them places them back. This really ruins the tnt aspects of the game.

**Comment by MyPictures** [comment]
Please try to follow the https://github.com/NoCheatPlus/Issues/blob/master/CONTRIBUTING.md as much as possible. /ncp version is really important for us to do something.

I would assume this is in creative gamemode?

**Comment by asofold** [comment]
Please do post the output of the 'ncp version' command, as that's crucial to judging the basic side conditions for virtually anything that happens.

**Comment by Nubebuster** [comment]
@asofold You should add a template like here: https://github.com/OpenRCT2/OpenRCT2/issues
That way people wont forget stuff when reporting bugs

**Comment by Nubebuster** [comment]
I will upload a video in a moment

**Comment by Nubebuster** [comment]
Version: git-Spigot-e4d4710-e1ebe52

TNT cannon *with* NCP (op)
https://www.youtube.com/watch?v=Z8K6_NRt98w&feature=youtu.be

TNT cannon *without* NCP (not op)
https://www.youtube.com/watch?v=sXBrZeYxQFI&feature=youtu.be

**Comment by asofold** [comment]
I need a debug log of this one, running with development build 988 or later (NCP build 988: http://ci.md-5.net/job/NoCheatPlus/, debug log: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players).

If i have time+success to reproduce this, no debug log will be needed, it just would speed up things a lot.

**Comment by Nubebuster** [comment]
I can't reproduce the bug with the version you linked

**Comment by asofold** [comment]
Alright, thanks :). We'll try to release 'soon', just we need to cover all/most vehicles.
