### ISSUE TITLE
Permissions caching [DBO 656]

### ISSUE THREAD

**Issue by MyPictures** [NoCheatPlus/Issues#19]
I have recently been doing some performance monitoring on my production server (usually 300-500 players online) and I noticed that NoCheatPlus was taking up a fair amount of CPU time.

Whilst this is to be expected with a plugin such as this, it actually turns out that some of the biggest hits on performance come from permissions checking, especially in checks such as survival fly.

I am proposing that permissions are 'cached' in some way to prevent the massive amount of calls to hasPermission.

**Comment by MyPictures** [comment]
**asofold:** "That's interesting. Do you have any data that could help us judge things?

Specifically i would be interested in....

- Timings
- Profiling data (permission calls, other to judge against), like a percentage of the permission checks vs. the MovingListener.onPlayerMove call processing time.
- Permissions plugin

(For timings we always need edge data like time measured, number of events, average or total time, in order to know if we can use the data - just in case, sometimes people give us timings with only few thousands of moving events.)

Caching permissions for some tasks has been considered as an option from the start, however we need more data to judge if such really pays. It would be configurable, because some are using setups with region-specific permissions, for instance."

**Comment by MyPictures** [comment]
**asofold:** "Checking somewhat recent (1.7.10?) profiling data, permission checking can be massive (survivalfly: permission checks roughly double the checking time, which is a lot, given that survivalfly is quite an intense check)."

**Comment by MyPictures** [comment]
**asofold:** "Perhaps we will try to implement a "likely not to fail" variation here, guarding with timing and position, to at least not re-check all the time with repeated survivalfly violations, or actions like attacking or interacting from the same position.

Once there, we might also allow different policies, like block change only / world based / configurable timeout intervals, plus other like lazy init."

**Comment by asofold** [comment]
This will likely be implemented, perhaps rather sooner than later - prerequisite is changing PlayerData to not ever get removed while a player is online (only remove lazily/bulk later on).

Until then: https://github.com/NoCheatPlus/Issues/projects/6
