### ISSUE TITLE
Magicspells no longer do damage in pvp in 1.9.4

### ISSUE THREAD

**Issue by tara81** [NoCheatPlus/Issues#190]
No cheat is blocking all spell damage using magicspells since 1.9.4 with cncp.

**Comment by asofold** [comment]
CompatNoCheatPlus will be discontinued in favor of other solutions built into NCP and/or MagicSpells. Currently it's not such a favourable situation though. I'll see what i can do for instant damage spells inside of NCP for a quick thing.

**Comment by asofold** [comment]
Could you provide the output of the 'ncp version' command as well as the MagicSpells version (and where you got it from... dev.bukkit.org?) ?

I'd also like to know what checks of NCP alert for damage spells - for comparison run 'ncp info PLAYER_NAME' before and after applying a spell - if possible please just post the input here (paste/gist if you like, but likely not necessary).

**Comment by asofold** [comment]
Assume superseded, see latest of NCP + cncp.
