### ISSUE TITLE
Non-fixed private cheat

### ISSUE THREAD

**Issue by MoofMonkey** [NoCheatPlus/Issues#191]
https://yadi.sk/d/KobuDoedsG376
Please fix this

**Comment by asofold** [comment]
Could you describe the issue shortly and provide the output of the 'ncp version' command in _text form_ (only applies, if it's your server at all)?

**Comment by MoofMonkey** [comment]
Working on all 1.5.2 NoCheatPlus
Cheat at 1.5.2 (can't move to 1.7+ - haven't sources)

**Comment by asofold** [comment]
The latest versions of NCP should still be supporting Minecraft 1.5.2, if you're using an older version of NCP .-.. that would be pointless. So if you're running on one of the latest releases or development builds (soon to release a new version), i'd really like to see the output of the 'ncp version' command.

**Comment by asofold** [comment]
Please always consider checking this page, if you are not sure which version of NCP to use with your version of Minecraft:

 https://github.com/NoCheatPlus/Docs/wiki/Notable-Builds

* HeadInBody is relevant?
* Don't know is relevant?
* Kill aura is always relevant. Ensure to keep checking for updates of NCP though.

Closing as 'duplicate', please check out existing tickets for individual issues/cheats rather, and/or create one if the search doesn't show any related tickets.
