### ISSUE TITLE
SurvivalFly issue with chests and slabs

### ISSUE THREAD

**Issue by FuRiouSOne** [NoCheatPlus/Issues#193]
Spigot 1.9.4
NCP 3.14.0 b960

Players are constantly getting stuck on any slabs and chests if they try to walk/jump on them. 
Disabling the check for SurvivalFly allows them to walk/jump normaly on/over them.

**Comment by asofold** [comment]
Build 960 doesn't cover Minecraft 1.9.4. Currently rather the latest development build should do (988+) - release will be soon, one or two fixes will still be in.
