### ISSUE TITLE
Error in console with MythicMobs

### ISSUE THREAD

**Issue by Bodyash** [NoCheatPlus/Issues#197]
![default](https://cloud.githubusercontent.com/assets/2454569/15821538/00b788b2-2bf9-11e6-8ed2-529a87b4c2a6.PNG)
Doesnt know what that means.

**Comment by asofold** [comment]
Could you show that error (preferably in text form) to the MythicMobs maintainers? 

It looks like they trigger a player teleportation asynchronously (not from within the primary server thread), which is a problem. It has the potential to lead to crashes and data inconsistencies, plugins usually don't account for standard events firing off the primary thread either, increasing potential trouble on that account.

You could just link this issue or cite my text above.

**Comment by asofold** [comment]
Closing as 'can't fix', since this should be dealt with by the MythicMobs maintainers (probably already has been).
