### ISSUE TITLE
Fast Nether portal usage [DBO 658]

### ISSUE THREAD

**Issue by MyPictures** [NoCheatPlus/Issues#20]
Using the timer hack which allows the game to run faster than normal, you can speed up the process of going through a nether portal. When a normal player needs to wait 4 seconds before teleported to nether, hackers don't need to wait almost at all. Traveling to nether happens in less than a second when gone in to a portal block with a timer hack on.

Tested on:
git-Bukkit-1.6.4-R2.0-1-g988f599-b2919jnks <MC: 1.6.4>
NCP:
Plugin: 3.10.6-SNAPSHOT-sMD5NET-b640
McAccess: 1.6.4 / CB2882-DEV

**Comment by asofold** [comment]
https://github.com/NoCheatPlus/Issues/projects/6
