### ISSUE TITLE
Bunny Hop abuse?

### ISSUE THREAD

**Issue by MyPictures** [NoCheatPlus/Issues#200]
@Dionis reported this for me and I tried it out myself. Its some kind of bunny jump abuse. It seems to allow quicker hopping and also more control (move while in air - left or right).
I created a debug log for reference:
[bHop.txt](https://github.com/NoCheatPlus/Issues/files/303480/bHop.txt)

[22:34:39 INFO](Features:): ---- Version information ----
[22:34:39 INFO](Features:): #### Server ####
[22:34:39 INFO](Features:): git-Spigot-550ebac-7019900 ~MC: 1.8~
[22:34:39 INFO](Features:):   detected: 1.8
[22:34:39 INFO](Features:): #### NoCheatPlus ####
[22:34:39 INFO](Features:): Plugin: 3.14.0-SNAPSHOT-sMD5NET-b989
[22:34:39 INFO](Features:): MCAccess: 1.8 / Spigot-CB-1.8_R1

[22:34:39 INFO](Features:):   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
[22:34:39 INFO](Features:):   checks: FastConsume | Gutenberg
[22:34:39 INFO](Features:):   defaults: pvpKnockBackVelocity
[22:34:39 INFO](Features:): Hooks: AllViolations~NCP~ 1.0 | TestNCPHook 1.0
[22:34:39 INFO](Features:): #### Related Plugins ####
[22:34:39 INFO](Features:): ProtocolLib v3.7-SNAPSHOT-b244

**Comment by asofold** [comment]
I think this still duplicates the speeding issue , though: https://github.com/NoCheatPlus/Issues/issues/7

Looks like really making used of some of the bunny hopping constraints.

Please include 'ncp stopwatch distance 100' next time !

**Comment by MyPictures** [comment]
It looks different then what I know from #7 tho and I still cant figure that stopwatch command out :large_blue_circle:

**Comment by asofold** [comment]
Just _/ncp stopwatch distance 100_ ... 
* Keep the delay between 'return/enter' and starting to sprint as low as possible.
* Use the same testing conditions for comparison with vanilla/other-cheats (100 blocks flat ground, vs. uphill/idk), always make the parkour/lane longer than 100 blocks (idk 5-10 more to each side).
* It'll stop automatically after you reach 100 blocks distance from where you issued the command.

The other ... as discussed already: The log is interesting for the speeding ticket, the direction changing is another issue and will be approached in a different way.

**Comment by asofold** [comment]
How fast is it?

**Comment by MarkElf** [comment]
#165

**Comment by MarkElf** [comment]
#165

**Comment by Iceee** [comment]
Really fast
https://www.youtube.com/watch?v=RyTZJFXANq8

**Comment by MarkElf** [comment]
On a flat surface, I seem to average at 15.7.
On wolfram, I moved 100 blocks in 15.2 seconds.
On Wurst, I seemed to move 15.3 seconds
(It would likely be 15.2 or 15.1 however Wurst's requires you to toggle it after sprinting to move faster, otherwise you just jump awkwardly)

I assume that these are much slower than Glade b4 and other clients though as @VrektHF obtained  10.3 seconds in issue #165

**Comment by asofold** [comment]
The point is always to compare running with cheat vs without cheat, of course you need the same potion effects and attributes.

Looks like 10 vs 14 is a little bit too much, so i'm considering a direction to set off to.

**Comment by Curtis3321** [comment]
Any updates on this?

**Comment by asofold** [comment]
Currently stuck watching news.

**Comment by Xayanix** [comment]
Bump!

**Comment by asofold** [comment]
Will soon push something [BLEEDING] which i'd like to be tested with speeding/dolphin - and of course false positives.

**Comment by asofold** [comment]
Speed should be down to 15%, see other tickets. In-air (but also on-ground) direction changing is another topic and shopuld be treated extra.
