### ISSUE TITLE
Standing on top of slabs, ender chests, and chests causes players to freeze

### ISSUE THREAD

**Issue by jflory7** [NoCheatPlus/Issues#203]
_Related to #56, #202._

1. **What is the problem? What do you expect to see instead?**

* Whenever a player stands on top of any slab block, an ender chest, or regular chests, NCP will cause them to freeze and they are unable to move on top of the blocks. They are able to teleport away using `/spawn`, `/home`, or similar commands. When players do this, it fires multiple **Passable** checks specifically.

![Screenshot of checks](https://i.imgur.com/ALiwzMr.png)

2. **If it can be reproduced please try to explain as detailed as possible (video, text or images are always welcome):**

* Does it affect all players on your server?
 * All players are affected (excluding ones who bypass checks).
* Is it easy to reproduce?/Does it always happen?
 * Every time.
* Does it also happen if you use a unmodded vanilla client?
 * All tests were made with vanilla, standard clients.

3. **Have you made any (noteworthy) changes to the default configuration of NCP?**

* Only minor changes over a long period of time… which I know is very unhelpful. I avoid touching the configuration when possible and my configuration is probably 95% stock.

4. **Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?**

* Our server is semi-vanilla, so we aim to have as close to a vanilla experience as possible. There are no plugins that affect the movements, abilities, or speed of regular players.

5. **What is your NoCheatPlus version? (_/ncp version_)**

* * 3.15.0-SNAPSHOT-s${BUILD_SERIES}-b${BUILD_NUMBER} (built from source @ commit 19312bdbfa9430bfefc539082281a364669f9b1a).

6. **What is your server version? (_/ncp version_ or _/version_)**

* PaperSpigot, git-Paper-776 ~MC: 1.10~

7. **Please provide any additional information below! Use GitHub, http://pastebin.com/ or similar for huge logs!**

* @stevoism, @dellman135, and @Natzic have been spending a little more time on my server than me, and they might be able to add anything in case I missed anything glaringly obvious.

**Comment by asofold** [comment]
I strongly assume this is about having built without the craftbukkit-1.10-R0.1-SNAPSHOT dependency.

On compiling see: https://github.com/NoCheatPlus/NoCheatPlus/blob/master/README.md#compiling-nocheatplus

To be on the safe side for MC 1.10, set both a build parameter names _spigot1_10_r1_ to true and add _-P spigot_1_10_r1_ to the maven goals (activate the profile of that same name). Or build another profile, as listed there.

**Comment by asofold** [comment]
Jenkins is ready again. So builds for 1.10 will be provided there too.

It's been a decision to have the minimal build profile be the default (without craftbukkit dependencies), with the reflection based compat module as the fall-back. Unfortunately the reflection based module is the first to be left as-is, when time isn't enough.

**Comment by asofold** [comment]
Assume resolved.

**Comment by jflory7** [comment]
@asofold Yes, sorry, rebuilt today and all standing issues for this ticket were fixed. Cheers!

**Comment by asofold** [comment]
No  question, i was being optimistic  about the 'thumbs up' emoji, so i closed it, having tested 1.10 a little bit - perhaps too early.
