### ISSUE TITLE
1.10: Minecarts false positives with vehicle.envelope

### ISSUE THREAD

**Issue by asofold** [NoCheatPlus/Issues#204]
Looks like moving upwards with minecarts on powered rails leads to false positives on 1.10.

**Comment by asofold** [comment]
Build 1004 contains a patch/fix attempt.

**Comment by MyPictures** [comment]
You can fly with minecarts also? Thought they were still server sided on 1.9.

**Comment by asofold** [comment]
Good question, also for pigs. It's not been such a big difference... prefer to have them covered for now. With configuration it'll be deactivatable later on.

**Comment by asofold** [comment]
On swiftly having a look at nms/PlayerConnection i don't see a difference, but perhaps there is one.

**Comment by asofold** [comment]
Anyway, that's another question, feel free to open a ticket for it :).
