### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by DutchUser** [NoCheatPlus/Issues#209]
Server Version: Spigot 1.10
NCP Version: http://i68.tinypic.com/14lmpsg.png

16.06 00:04:27 [Server] WARN Exception in thread "Craft Scheduler Thread - 4" 
16.06 00:04:27 [Server] INFO Registered for fr.neatmonster.nocheatplus.components.modifiers.IAttributeAccess: fr.neatmonster.nocheatplus.compat.cbdev.AttributeAccess
16.06 00:04:27 [Server] INFO Registered for fr.neatmonster.nocheatplus.components.location.IEntityAccessLastPositionAndLook: fr.neatmonster.nocheatplus.compat.cbdev.EntityAccessLastPositionAndLook

**Comment by asofold** [comment]
Please don't link 'ncp version' output to an external site, instead please just paste it fully here, _or use the 'Attach files by dragging & dropping or selecting them'_ feature of the ticket creation/editing here on GitHub.

The text posted here doesn't seem to contain errors related to NCP - the _"16.06 00:04:27 [Server] WARN Exception in thread "Craft Scheduler Thread - 4" "_ part can't be judged as it's incomplete, could you show more context from that log? There should be a stack trace printed with an actual error.

**Comment by asofold** [comment]
The horse messages are from vanilla (...). One can get them with riding up stairs, likely other ways too.

The [INFO] lines from NCP are not an error, though they may look a little bit scary - it's just messages about internal registries. They'll later probably be put to file only.

So the warning message may be from some other plugin or a part is missing.

**Comment by DutchUser** [comment]
Is there an way to fix that horse are not kinda bugging?

And second. I cant findt the error back. I restarted the server multple times.

**Comment by asofold** [comment]
That's Minecraft with 'moved wrongly' :p ... there is indeed a setting in the spigot.yml (i think there , not bukkit.yml), which is about moved-wrongly-threshold.

You could increase that value and hope it doesn't allow something extreme otherwise (player moving is monitored by NCP anyway, with vehicles horizontal distances need to be done still, except for more than extreme moves, which are covered already)

**Comment by DutchUser** [comment]
I just found an other issue that causing an shit load of spam. When an player try to walk on (See Schreen) 
[IMG]http://i65.tinypic.com/2hzpwte.png[/IMG]

**Comment by asofold** [comment]
Check out this ticket: https://github.com/NoCheatPlus/Issues/issues/215

Should be that issue, you can update NCP or apply the workaround suggested there. Updating probably is better.

**Comment by asofold** [comment]
Assume resolved/superseded by updating.
