### ISSUE TITLE
Off primary thread call to hasByPass for INVENTORY_OPEN

### ISSUE THREAD

**Issue by TheChampTF** [NoCheatPlus/Issues#211]
Hey

Have a few issues with latest dev. build http://paste.yu8.me/?c46f4237bd177561#w/KyaTkRviUfEcC0FSAI5dOos+NPBKdzpB3wZtZjkQ4=

**Comment by asofold** [comment]
Looks like the GadgetPortalGun feature of the UltraCosmetics plugin is causing player teleporting off the primary thread.


Standard Bukkit events that always fire from within the primary thread, here firing off the primary server thread can't really work. Neither the server nor plugins are prepared for such, and it's not feasible to design towards this.

So i strongly suggest contacting the authors of the UltraCosmetics plugin for the asynchronous teleportation issue. Not sure if the per-world plugin is involved, should mention that one and/or link the paste there as well.

**Comment by iSach** [comment]
@asofold Hello.
I'm the author, asynchronous teleportation can't be made in Minecraft? Well, I'll put it synchronous, thanks for info.

**Comment by asofold** [comment]
@iSach Virtually all of the Bukkit API is not thread-safe, unless stated otherwise in the java docs. So in general one can't really access anything of relevance asynchronously. Throughout the past there have been some things that worked, e.g. senbd

**Comment by iSach** [comment]
@asofold Alright, thanks for the info. ^^

**Comment by asofold** [comment]
Setting to can't fix (probably it's resolved), as this has to be fixed externally.
