### ISSUE TITLE
FastLadder

### ISSUE THREAD

**Issue by MarkElf** [NoCheatPlus/Issues#213]
**What is the problem? What do you expect to see instead?**
FastLadder, on every client that I've tested with, works and isn't blocked by any means with the default configuration, version 1.8 with the latest development build, build 1015.
A notification for SurvivalFly is sent however it is not blocked by any means.

**If it can be reproduced please try to explain as detailed as possible (video, text or images are always welcome):**
It can easily be reproduced via any hacked client, enabling 'FastLadder' and walking towards a ladder.
A .gif of such can be found here: https://giphy.com/gifs/GLhpGfERG5G00

**Comment by asofold** [comment]
Could use a debug log :).

**Comment by MarkElf** [comment]
I found the source of wolfram's FastLadder working, the cause was on my end - my apologies for that, however looking farther into FastLadder across other clients, Lucid's fastladder does function - it allows for players to move a faster up ladders.

Debug log for the client Lucid using FastLadder: http://paste.md-5.net/jihatipepu.coffee
A .gif of Lucid's FastLadder being used can be found here: https://giphy.com/gifs/o7H40keqI8Gzu
A screenshot of the stopwatch can be found here: http://prntscr.com/bk2f1s - it seems to be roughly 45% faster than normal.

**Comment by asofold** [comment]
I don't see any violations in the log, is the allviolations hook disabled hard?

Is it configured to always cancel?

**Comment by asofold** [comment]
Next build will contain a distinction of ascend and descend (still hard-coded). Could lead to new edge cases, but that's probably better with being able to even tell edge cases.
