### ISSUE TITLE
Soil ~ issue with moving.

### ISSUE THREAD

**Issue by asofold** [NoCheatPlus/Issues#215]
Possibly jumping out of water onto soil, possibly survivalfly or passable.

Soil may have melon stems with melons one block further on land.

Need reproduce + debug.

**Comment by hurrgurl** [comment]
Unable to walk on soil in general, works fine with passable off.

**Comment by asofold** [comment]
@hurrgurl I can't reproduce it on MC 1.10 with NCP build 1015.

Are you sure you have the appropriate build of NCP for your version of Minecraft? With 1.9/1.10 i recommend rather using build 1013 currently (Jenkins). Otherwise how to reproduce ...

**Comment by minoneer** [comment]
It is only the case with 1.10.1 and 1.10.2 clients. According to release logs, 1.10.1 changed the farm block offset: 

> [Bug MC-85162] - Slight player/mob offset when on Farmland Block (https://mojang.com/2016/06/minecraft-1101/)

**Comment by asofold** [comment]
Build 1016 contains an adaption for a fix. You would need to update cncp to the latest jenkins version as well (!), while cncp shouldn't be needed for Citizens anymore, mcMMO stuff hasn't been built into the core yet.

The workaround for not updating currently would be to add an entry to the compatibility.blocks.overrideflags section, namely:

SOIL: default+ground_height

This would allow standing on any height of that block, however at the cost of being able to pass through it.

**Comment by hurrgurl** [comment]
@asofold
Oh wow, I didn't even realize MC was updated.

Yeah, sorry about that. I was on the latest version. (1.10.1+)

**Comment by CoolLord22** [comment]
This issue is still persisting for me. I'm using viaversion with the latest NCP build 3.15.2-SNAPSHOT-sMD5NET-b1117 I tried adding the SOIL into overrideflags but it didn't do anything.

EDIT: If the players connect using 1.9 (server version) it works completely fine. However, when they connect with 1.12 (version that is allowed by ViaVersion) they cannot move inside the farmland at all.

**Comment by asofold** [comment]
@CoolLord22 And your server is what version ? Could post /ncp version ...

I'll probably add something to confine height between two values.

**Comment by CoolLord22** [comment]
eeek! sorry forgot to paste it somehow, my bad!
[13:08:29 INFO]: #### Server ####
[13:08:29 INFO]: git-Spigot-c6871e2-0cd0397 ~MC: 1.9.4~
[13:08:29 INFO]:   detected: 1.9.4
[13:08:29 INFO]: #### NoCheatPlus ####
[13:08:29 INFO]: Plugin: 3.15.2-SNAPSHOT-sMD5NET-b1117
[13:08:29 INFO]: MCAccess: 1.9.4 / Spigot-CB-1.9_R2
[13:08:29 INFO]: Features:
[13:08:29 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9
[13:08:29 INFO]:   checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[13:08:29 INFO]:   defaults: pvpKnockBackVelocity
[13:08:29 INFO]:   packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
[13:08:29 INFO]: Hooks: AllViolations~NCP~ 1.0
[13:08:29 INFO]: #### Related Plugins ####
[13:08:29 INFO]: ProtocolLib v4.3.0 | ViaVersion v1.3.0

**Comment by asofold** [comment]
With the latest development build you might be lucky with adding an entry to compatibility.blocks.overrideflags:

SOIL: default + ground_height + min_height16_15 + height100

If that works, i'll make it a default workaround for if protocol plugins are in use.
