### ISSUE TITLE
Minecarts won't fall

### ISSUE THREAD

**Issue by Augustin37** [NoCheatPlus/Issues#218]
I have a problem with minecarts, they don't fall, player get stucked at the top. For example:
![Minecart wont fall](http://image.noelshack.com/fichiers/2016/25/1466731242-2016-06-24-03-17-26.png)

**Comment by asofold** [comment]
Build 1018 contains a fix attempt.

There'll be issues left with other vehicles likely (boats confirmed), something seems to have changed since 1.9.

**Comment by Augustin37** [comment]
What a fast fix!!! Thank you very much!
