### ISSUE TITLE
SurvivalFly kick with Jump Boost effect false positive is back!

### ISSUE THREAD

**Issue by Zaino60** [NoCheatPlus/Issues#220]
-    What is the problem? What do you expect to see instead?
  When you have Jump Boost effect ABOVE level 33, it detects SurvivalFly violation. Expected nothing to happen, since Jump Boost is a vanillia effect and is not hacking
-    If it can be reproduced please try to explain as detailed as possible (video, text or images are always welcome):
  a) Does it affect all players on your server? Yes
  b) Is it easy to reproduce?/Does it always happen? Yes, you just need to get the Jump boost effect above level 33 (For example: jump boost 40), which is used A LOT for Parkour, and you can reproduce it
  c) Does it also happen if you use a unmoded vanilla client? Yes
-    Have you made any (noteworthy) changes to the default configuration of NCP? Nope, no changes
-    Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)? Nope, /effect is a vanillia command
-   What is your NoCheatPlus version? (/ncp version) https://pastee.org/j5y9b
-    What is your server version? (/ncp version or /version)
  CraftBukkit version git-Spigot-1d14d5f-ba32592 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT) 
  With ViaVersion 0.9.4 to support 1.8 - 1.10.2 clients
-    Please provide any additional information below! Use GitHub, http://pastebin.com/ or similar for huge logs!
  Example of how this bug happens with violation level output: https://gyazo.com/804b4a0ea5c8c43d75987816272112ac

**Comment by asofold** [comment]
Closing as suprseded, as it might've been fixed (can't access version paste anymore, next time plase put it in here from start :), please).
