### ISSUE TITLE
Attempted to place a tile entity

### ISSUE THREAD

**Issue by TheChampTF** [NoCheatPlus/Issues#222]
On latest Spigot build and dev. of ncp http://paste.yu8.me/?6dd9475e87a7ecfe#QY1TiYFltIpNByIHcBwORVx+TIs/6nyMPYYoS/vPA6U=

**Comment by asofold** [comment]
Looks like a world generation issue, not sure if per-world plugins plugin has to do with it, i assume rather not. Not sure we can do anything on NCP side here.

* Is your server version up to date?
* Does this happen always or often or once in a while or under certain conditions?
* Are special map generators in use?
* Did you inspect the map at that position yet (possibly better with an offline copy)?

**Comment by TheChampTF** [comment]
I'm more or less always on newest release - testing with newest release of NCP & Spigot shortly.
Think it might have happened on build 1019 that got removed from dev. page (NCP)
It happened one time so far, but always learned it's better to report things.
I use Multiverse, have skyblock and a plotworld rest is normal worlds.

**Comment by asofold** [comment]
Certainly good to report, i just can't think of any other directions to investigate right now.

**Comment by asofold** [comment]
Assume superseded by updates - despite interesting :).
