### ISSUE TITLE
Erroring on 1.8

### ISSUE THREAD

**Issue by Darkfield** [NoCheatPlus/Issues#224]
Using latest mostly stable build.

http://hastebin.com/itasuwikas.avrasm
http://hastebin.com/olebocokoy.avrasm

**Comment by asofold** [comment]
Looks like we have to name another build then. There has been a fix for this already, would roughly need to update to 'latest' (1020+) - in case of using mcMMO that would also mean updating CompatNoCheatPlus for now.

**Comment by Darkfield** [comment]
Updated to 1020, now getting rarely this:

http://hastebin.com/opayacujuq.avrasm

**Comment by asofold** [comment]
Assume suprseded / fixed.
