### ISSUE TITLE
Terrible error spam 

### ISSUE THREAD

**Issue by Loumite** [NoCheatPlus/Issues#225]
As the title says it, I get an **extremely lengthy** error message every once in a while. I have yet to find out what event specifically triggers the error. 

Here's a gist because it was too huge for pastebin: https://gist.github.com/MitesMC/f14213af26e3631a08be7dbbb172951c 

**Plugins versions:**
NoCheatPlus 3.14.0-SNAPSHOT-sMD5NET-b989
CompatNoCheatPlus 6.6.3-SNAPSHOT-sMD5NET-b86
mcMMO 1.5.05-SNAPSHOT-b136

Any help would be appreciated. I'll update this if I manage to isolate the trigger. 
Thanks in advance! :)

PS:
I wasn't kidding when I say "extremely lengthy". My host's web console that supports 300 lines cannot fit the entire error message. I had to dig into the server logs just to get the complete error message. As I type this, I'm still waiting for pastebin to come to its senses lol. The pastebin tab has been frozen since I pasted the complete error message because of how long it is. Just a comical experience I thought I'd share haha. Aaand turns out pastebin cannot even let me save it because it exceeded the paste limit for free users  (1.41MB file)!!!

**Comment by asofold** [comment]
You updated CompatNoCheatPlus without updating NoCheatPlus.

In this case there has been a breakage so either you downgrade cncp to a build earlier, or you update NCP (1018+).

**Comment by asofold** [comment]
Suprseded - NCP and cncp should be used at latest (release).
