### ISSUE TITLE
Passable and SurvivalFly false positives.

### ISSUE THREAD

**Issue by Lysandr0** [NoCheatPlus/Issues#227]
Hello there!
Recently, I’ ve noticed a few (actually three) problems with Passable and SurvivalFly.
Firstly for Passable: as soon as you collide directly with an iron bar (or a glass pane) you’ ll start raising violations; same thing if you walk next to a corner of a slab. These issues do not happen on older builds (for what I tested).
Here's three gifs about:
https://gyazo.com/5011e57e4f8ea9fdaaab798e3908e15a
https://gyazo.com/c25a2096c438277c454d5289f8b690bf
https://gyazo.com/023825b69eafe28865308768df53e72b
(it might take a while to reproduce the slab issue)

Secondly, if you do a ‘bunnyhop’ on something like this: https://gyazo.com/d77f9cc3b035e0577d519e05732b5cc9 you’ ll be restrained by SurvivalFly, despite the low violation levels generated. 
(You must do a ‘non-stop’ bunnyhop in order to reproduce this false positive as shown in this other gif:
https://gyazo.com/5a5c326ab91c456f12c7e94c4e7bb780 )

If it could be helpful, I made some ‘on-the-fly’ debug logs for reference.
[SurvivalFly(Fp).txt](https://github.com/NoCheatPlus/Issues/files/344316/SurvivalFly.Fp.txt)
[Passable(Iron bars).txt](https://github.com/NoCheatPlus/Issues/files/344317/Passable.Iron.bars.txt)
[Passable(Slabs).txt](https://github.com/NoCheatPlus/Issues/files/344318/Passable.Slabs.txt)

Default config.
Plugins: PermissionsEx, PlugMan, WorldEdit, ConditionalCommands, Essentials, EssentialsChat, ProtocolLib, NoCheatPlus, AuthMe, TestNCP.

Output /ncp version:
---- Version information ----
#### Server

 git-Spigot-6c9b0a1-de5c261 ~MC: 1.8.8~
detected: 1.8.8
#### NoCheatPlus

Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1020
MCAccess: 1.8.4-1.8.8 / Spigot-CB-1.8_R3
Features:
blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
defaults: pvpKnockBackVelocity
packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | CatchAllAdapter
Hooks: AllViolations~NCP~ 1.0 | TestNCPHook 1.0
#### Related Plugins

ProtocolLib v3.6.4

If needed, I can test all this out with a more recent version.

(Also, English isn’t my native language, so please excuse any mistakes!  :p)

**Comment by craftrise** [comment]
I have the same problem. up!

**Comment by asofold** [comment]
How did this ticket slip through !? Usually we prefer one issue per topic/item. 

@craftrise I do need to know more about the versions in use and the actual issues you have, as in this ticket several issues of different kind are mentioned. So best would be, if you could post the complete outpout that's generated with running the 'ncp version' command, preferably as text, and also describe (at least shortly) what you have issues with.

**Comment by asofold** [comment]
Closing as superseded, as ProtocolLib and NCP should've been updated until now.

Will add to std testing ground.

**Comment by Lysandr0** [comment]
> Usually we prefer one issue per topic/item.


Sorry about that, I will keep it in mind in the future. :)

Anyway, the issues / fp regarding Passable seem to be all fixed with the latest build (At least for me), while the SurvivalFly one is still present even if it doesn't flag as much as before.

**Comment by asofold** [comment]
I will attempt to address some survivalfly issues soonish,  which might include the sprint+jump stuff.
