### ISSUE TITLE
Can't move on soil mc1.10.2

### ISSUE THREAD

**Issue by iluvncp** [NoCheatPlus/Issues#228]
In #215, Mr.asofold said its already fixed.
However, today I checked in my 1.10.2 client and this problem still exist ;D

here is the short movie
https://i.gyazo.com/fd8be67d7535711da4c1089a68f5f7e8.mp4

**Comment by asofold** [comment]
Which version of NCP are you using?
Please add 'ncp version' in text form with issues, always :).

For 1.9/1.10 you should rather use current development builds.
