### ISSUE TITLE
...

### ISSUE THREAD

**Issue by Neszku** [NoCheatPlus/Issues#229]

**Comment by Neszku** [comment]
anyone here ;-;?

**Comment by asofold** [comment]
I don't see anything special. Moving checks are comparably heavy, but the plugin should stay below 5% load clearly in average.

1.x% for moving is pretty common.

We'll make some attempts to cut down things, e.g. do our own permission caching, but currently it's not bad enough and moving checks are meant to check things, so they have to create some cpu load. Later they might get optimized for performance once again, but currently that's not the main topic.

**Comment by Neszku** [comment]
https://timings.spigotmc.org/?url=18796065
Is it really normal ;-;...

**Comment by Neszku** [comment]
It's just lagging dyum

**Comment by asofold** [comment]
Sorry, i overlooked you are using a long outdated version of NCP with 1.10.x. You'll have to use ~ build 1020 from Jenkins (developement builds...), at present.
