### ISSUE TITLE
Auto Updater [DBO 683]

### ISSUE THREAD

**Issue by MyPictures** [NoCheatPlus/Issues#23]
Hey just a suggestion to add an auto updater.

Suggested updater could use: https://github.com/gravitylow/Updater

**Comment by MyPictures** [comment]
**asofold:** "Now as a ticket !

I might opt for a poll, because it is quite a decision to pull it off, because then our plugin always connects to the curse.com/API by default. Turing that off for those that are changing much of the configuration should not be a problem, though.

Could also implement ingame/other notifications and delayed/on-demand variations for actually updating."

**Comment by asofold** [comment]
https://github.com/NoCheatPlus/Issues/projects/6
