### ISSUE TITLE
Speed packet bypassing kill aura

### ISSUE THREAD

**Issue by MarkElf** [NoCheatPlus/Issues#230]
**What is the problem? What do you expect to see instead?**
It seems either a form of bunny hopping very quickly, or a quick bursts of packets allows for players to move quickly in combat, simulating teleporting around players. I had this reported to me so there isn't much more direct information that I can provide.
**If it can be reproduced please try to explain as detailed as possible (video, text or images are always welcome):**
I was provided a video of the cheat being used.
https://youtu.be/jMfR-Uw_kWo

**Have you made any (noteworthy) changes to the default configuration of NCP?**
Nope.
**Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?**
I don't believe so, I am typing this up on someone else's behalf.
**What is your NoCheatPlus version? (/ncp version)**
**What is your server version? (/ncp version or /version)**
#### Server

git-Spigot-db6de12-18fbb24 ~MC: 1.8.8~
  detected: 1.8.8
#### NoCheatPlus

Plugin: 3.14.0-SNAPSHOT-sMD5NET-b968
MCAccess: 1.8.4-1.8.8 / Spigot-CB-1.8_R3
Features:
  blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
  checks: FastConsume
  defaults: pvpKnockBackVelocity
Hooks: AllViolations~NCP~ 1.0

I would have uploaded the debug log to pastebin, or a similar site but to the log was too large for any site that I attempted to upload it to unfortunately.
[Download to debug log.](https://www.mediafire.com/?c15l0kw1774ebse)

**Comment by asofold** [comment]
Ordinary zip should do for the usual case.

So the point is that the combination of continued burst-like moving with pausing between, as if lagging repeatedly is giving them another edge?

**Comment by MarkElf** [comment]
That does seem to be the case as I mentioned before - similar to rapid uses of 'blink' with packet bursts simulating lag or as I mentioned before, it could just be a multiple very quick bunny hops with kill aura.

**Comment by Janmm14** [comment]
Can you upload the video somewhere without music or not on youtube (youtube germany blocked the video because of copyrights)
