### ISSUE TITLE
Updated from 960 to 1020 and with bukkit API somehow showing player is not in minecart, while he is.

### ISSUE THREAD

**Issue by Darkfield** [NoCheatPlus/Issues#231]
Updated from 960 to 1020 and on 1.8.8 server something weird is going on with minecarts... and checking if player is in minecart somehow it doesn't detect if you are in minecart, returns as false even if player is in minecart.

public boolean hasNoVehicle()
    {
        return getPlayer().getVehicle() == null;
    }

**Comment by asofold** [comment]
ASsume superseded by updates - pls state if issues persist.
