### ISSUE TITLE
Could not pass event FakeBlockBreakEvent & FakeBlockDamageEvent - Massive Console Spam

### ISSUE THREAD

**Issue by Raserhead** [NoCheatPlus/Issues#236]
MC - Spigot 1.9.4
CNCP - 6.6.2-RC-sMD5NET-b83
NCP - 3.15.0-SNAPSHOT-sMD5NET-b1020
MCMMO - 1.5.05-SNAPSHOT-b136

Using the tree feller MCMMO ability floods the console with these errors, it says it cannot parse the event to CNCP. My guess is either McMMO changed their method or the property is no longer used by NCP.

I tried at least "hide" the issue by changing the configuration to ignore it, by removing the "FakeBlockBreakEvent" from the block-break section of the config. The error remained by tree feller no longer worked.

Other abilities like Superbreaker required me to turn off the fastbreak function within NCP.

If there's a band aid fix I could implement until this is sorted out, that'd be great.

**Comment by MarkElf** [comment]
I would update to the latest development build of CNCP: [Click here](http://ci.md-5.net/job/CompatNoCheatPlus/lastSuccessfulBuild/artifact/CompatNoCheatPlus/target/cncp.jar).

Can you paste a portion of the error to pastebin or a similar site? I'm sure it'll be needed to some extent to resolve the issue if updating to the latest CNCP development build does not resolve your issue.

**Comment by Raserhead** [comment]
Here's both errors.

http://pastebin.com/UD5L24V9

I haven't gone through every single error it prints out, but I did skim through about 10 see if they were the same and they appeared to be.

I thought there was a development version, but I could never find it. Thanks for linking it.

**Comment by asofold** [comment]
Does the problem persist with updating CompatNoCheatPlus to the latest build on Jenkins (http://ci.md-5.net/job/CompatNoCheatPlus/)?

**Comment by Raserhead** [comment]
Ah yes, sorry. Updating fixed the issue. Thanks for the help.

Been dealing with random and seemingly causeless crashes, so this issue slipped to the back of my mind.

**Comment by asofold** [comment]
Thank you for the feedback, good luck then.
