### ISSUE TITLE
Could not pass event FakeBlockDamageEvent

### ISSUE THREAD

**Issue by CitrusFruit** [NoCheatPlus/Issues#237]
MC - Spigot 1.9.4
CNCP - 6.6.2-RC-sMD5NET-b83
NCP - 3.15.0-SNAPSHOT-sMD5NET-b1020
MCMMO - 1.5.06-SNAPSHOT-b144
Full Error - http://pastebin.com/RvBtkGf1

**Comment by asofold** [comment]
Does the problem persist with updating CompatNoCheatPlus to the latest build on Jenkins (http://ci.md-5.net/job/CompatNoCheatPlus/)?
