### ISSUE TITLE
Placing signs with offhand triggers autosign detection

### ISSUE THREAD

**Issue by Kakifrucht** [NoCheatPlus/Issues#238]
The sign will also be blank.

Build b1020, git-Spigot-7745d45-02d704b (MC: 1.10.2)

**Comment by minoneer** [comment]
Same issue here

**Comment by asofold** [comment]
Fix attempt in build 1022.

**Comment by minoneer** [comment]
Awesome, seems to work!

Thanks for the quick support - it really is a joy to report bugs for NCP.

**Comment by Kakifrucht** [comment]
Thanks, can confirm the fix aswell.
