### ISSUE TITLE
Pixelmon Version? 1.7.10

### ISSUE THREAD

**Issue by Shane1199** [NoCheatPlus/Issues#239]
I am needing a version for the Pixelmon mod 3.5.1 that supports the fast boots, because currently is will punish the player for "Speed" hacking when using that legit item. My server runs on Cauldron for 1.7.10. Thanks!!!

**Comment by asofold** [comment]
Which version of NCP are you using (/ncp version)?

**Comment by Shane1199** [comment]
It states:
---- Version information ----
#### Server ####
1.7.10-1492.150 ~MC: 1.7.10~
detected: 1.7.10
#### NoCheatPlus ####
Plugin: 3.13.7-RC-sMD5NET-b925
MCAccess: 1.4.6|1.4.7|1.5.x|1.6.x|1.7.x|1.8.x|? / Bukkit-API
Features:
blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | MCAccessBukkit
defaults: enforceLocation
Hooks: AllViolations~NCP~ 1.0
#### Related Plugins ####
ProtocolLib v3.7-SNAPSHOT-b232

**Comment by Shane1199** [comment]
I just downgraded and added CNCP:

15.07 00:38:39 [Server] INFO ---- Version information ----
15.07 00:38:39 [Server] INFO #### Server ####
15.07 00:38:39 [Server] INFO 1.7.10-1492.150 (MC: 1.7.10)
15.07 00:38:39 [Server] INFO (detected: 1.7.10)
15.07 00:38:39 [Server] INFO #### NoCheatPlus ####
15.07 00:38:39 [Server] INFO Plugin: 3.12.0-BETA2-sASO-b813
15.07 00:38:39 [Server] INFO MCAccess: 1.4.6|1.4.7|1.5.x|1.6.x|1.7.x|1.8.x|? / Bukkit-API
15.07 00:38:39 [Server] INFO Features:
15.07 00:38:39 [Server] INFO blocks: BlocksMC1_4(base) | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | MCAccessBukkit
15.07 00:38:39 [Server] INFO defaults: enforceLocation
15.07 00:38:39 [Server] INFO Hooks: Citizens2(cncp) 2.0

**Comment by asofold** [comment]
I'd rather upgrade to latest development build, but i am not sure if that will resolve the issue.

Interesting would be a debug log for a couple of set-backs with the latest development build: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players

**Comment by asofold** [comment]
Closing as superseded. Perhaps it's fixed, otherwise cauldron support might be the issue.
