### ISSUE TITLE
Notification on insufficient permissions [DBO 685]

### ISSUE THREAD

**Issue by MyPictures** [NoCheatPlus/Issues#24]
A player that owns the "nocheatplus.command.commands" permissions is able to list all nocheatplus commands using /nocheatplus or /ncp. However if this person tries to execute a sub command which he/she doesn't have permissions for the NoCheatPlus will simply list all commands again.

I think it would be better to give a little notification to that person (which owns the command.commands permissions) that he/she has insufficient permissions to execute that command instead of just listing all commands for him/her again.

This should also be less confusing for some of our users that maybe misspelled a permission or simply forgot to add in properly.

Suggestions:
"You have insufficient permissions!"
"You need <permission> to execute this command!"
If you have any other please feel free to write them here as comments.

**Comment by MyPictures** [comment]
**asofold:** "Also usage printing should be more instructive (individual per command)."

**Comment by MyPictures** [comment]
**MyPictures:** "Would be even better yea. Users should get better notifications if something went wrong while they tried to execute a ncp command."

**Comment by asofold** [comment]
https://github.com/NoCheatPlus/Issues/projects/6
