### ISSUE TITLE
Captcha BUG

### ISSUE THREAD

**Issue by ThinkHO** [NoCheatPlus/Issues#241]
Good morning,I found that there is a BUG with Captcha.
I am using Paperspigot1.10.2 and NCP#1021
When I testing the Caotcha.I found that whether I type the right codes or the wrong codes.It always said that I type a wrong code.I have try to use the default config.yml and it still have this problem.
Hope you can fix it.Thank you.
It is a nice and useful plugins.

**Comment by asofold** [comment]
Did you ensure to type exact case ?

**Comment by ThinkHO** [comment]
Yes,I have try to use default config and type "captcha".It still have this problem.

**Comment by asofold** [comment]
You type "captcha"?  This needs disambiguation somehow :).

So you typed the code in exact case, like Xb2nR7", not xb2nR7 ?

**Comment by ThinkHO** [comment]
This is the config:

chat:
    captcha:
      active: true
      skip:
        commands: false
      characters: abcdefghjkmnpqrtuvwxyzABCDEFGHJKMNPQRTUVWXYZ2346789
      length: 6
      question: '&cPlease type ''&6[NOTBOT]&c'' to continue sending messages/commands.'
      success: '&aOK, it sounds like you''re not a spambot.'
      tries: 3
      actions: cancel cmd:kickcaptcha vl>4 log:captcha:2:5:cf cancel cmd:kickcaptcha

And I type "NOTBOT".(If i need to type '&6[NOTBOT]&c' ?)

**Comment by asofold** [comment]
I'm confused...

The configuration must contain [captcha]  in order to have NCP replace that part with the randomly generated letters that you have to type then.

So the question should look like '&cPlease type ''&6[captcha]&c'' to continue sending messages/commands.' and the player will see something like 'Please type Xb27n5C to continue...' and then they have to type Xb27n5C .

**Comment by ThinkHO** [comment]
Oh,I think this problem will remove in future.So I just modift the config again.:D

**Comment by ThinkHO** [comment]
I am sorry.I will confirm it again and give you a reply.

**Comment by asofold** [comment]
@ThinkHO No problem :).

**Comment by ThinkHO** [comment]
I have modify the config to this and reload the ncp:

chat:
    captcha:
      active: true
      skip:
        commands: false
      characters: abcdefghjkmnpqrtuvwxyzABCDEFGHJKMNPQRTUVWXYZ2346789
      length: 6
      question: '&cPlease type ''&6[captche]&c'' to continue sending messages/commands.'
      success: '&aOK, it sounds like you''re not a spambot.'
      tries: 3
      actions: cancel cmd:kickcaptcha vl>4 log:captcha:2:5:cf cancel cmd:kickcaptcha

I have test it as a player.I just saw a message:"Please type ''[captche]'' to continue sending messages/commands."
The ''[captche]'' haven't replace by something else.

**Comment by ThinkHO** [comment]
It work now...I am sorry............

**Comment by asofold** [comment]
No problem :).
