### ISSUE TITLE
Bug with Farmland block

### ISSUE THREAD

**Issue by niqoar** [NoCheatPlus/Issues#243]
Spigot 1.8.8
NoCheatPlus 3.13.7-RC-sMD5NET-b925	

Video by @Sitmobedaf: https://www.youtube.com/watch?v=DJ_os5XpquM&feature=youtu.be

**Comment by MarkElf** [comment]
I do believe that this issue was resolved in the latest development build already.

http://ci.md-5.net/job/NoCheatPlus/lastSuccessfulBuild/artifact/target/NoCheatPlus.jar

**Comment by Sitmobedaf** [comment]
@niqoar, check it with build-1005 http://ci.md-5.net/job/NoCheatPlus/1005/

**Comment by niqoar** [comment]
Is corrected with the latest development build

**Comment by asofold** [comment]
thx .
