### ISSUE TITLE
setFallDistance doesn't work

### ISSUE THREAD

**Issue by MClausz** [NoCheatPlus/Issues#244]
When NoCheatPlus installed, plugins that do setFallDistance(0) to non-op players will make no effect.

**Comment by asofold** [comment]
Cheats can fake 0 fall distance, thus NCP will enforce fall damage based on the highest point the player reached before/during an in-air phase.

Thus setting the fall distance to 0 will not have an effect for most cases.

Possible would be to in addition hook into NCP to remove fall distance accounting: MovingData.getData(player).clearNoFallData() 

Not sure there is a simple/doable way of detecting plugins (re-) setting the fall distance, as clients could force fall damage by vanilla any time or use micro moves to increase fall damage wihtout bukkit plugins noticing. There might be ways/concepts without extra events, though.

**Comment by asofold** [comment]
Setting to can't fix. If anyone has an idea about how to this (technically)... fell free to add.

**Comment by asofold** [comment]
https://github.com/NoCheatPlus/Issues/projects/6

Currently i can only suggest that plugins try to become compatible somehow - e.g. advertise this via an extra event, or hook into NCP directly and adjust the nofall data.

**Comment by amadeusmz** [comment]
Looks like the method MovingData.getData(player) is gone, so how can I deal with this?

**Comment by amadeusmz** [comment]
@asofold

**Comment by asofold** [comment]
@MClausz 

You have to fetch via PlayerData#getGenericInstance with MovingData.class as argument: https://github.com/NoCheatPlus/NoCheatPlus/blob/master/NCPCore/src/main/java/fr/neatmonster/nocheatplus/players/PlayerData.java#L866

Convenience, if PlayerData is not there: https://github.com/NoCheatPlus/NoCheatPlus/blob/master/NCPCore/src/main/java/fr/neatmonster/nocheatplus/players/DataManager.java#L253

Docs (API) need an update for this ... could make a ticket for this.
