### ISSUE TITLE
Boat triggers MorePackets

### ISSUE THREAD

**Issue by MClausz** [NoCheatPlus/Issues#246]
How it happens:
Player A get on a boat
Player B get on that boat
A ride the boat, then get off the boat.
B and the boat will teleport to the location where the boat started moving.
Sorry for my English, please tell me if you can't understand it clearly.

**Comment by mibby** [comment]
@asofold Boats also seem to trigger quite a lot of survivalfly violations.

NoCheatPlus dev 1021

**Comment by asofold** [comment]
This issue clearly seems to be related to 'two passenger issues': https://github.com/NoCheatPlus/Issues/issues/207

**Comment by sigmaroot** [comment]
Note: To prevent this teleportation: Disable `check.moving.vehicle.envelope.active` or give the following permission: `nocheatplus.checks.moving.vehicle.envelope`

**Comment by asofold** [comment]
Assume fixed - please drop a note if not so.
