### ISSUE TITLE
WTH!!! HELP

### ISSUE THREAD

**Issue by LurkingGamerPro** [NoCheatPlus/Issues#248]
The nocheatplus is way over sensortive and i need to so hackers can ruin the game but intead it is stopping people going through doors, stepping on slabs and stopping them from jumping on beds, if they go and do all that it will notify me saying cheating and I cant have any anti cheat anymore ebcause of the stupid thing! Please sort it out it is getting really annoying.

**Comment by asofold** [comment]
Looks like an outdated version of NCP in use. Have you tried build 1021? http://ci.md-5.net/job/NoCheatPlus/

We don't have an official release for anything around 1.10 at present. Please also add the output of the 'ncp version' command with reports, which helps to see some things very quickly.

**Comment by LurkingGamerPro** [comment]
http://dev.bukkit.org/bukkit-plugins/nocheatplus/
NOW! With Minecraft 1.10 support! (on Jenkins)

that is were i got it from and you say you havnt made a release with 1.10 i suggest not putting 1.10 on description

**Comment by MarkElf** [comment]
Some people are just ignerent - it clearly states on Jenkins.

http://ci.md-5.net/job/NoCheatPlus/lastSuccessfulBuild/artifact/target/NoCheatPlus.jar

**Comment by asofold** [comment]
My statement here hadn't been 100% clear though, release/build/wheere...

that's the drawback with not having "releases" :p ...

**Comment by ScuroK** [comment]
@asofold is NCP abandoned??

**Comment by asofold** [comment]
@ScuroK http://ci.md-5.net/job/NoCheatPlus/
