### ISSUE TITLE
NoSlowDown - move normal walk speed while eating

### ISSUE THREAD

**Issue by MarkElf** [NoCheatPlus/Issues#249]
I don't believe that this needs much explaining, while eating and having the cheat enabled, players are able to move at the normal walk speed while eating food. The log file below is for a spigot 1.9.4 server, default configuration, development build 1021.

/ncp version output: http://prntscr.com/buu6vn
Debug log: http://pastebin.com/T73NaKCz

**Comment by asofold** [comment]
Despite the old ticket being a raw/borked import from dbo, isn't this duplicating: https://github.com/NoCheatPlus/Issues/issues/13

(There is no check in NCP yet.)

**Comment by MarkElf** [comment]
It is, my apologies.
