### ISSUE TITLE
/Homes on a fence/pole [DBO 686]

### ISSUE THREAD

**Issue by MyPictures** [NoCheatPlus/Issues#25]
==What is the problem? What do you expect to see instead?==

If you teleport on a fence using /home,you can't move dueto survivalflyetection and it will kick you, repeating that on relogg.
==Can it be reproduced systematically and if so: How?==

==How easy is it to reproduce? Does it always happen? Does it happen to all players? Does it happen with vanilla clients?==
See above, always happens.

==**Versions of NCP and server: Post the output of the "ncp version" command!**==
git-Bukkit-1.7.2-b2974jnks

3.10.7-Beta-sMD5NET-b651

**Comment by MyPictures** [comment]
**asofold:** "I might be bale to do something - not sure it will allow spider though."

**Comment by asofold** [comment]
How is this at present?

There has been a report for 1.9.4, but i can't manage to teleport onto fences without gliding off, no violations.

**Comment by MyPictures** [comment]
I dont even remember if this was with all /home plugins or just essentials in particular.

**Comment by asofold** [comment]
It used to be plugins optimizing home positions (on top of the idk-nearby block), then perhaps on relog, or right away. Just now it looks like they glitch off the fence, i don't get a stable position on the fence with teleportation.

**Comment by asofold** [comment]
Closing as superseded.
