### ISSUE TITLE
Holding down the right (or left) mouse button on the ground while riding a horse triggers BlockInteract.Direction

### ISSUE THREAD

**Issue by Lysandr0** [NoCheatPlus/Issues#250]
Even Reach and Visible violations at times…
Should be easy to reproduce.
Gif  :)
https://gyazo.com/264ef8a3968ddfe79d6bbdfc91ae78e4

---- Version information ----
#### Server

git-Spigot-6c9b0a1-de5c261 ~MC: 1.8.8~
detected: 1.8.8
#### NoCheatPlus

Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1022
MCAccess: 1.8.4-1.8.8 / Spigot-CB-1.8_R3
Features:
blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
defaults: pvpKnockBackVelocity
packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | CatchAllAdapter
Hooks: AllViolations~NCP~ 1.0 | TestNCPHook 1.0
#### Related Plugins

ProtocolLib v3.6.4

**Comment by asofold** [comment]
very likely fixed with using ProtocolLib and around build 1090.

**Comment by Lysandr0** [comment]
Yeah... Can confirm. Thanks for all your work!
