### ISSUE TITLE
Packet

### ISSUE THREAD

**Issue by TheIntelloBox** [NoCheatPlus/Issues#252]
Hello,

When I go in a world called Survival, my players and me have : http://zupimages.net/up/16/30/ckhi.png
Using Java 8, Spigot 1.8.9 and the latest dev build of No Cheat Plus.
Thanks.

**Comment by asofold** [comment]
No idea, other than dependency plugins like combination of ProtocolLib with ... others, such as NCP ... or is it a protocol-support build (1.8 - 1-10 clients or what not)?

**Comment by TheIntelloBox** [comment]
I'm on 1.8.9 and some players are kicked for sending a lot of packets !

**Comment by asofold** [comment]
Could you post those kick messages here?

**Comment by asofold** [comment]
Assume superseded by protocol/packet/ncp updates.
