### ISSUE TITLE
NCP + RampenDrills

### ISSUE THREAD

**Issue by Dizfunkshunal** [NoCheatPlus/Issues#254]
RampenDrills - https://www.spigotmc.org/resources/rampendrills.23086/

NCP stops players from using this plugin. Says the are breaking to fast. I read NCP document ion and couldn't figure a way to change this other then disabling the check for fast break, which i would rather not do.  any ideas or help with this would be great. thanks

**Comment by asofold** [comment]
Without inspecting the source code there is nothing better to advise than to disabling the check... despite such not being such a good thing in general.

Typically auto-thing plugins fire events in the name of the player, so we need to find out how to distinguish such a drill machine from a player. Some plugins ensure it can be distinguished somehow (meta-data, special events, API), some don't.

If the plugin is not open source, i'd rather have the author check out the API of NCP, as there is a couple of ways to let NCP ignore drills (e.g. add "nocheat.exempt" metadata to the player before firing the events for drilling, and removing the meta-data afterwards).

**Comment by asofold** [comment]
Don't see the source there, i suggest the developer does something about it - i'm still here for reference.
