### ISSUE TITLE
Is real vulnerability?

### ISSUE THREAD

**Issue by MoofMonkey** [NoCheatPlus/Issues#255]
Is real?
https://www.youtube.com/watch?v=7y01EYDUNcc
I'm not sure.

**Comment by asofold** [comment]
Sorry, on first skimming through the video i couldn't find a vulnerability.

It's likely that i've just missed it, or even accidentally watched another video somehow, i don't understand that much of that language. (Looks like special game modes, not sure where / how.)

What is it about?

**Comment by jtvjan** [comment]
It looks like a fake "cracking" program that tells users that it'll give them OP but actually steals their Minecraft login credentials or has surveys to access the program that gives the creator money. Anyway, it's probably fake.

**Comment by MoofMonkey** [comment]
Fake crack program. This is may be stealer. Don't worry, close it. Thx for replies! =3
