### ISSUE TITLE
Players glitching

### ISSUE THREAD

**Issue by Xephrew** [NoCheatPlus/Issues#258]
Hi there,

I have had to uninstall the plugin as players are not able to move on items like stairs and slabs (this happens to all apart from OP).
I have made no changes to the config.
Server version: 1.10.2

Kind regards,
Flynn.

**Comment by Wealh** [comment]
Bump

**Comment by asofold** [comment]
Please always look here:

https://github.com/NoCheatPlus/Docs/wiki/Notable-Builds

http://ci.md-5.net/job/NoCheatPlus/

In order to allow people judge quickly the output that the 'ncp version' command generates would be very helpful with each and every issue report!
