### ISSUE TITLE
Save logs in mysql [DBO 697]

### ISSUE THREAD

**Issue by MyPictures** [NoCheatPlus/Issues#26]
It will be easy to check players through a nice interface.
Not sure how much it will affect the server's performance.

**Comment by MyPictures** [comment]
**asofold:** "The design of how to make it accessible is another question, probably dynamic logging backend registration makes most sense (integrate into logging section). It would not be a new action type. If this would be with NCP, it would probably have to be s or q (log:...:icfq), though those shortcuts don't look nice.

With a completely new design we might try to provide a different way to set up logging. Likely we will try to reduce the action lists to ... nothing if possible. Instead we would try for a generic logging policy, which then demands to take into account frequency + some abstract severity levels both for the check itself (important check or not) and the violation (check with false positives on that level, low severity, no-vanilla-ever-do etc.).

Since it's fancy, i also have to mention the planned feature to state a probability for an action (cancel 50% of the cases) and a context-thing (like "earliest 10 seconds after login", interesting for latency-based problems)."

**Comment by asofold** [comment]
Postponed as is - a plugin could add specific loggers to the LogManager of NCP, and then send what's logged anywhere.

An interesting change could be to allow custom prefix-indicators (defaults are icf), which could be set to relay to a certain registered log stream (log manager) or to a configurable command (strings entry). However that is a more general addition worth its own ticket.

https://github.com/NoCheatPlus/Issues/projects/6
