### ISSUE TITLE
Can't walk on slabs!

### ISSUE THREAD

**Issue by Wealh** [NoCheatPlus/Issues#260]
For some reason, I and other players can't walk on slabs on my server! I have the last version of NCP! I get not notification at all but it just doesn't work! It has something to do with survivalfly, though! Help! People can't walk in the spawn!

**Comment by asofold** [comment]
Please always look here:

https://github.com/NoCheatPlus/Docs/wiki/Notable-Builds

http://ci.md-5.net/job/NoCheatPlus/

In order to allow people judge quickly the output that the 'ncp version' command generates would be very helpful with each and every issue report!

**Comment by asofold** [comment]
https://raw.githubusercontent.com/NoCheatPlus/Issues/master/ISSUE_TEMPLATE

Assume superseded / fixed alreadym. Otherwise 'ncp version' is needed.
