### ISSUE TITLE
NCP + ProtocolLib + Lib's Disguises on 1.8.8 - False kicked for flying

### ISSUE THREAD

**Issue by L4BORG** [NoCheatPlus/Issues#261]
With https://www.spigotmc.org/resources/libs-disguises.81/ for 1.8.8 (8.6.7) on latest 1.8.8 players would get kicked for flying or related right away when they're disguised as block with plugins such as https://www.spigotmc.org/resources/hideandseek.9777/ (latest)

```
>ncp version
[19:37:05 INFO]: ---- Version information ----
[19:37:05 INFO]: #### Server ####
[19:37:05 INFO]: git-TacoSpigot-"65fd35f" ~MC: 1.8.8~
[19:37:05 INFO]:   detected: 1.8.8
[19:37:05 INFO]: #### NoCheatPlus ####
[19:37:05 INFO]: Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1022
[19:37:05 INFO]: MCAccess: 1.8.4-1.8.8 / Spigot-CB-1.8_R3
[19:37:05 INFO]: Features:
[19:37:05 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
[19:37:05 INFO]:   checks: FastConsume | Gutenberg
[19:37:05 INFO]:   defaults: pvpKnockBackVelocity
[19:37:05 INFO]: #### Related Plugins ####
[19:37:05 INFO]: ProtocolLib v4.1.0-SNAPSHOT-b317
```

**Comment by L4BORG** [comment]
Actually moving is fine, while moving and turning around (even if it's just a little bit) would instantly generate crazy survivalfly VL and kick player.

**Comment by L4BORG** [comment]
Kick would only occurred when player is disguised as something... and VL:
```
>ncp info player
[19:53:36 INFO]: NCP: Displaying player's violations...
[19:53:36 INFO]: NCP: [19:52:51] player.survivalfly VL 1893  (n2a946m1879)
[19:53:36 INFO]: NCP: [19:53:30] player.passable VL 9  (n9a1m1)
```

**Comment by asofold** [comment]
Might need a debug log here (https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players).

Is it just survivalfly, no morepackets (excess rather)?

**Comment by RoboMWM** [comment]
And these clients are 1.8.8 clients? I suspect viaversion here at play too.

**Comment by L4BORG** [comment]
Yes. Could be ViaVersion, we're also having issues with lilypads...

**Comment by L4BORG** [comment]
Sorry for late reply and stuff I'm like extremely busy those days, for now we just downgraded NCP and we're using old procollib. We did test with latest ViaVersion tho, but no luck. I'll get back to that ASAP.

**Comment by RoboMWM** [comment]
Yea, if you're using viaversion, you're gonna have a bad time, since I guess clients report their position differently on blocks like lilypads compared to 1.8.8 clients.

**Comment by L4BORG** [comment]
Could be, but isn't that handled by ViaVersion? @MylesIsCool

**Comment by MylesIsCool** [comment]
@L4BORG Lilypads are broke because hitbox changed, i've not seen any other issues with NCP as long as you use latest. Jump height did change by like 0.0125 or something like that but i've had nobody else with these kind of issues.

**Comment by L4BORG** [comment]
I did some more testing, without ViaVersion the result is the same. The only VL we're seeing is survivalfly, no more packets or anything else...

how to replicate, you need latest NCP, latest ProtocolLib, Lib's Disguises (8.7.6 for 1.8.8), latest TacoSpigot/PaperSpigot 1.8.8, once you're online:
1.) do /disguise silverfish (or anything really)
2.) walk around a bit (you will get kicked before you can walk for a few blocks, but ONLY if you turn left/right while walking).

**Comment by RoboMWM** [comment]
> do /disguise silverfish (or anything really)

In other words, not an NCP issue. Libsdisguises should hook into and make an exemption if necessary.

**Comment by L4BORG** [comment]
Are you sure? Because this started happening after updating NCP from 3.14.0-SNAPSHOT-sMD5NET-b989 to 3.15.0-SNAPSHOT-sMD5NET-b1022.

**Comment by RoboMWM** [comment]
Perhaps get some debug data on 989 and 1022?

Though tbh I rather they focus on later versions, especially considering asofold's inactivity.

**Comment by asofold** [comment]
Assume superseded by updates on either/all sides - if issues persist, please describe +- debug log :).
