### ISSUE TITLE
End Portals & survivalfly

### ISSUE THREAD

**Issue by hurrgurl** [NoCheatPlus/Issues#262]
Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1022

**Jumping** to end portal generates survivalfly VL 5000-7000 - results in a kick with newly generated config.

After kick and relogin player is teleported to 0 0 0 instead of the right location, as tho Minecraft doesn't know where to spawn them.

**Slowly walking** into end portal works as intended, no false positives.

**Comment by MarkElf** [comment]
Duplicate of #221 .

**Comment by MyPictures** [comment]
Closed because of duplicate.
