### ISSUE TITLE
Full Slimefun Support?

### ISSUE THREAD

**Issue by Ethon6** [NoCheatPlus/Issues#263]
Slimefun a "Pocket Tekkit". My server Core is Slimefun. Plz create for a full support. (Double Jump boots, not working)

Slimefun page: http://dev.bukkit.org/bukkit-plugins/slimefun/

**Comment by RoboMWM** [comment]
Unless you can give specific instances where Slimefun has issues like I did (e.g. https://github.com/NoCheatPlus/Issues/issues/69 ) (which btw, the original Slimefun developer is no longer active), simply asking for "full slimefun support" gets nobody anywhere.

**Comment by asofold** [comment]
Closing as 'can't fix' - need more information.
