### ISSUE TITLE
Spam Hack in chat

### ISSUE THREAD

**Issue by LoXR** [NoCheatPlus/Issues#267]
So basically, the chat gets spammed by players who are offline with notifications of someone speedmining or fastbreaking etc. Is that caused by nocheatplus or some other plugin I have?
Capture: http://prntscr.com/c5gf4p
NCP Version: http://prnt.sc/c5gggk
Logs: http://pastebin.com/LC8h3QHM

**Comment by asofold** [comment]
Sorry - why did this one slip through !?

1. The configuration seems to be custom (speedmine isn't contained in the original configuration of NCP).
2. Yes, the check likely is for fast breaking of blocks - unless this is a special plugin feature which is incompatible with NCP, it does look like a fastbreak/nuking attempt, i.e. breaking vast amounts of blocks in a very short time. (In theory it could also be malconfigured, but i assume it's not that.)

Closing as superseded, as everyhting got updated a million times, though there may or may not be an actual issue left.
