### ISSUE TITLE
Don't Block but notif ?

### ISSUE THREAD

**Issue by Mihawka** [NoCheatPlus/Issues#268]
How to display notifications of ncp and not block players ?

**Comment by RoboMWM** [comment]
Short answer: Read the wiki. See [Actions](https://github.com/NoCheatPlus/Docs/wiki/General#actions) and [Logging](https://github.com/NoCheatPlus/Docs/wiki/Logging)

Another short answer: Remove the word "cancel" for `actions:` under each check.
