### ISSUE TITLE
PaperSpigot 1.7.10 ProtocolLib hook not working...

### ISSUE THREAD

**Issue by Menfie** [NoCheatPlus/Issues#270]
I'm using latest NCP build with paperspigot 1.7.10 protocolhack. And I have protocollib 1.6.4 as you guys suggested but the thing is when I try my config on spigot 1.8.8 it detects AttackFrequency and other protocollib stuff but on paperspigot 1.7.10 it's not detecting.

**Comment by asofold** [comment]
Closing as superseded .

Please check what the ProtocolLib developer is suggesting for that version - reopen if necessary.
