### ISSUE TITLE
NoCheat Plus current build errors in console.

### ISSUE THREAD

**Issue by keyman1986** [NoCheatPlus/Issues#271]
ERROR Could not pass event FakeBlockDamageEvent to CompatNoCheatPlus v6.6.2-RC-sMD5NET-b83 27.08 18:51:43 [Server] INFO org.bukkit.event.EventException 27.08 18:51:43 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.10.jar:git-Spigot-1e4dd71-4507d99] 27.08 18:51:43 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.jar:git-Spigot-1e4dd71-4507d99] 27.08 18:51:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.jar:git-Spigot-1e4dd71-4507d99] 27.08 18:51:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.jar:git-Spigot-1e4dd71-4507d99] 27.08 18:51:43 [Server] INFO at com.gmail.nossr50.util.EventUtils.simulateBlockBreak(EventUtils.java:101) [mcMMO%20%23145.jar:?] 27.08 18:51:43 [Server] INFO at com.gmail.nossr50.skills.mining.MiningManager.remoteDetonation(MiningManager.java:99) [mcMMO%20%23145.jar:?] 27.08 18:51:43 [Server] INFO at com.gmail.nossr50.listeners.PlayerListener.onPlayerInteractMonitor(PlayerListener.java:594) [mcMMO%20%23145.jar:?] 27.08 18:51:43 [Server] INFO at sun.reflect.GeneratedMethodAccessor223.invoke(Unknown Source) ~[?:?] 27.08 18:51:43 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65] 27.08 18:51:43 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65] 27.08 18:51:43 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot-1.10.jar:git-Spigot-1e4dd71-4507d99] 27.08 18:51:43 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.10.jar:git-Spigot-1e4dd71-4507d99] 27.08 18:51:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.jar:git-Spigot-1e4dd71-4507d99] 27.08 18:51:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.jar:git-Spigot-1e4dd71-4507d99] 27.08 18:51:43 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot-1.10.jar:git-Spigot-1e4dd71-4507d99] 27.08 18:51:43 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198) [spigot-1.10.jar:git-Spigot-1e4dd71-4507d99] 27.08 18:51:43 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:194) [spigot-1.10.jar:git-Spigot-1e4dd71-4507d99] 27.08 18:51:43 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:946) [spigot-1.10.jar:git-Spigot-1e4dd71-4507d99] 27.08 18:51:43 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:27) [spigot-1.10.jar:git-Spigot-1e4dd71-4507d99] 27.08 18:51:43 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot-1.10.jar:git-Spigot-1e4dd71-4507d99] 27.08 18:51:43 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.jar:git-Spigot-1e4dd71-4507d99] 27.08 18:51:43 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_65] 27.08 18:51:43 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_65] 27.08 18:51:43 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.jar:git-Spigot-1e4dd71-4507d99] 27.08 18:51:43 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-1.10.jar:git-Spigot-1e4dd71-4507d99] 27.08 18:51:43 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.jar:git-Spigot-1e4dd71-4507d99] 27.08 18:51:43 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.jar:git-Spigot-1e4dd71-4507d99] 27.08 18:51:43 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.jar:git-Spigot-1e4dd71-4507d99] 27.08 18:51:43 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_65] 27.08 18:51:43 [Server] INFO Caused by: java.lang.NoClassDefFoundError: fr/neatmonster/nocheatplus/utilities/BlockProperties 27.08 18:51:43 [Server] INFO at me.asofold.bpl.cncp.hooks.mcmmo.HookFacadeImpl.getToolProps(HookFacadeImpl.java:137) ~[?:?] 27.08 18:51:43 [Server] INFO at me.asofold.bpl.cncp.hooks.mcmmo.HookFacadeImpl.blockDamageLowest(HookFacadeImpl.java:164) ~[?:?] 27.08 18:51:43 [Server] INFO at me.asofold.bpl.cncp.hooks.mcmmo.HookmcMMO.onBlockDamageLowest(HookmcMMO.java:128) ~[?:?] 27.08 18:51:43 [Server] INFO at sun.reflect.GeneratedMethodAccessor557.invoke(Unknown Source) ~[?:?] 27.08 18:51:43 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65] 27.08 18:51:43 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65] 27.08 18:51:43 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.jar:git-Spigot-1e4dd71-4507d99] 27.08 18:51:43 [Server] INFO ... 28 more 27.08 18:51:43 [Server] ERROR Could not pass event FakeBlockDamageEvent to CompatNoCheatPlus v6.6.2-RC-sMD5NET-b83 27.08 18:51:43 [Server] INFO org.bukkit.event.EventException 27.08 18:51:43 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.10.jar:git-Spigot-1e4dd71-4507d99] 27.08 18:51:43 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.jar:git-Spigot-1e4dd71-4507d99] 27.08 18:51:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.jar:git-Spigot-1e4dd71-4507d99] 27.08 18:51:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.jar:git-Spigot-1e4dd71-4507d99] 27.08 18:51:43 [Server] INFO at com.gmail.nossr50.util.EventUtils.simulateBlockBreak(EventUtils.java:101) [mcMMO%20%23145.jar:?] 27.08 18:51:43 [Server] INFO at com.gmail.nossr50.skills.mining.MiningManager.remoteDetonation(MiningManager.java:99) [mcMMO%20%23145.jar:?] 27.08 18:51:43 [Server] INFO at com.gmail.nossr50.listeners.PlayerListener.onPlayerInteractMonitor(PlayerListener.java:594) [mcMMO%20%23145.jar:?] 27.08 18:51:43 [Server] INFO at sun.reflect.GeneratedMethodAccessor223.invoke(Unknown Source) ~[?:?] 27.08 18:51:43 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65] 27.08 18:51:43 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65] 27.08 18:51:43 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot-1.10.jar:git-Spigot-1e4dd71-4507d99] 27.08 18:51:43 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.10.jar:git-Spigot-1e4dd71-4507d99] 27.08 18:51:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.jar:git-Spigot-1e4dd71-4507d99] 27.08 18:51:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.jar:git-Spigot-1e4dd71-4507d99] 27.08 18:51:43 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot-1.10.jar:git-Spigot-1e4dd71-4507d99] 27.08 18:51:43 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198) [spigot-1.10.jar:git-Spigot-1e4dd71-4507d99]

**Comment by MarkElf** [comment]
You ncp.jar is further up to date then your cncp.jar file. Update to the following build, this is a direct download:
http://ci.md-5.net/job/CompatNoCheatPlus/lastSuccessfulBuild/artifact/CompatNoCheatPlus/target/cncp.jar

**Comment by MyPictures** [comment]
Yeah, updating cncnp and NC+ should solve this problem. If the problem persists then feel free to reopen or ask for help.
