### ISSUE TITLE
FP: Holding a food item while eating cake triggers instanteat

### ISSUE THREAD

**Issue by RoboMWM** [NoCheatPlus/Issues#275]
Some possible fixes include checking if player is staring at a cake block and/or if the food item is still in the player's hand. Although then again I could be confusing this check's purpose with fastconsume...

**Comment by asofold** [comment]
@MyPictures Cake rules over other food items?

**Comment by RoboMWM** [comment]
Btw, is there a difference between the instanteat and fastconsume check? Or is one of them old/deprecated?

**Comment by asofold** [comment]
The fastconsume check replaces instanteat (since MC 1.5.2 or so).
There also should be a log message about fast consume taking effect.

**Comment by RoboMWM** [comment]
hmm, well, I had to manually disable the instanteat check.

**Comment by asofold** [comment]
Are you sure?

Does it fire instanteat violations?
The log should show: Inventory checks: FastConsume is available, disabled InstantEat.

NCP would disable instanteat then (but not alter the configuration file).

**Comment by RoboMWM** [comment]
I believe it did state that, but it was still active. I'll take another look at it when I can.

**Comment by asofold** [comment]
Looks like this might have happened with reloading the configuration.

Build 1037 attempts to fix this.

**Comment by RoboMWM** [comment]
Haven't been able to test if this is the case, but I already went ahead and just disabled instanteat in the config myself.
