### ISSUE TITLE
FIGHT_DIRECTION checks have infinite values on latest Dev Build

### ISSUE THREAD

**Issue by Maxetto** [NoCheatPlus/Issues#276]
I recently decided to update NCP to latest version (3.15.0-SNAPSHOT-sMD5NET-b1022) because I got hit by some packet spam hacks (I'm on Spigot 1.8.8).

Everything works fine but the FIGHT_DIRECTION check, that prints absurd values whenever a player fails it.

```
NCP: [19:11:38] fight.direction VL 9223372036854775807  (n2a9223372036854775807m9223372036854775807)
```

```
NCP: [19:29:51] fight.direction VL 9223372036854775807  (n1a9223372036854775807m9223372036854775807)
```

This might be caused by this commit: https://github.com/NoCheatPlus/NoCheatPlus/commit/2c614cce915c547890ce5133419ecbd23de0a1e9

Is this cheating for sure? Why there's people that have normal values too? Is this part of something unfinished?
Thank you.

**Comment by asofold** [comment]
The commit made it more lenient :).

This sounds horrible, will need to check the code further...

**Comment by asofold** [comment]
Should've had a look earlier on ... 

Assume fixed in build 1039, note other recent changes possibly containing other bugs.

**Comment by Maxetto** [comment]
Confirmed Fixed.

Thank you for your hard work.
