### ISSUE TITLE
NCP lagback on Snow, carpet, soiled land, lilypads, slabs, etc...

### ISSUE THREAD

**Issue by Katon151998** [NoCheatPlus/Issues#278]
Hello,
I have a major problem with NCP, It keeps lagging players back when they sprint on any block that isn't considered a "full" block (EX: Cobblestone, dirt, etc...) And it's really annoying. What can i do to fix it?

Thank you,
Katon15

**Comment by MarkElf** [comment]
Did you really have to make a duplicate?
#274

**Comment by RoboMWM** [comment]
You included hardly any information. We need `/version` and `/ncp version` at the very least. A plugin list/server log would also be handy.

But, my guess is that you aren't running the latest version of NCP.

**Comment by asofold** [comment]
http://ci.md-5.net/job/NoCheatPlus/

Assume superseeded somehow.
