### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by sufletzel** [NoCheatPlus/Issues#280]
Can you make this compatible whit this plugin https://www.spigotmc.org/resources/zenchantments.12948/reviews

**Comment by Janmm14** [comment]
Do it the other way around and ask zenchantments to hook into nocheatplus.

**Comment by asofold** [comment]
Currently i prefer if they did something, discussion on how to would always be welcome.

At some point CompatNoCheatPlus will be fully discontinued, in favor of adding a few generic compatibility mechanisms into NCP directly, but currently i can't focus on that.

**Comment by asofold** [comment]
Closing as 'won't fix' - but the developer may ask me any time if there are technical issues.
