### ISSUE TITLE
Making a pile of boats and running over them results in fly kick.

### ISSUE THREAD

**Issue by MithrandirCraft** [NoCheatPlus/Issues#282]
Just as the title says. When someone places a pile of boats on water and then runs over them, it kicks the player for flying.

https://cloud.githubusercontent.com/assets/20175690/19017054/c3c612cc-8803-11e6-861a-18128c74905e.png

NCP: 3.15.0
Spigot: 1.10.2

PS: When will combat hacks be blocked? q_q

**Comment by asofold** [comment]
I'd love someone to produce a debug log, as even the setup will kill some time, which i might need to catch up in general for now.

**Comment by MithrandirCraft** [comment]
Will try to provide what you need asap.

**Comment by MithrandirCraft** [comment]
Oh, it seems I get the Bukkit alert "Flying is not allowed on this server"
So it musn't be your falt. Reporting this to Spigot.

**Comment by asofold** [comment]
Cool, thank you :).

We do usually assume that turning off the vanilla fly check is better, though. Is there anything it does better than the latest development builds of NCP?
