### ISSUE TITLE
up to about 220% Speed bypasses - client code included, no lagbacks by anticheat

### ISSUE THREAD

**Issue by Janmm14** [NoCheatPlus/Issues#283]
**_What is the problem? What do you expect to see instead?_**
Some nocheatplus speed modes are working allowing significantly faster movements. They just trigger surivalfly once.
I expect those creepy movements to be blocked.

If you have much time: I suggest implementing another speed check which focuses xz movement and enforces the limit of sprintjumping (as a catch-all if the other speed checks don't catch it).

**_If it can be reproduced please try to explain as detailed as possible (video, text or images are always welcome):_**
_a) Does it affect all players on your server?_
 -> n.a.
_b) Is it easy to reproduce?/Does it always happen?_
 -> Worked always in my tests.
_c) Does it also happen if you use a unmoded vanilla client?_
 -> n.a.

**_Have you made any (noteworthy) changes to the default configuration of NCP?_**
Nope.

**_Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?_**
Nope. (Turned off AAC / with AAC it doesn't work)

**_What is your NoCheatPlus version? (/ncp version)_**
/ncp version: https://sc-cdn.scaleengine.net/i/40ef3c195bce64f27c0f9daa489966c11.png

**_What is your server version? (/ncp version or /version)_**
/version: https://sc-cdn.scaleengine.net/i/5c98883192adb0c5d5745dbdb1e727951.png

**_Please provide any additional information below! Use GitHub, http://pastebin.com/ or similar for huge logs!_**

_NoCheatPlus Minihop sourcecode:_ (nearly twice the speed) http://pastebin.com/ndawW2zV
(minihop generates one or two violations when "initializing", but then produces nothing)
_NoCheatPlus BHop sourcecode:_ (around 150% speed) http://pastebin.com/crYbthha
_NoCheatPlus YPort 1 sourcecode:_ (more than twice the speed) http://pastebin.com/03gRx11E
_NoCheatPlus YPort 2 sourcecode:_ (more than twice the speed) http://pastebin.com/w0aHdXe3

**Notes to the client:** I suggest running the client **only in a vm** due to security reasons.
_Client to test:_ https://mega.nz/#!ioU00CpS !CFe81G6qmPe4i8hJDHe81NbKYn-BgOczCRObrXdQDzM (obfuscated by cracker)
**Virustotal:** https://virustotal.com/de/file/06bf4d7df1d5998b8e7fbab9c073b14096f5c051c0320f97d9a60f352bd89f8f/analysis/1481131923/
**Notes to the client:** I suggest running the client **only in a vm** due to security reasons.

_Full client sourcecode:_ https://mega.nz/#!r8shxbST !skIJrgBj94l0UbpWyddI9Ifexq8stWlyT_usLquLAhE
Notes to the source: Minecraft MCP mappings were used.

**Comment by asofold** [comment]
Probably time to redo it then.

The implementation mainly has a lot of exceptions for special cases, mostly from before having added a workaround counter framework and past move tracking. Thus the side condition checks are too general and probably even faulty by now.

**Comment by Janmm14** [comment]
What is a workaround counter framework?

**Comment by Janmm14** [comment]
@asofold Hello?

**Comment by asofold** [comment]
Build 1024 contains an experimental limiting thing, likely not fit for production.

**Comment by Janmm14** [comment]
@asofold
I heard one found a new speed which works with curious changes to the y coordinate (yport speed) while current ncp speeds seem fixed.

**Comment by asofold** [comment]
Could anyone confirm or deny latest builds of NCP (~1028) cutting down some of former speeding hacks (dolphin, bunny hop)?

**Comment by Cryptkeeper** [comment]
We've seen a 21% decrease in bunny hop/speed related cheater reports after deploying #1030. It seems to be effective against the extreme end of the bunny hop spectrum. 

So it's not quite there, but it's on the right track.

**Comment by hugo4715** [comment]
# WARNING
The link to the first client is really suspicious, if you did not run it in a vm, install bitdefender and scan your system.
virustotal scan: https://virustotal.com/fr/file/06bf4d7df1d5998b8e7fbab9c073b14096f5c051c0320f97d9a60f352bd89f8f/analysis/1481131923/

@Janmm14 Maybe remove the link?

**Comment by asofold** [comment]
@hugo4715 In general external links to potentially arbitrary content (unlike pastebin or youtube or vimeo, etc...) have to be handled like potentially harmful. Testing cheat clients also is problematic, a VM is about the best you can do at reasonable cost, next to starting locked down systems from CD (still the hardware is accessible directly, which may or may not be a problem). Also it's problematic to ever input user credentials (...), though you can set extra secret question content (e.g. random generated) with your Mojang account, so they can't easily change your passwords - then again, that better be an account used for testing exclusively (no admin rights / achievments/progress etc. on important servers)- naturally it's better to play offline mode for testing whenever possible.

**Comment by Janmm14** [comment]
@asofold @hugo4715 I already wrote that below already, but okay.

**Comment by asofold** [comment]
@Janmm14 Oh hehe, slipped past the notice.

In general external links could be source code or images or just raw socket attacks :p - in case of sites that may serve arbitrary content, the shortened links are a bit problematic, because one has no clue what's behind. Sometimes old content gets removed (also with pastebin/timings), and the shortened links may well get reused for something completely different (never know).

I wouldn't want to smear warning notices all over issue posts :p. The parts after the ! are some kind of hashes?

**Comment by Janmm14** [comment]
@asofold Thats the key for the mega download.

**Comment by asofold** [comment]
@Janmm14 Ok i see - that's good enough on that account. One even has to leave out the '!' :p, so accidental click through isn't so easy.

One point to consider (for me rather) is, that we tell people to post reports on GitHub, and those are most often server owners, some may be inexperienced server owners, and so on. So how do we handle potentially harmful external stuff is a little bit of a question. On the other hand i haven't seen people just so run any client on our account, up to now.

**Comment by Janmm14** [comment]
@asofold ok

**Comment by asofold** [comment]
@Janmm14 I see :)  - that's next best to uploading to GitHub. It was mean more like a general statement.

To get back on topic, i'd love to see timings (ncp stopwatch distance 100 ~ + run 100 blocks plain or so) with the still-fastest cheats on latest dev builds. If anyone is cheat-client-testing-savvy ...

**Comment by Janmm14** [comment]
https://www.youtube.com/watch?v=zCs2NZsLahg
https://www.youtube.com/watch?v=-FwaqLr2L28

**Comment by Janmm14** [comment]
@asofold 
Latest NoCheatPlus, default config without kicks:
longjump (+ yport speed working for short time)
https://www.youtube.com/watch?v=puJZlaPcNb0

(I hope that it got set up correctly)

**Comment by asofold** [comment]
Speeding videos are best with version information. Unless there is special setups of the map that might hint us at something, it'll not lead us anywhere, other than 'perhpaps review the code next century, when there is a little time'.

Long jump - this too is one of the things i have been waiting for. The rough envelopes we set, still allow slower falling, so it's plausible. Again it'll be necessary to quantify what's happening, in terms of how far they can jump with what other effects on (speed? jump?), and compare to a vanilla client with the same side conditions on - also ensuring what combination of server+ncp is in use (ncp version is sort of mandatory, though i think some type of long-er jumping is plausible).

**Comment by Janmm14** [comment]
@asofold build 1043 on spigot 1.8.8

**Comment by asofold** [comment]
@Janmm14 For the jump video yes, what's with the speeding videos... it's a general point, we just can't say much if the version information is missing.

**Comment by Janmm14** [comment]
@asofold I know for the speed video we don't know and will never know. Maybe ignore it for now.

**Comment by asofold** [comment]
Sure, then we're at what i was assuming. It can be a little bit confusing on multi-context issues, e.g. relating to 'it', leaving open which 'it'.

So i need more input on speeding, e.g. timings of cheat clients vs latest NCP with 'ncp version' and comparison to vanilla under the same side conditions (effects, items with attributes, map etc.). Probably someone will be willing to provide such, so we have an idea what the relevance is, this can be done without disclosing details about how exactly the client is doing it (_/ncp stopwatch distance 100_  or 50, best be plain ground).

And we might detach the long jump thing to another issue some time soon.

**Comment by Janmm14** [comment]
@asofold
yport speeds can still be used on ice, also the blockage of yport speeds on normal ground seems to kick in slowly only.
New issue for longjumps and its smaller variants used for current ncp speeds: #365
(funny number btw)

**Comment by asofold** [comment]
I will close this as 'superseded', because a couple of things happened between. Feel free to object / add new data or open a new ticket with new data (stopwatch!) :). Otherwise some pointers:

*  Latest speeding tickets indicate roughly 15% gain, which is cutting down things slightly from what it used to be (long before we had something like 30%). More may be possible (either side).
* Not sure yport speed -> this means sprint+jump speed while staying on ground? The latter i would rate to be 'not so problematic', in case they can technically sprint (food level). The 15% on bunnyhoppig would be the much larger issue, bu perhaps i am missing something.
* Note that we assume the player always to be sprinting, when technically possible, because the server used to forget the sprinting state on occasion (hitting entities for instance). This could be optimized if we cover all conditions for losing sprint and when to be sure that they're certainly not sprinting anymore. Not sure food level change is an issue if the state is not set on server side.
