### ISSUE TITLE
Piston + Slime block, players are not launching.

### ISSUE THREAD

**Issue by DefOnslaught** [NoCheatPlus/Issues#286]
I don't know if there is a solution to this. But, if the player is on a slime block with a piston pushing them up, they don't get launched into the air.

I can get it to work if I disable SurvivalFly. 

 ---- Version information ----
1:39:11 PM [INFO] #### Server ####
1:39:11 PM [INFO] git-Spigot-047f737-744e1a1 ~MC: 1.10.2~
1:39:11 PM [INFO]   detected: 1.10.2
1:39:11 PM [INFO] #### NoCheatPlus ####
1:39:11 PM [INFO] Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1022
1:39:11 PM [INFO] MCAccess: 1.10 / Spigot-CB-1.10_R1
1:39:11 PM [INFO] Features:
1:39:12 PM [INFO]   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10
1:39:12 PM [INFO]   checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
1:39:12 PM [INFO]   defaults: pvpKnockBackVelocity
1:39:12 PM [INFO]   packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter
1:39:12 PM [INFO] Hooks: AllViolations~NCP~ 1.0
1:39:12 PM [INFO] #### Related Plugins ####
1:39:12 PM [INFO] ProtocolLib v4.1.0

**Comment by asofold** [comment]
Duplicates: https://github.com/NoCheatPlus/Issues/issues/5

piston+slime is not supported yet. In fact even pistons are not really support.

Slight shame, but quite itchy/edgy to do - hot topic / high priority at present.
