### ISSUE TITLE
Prevent abuse of survival fly flags

### ISSUE THREAD

**Issue by v0idst4r** [NoCheatPlus/Issues#288]
Prevent abuse of survival fly flags where people can use it in games such as skywars.

**Comment by Janmm14** [comment]
I'd probably say: Not enough information.

**Comment by v0idst4r** [comment]
I don't really know what else there is to say?

**Comment by v0idst4r** [comment]
You'll be falling and someone turns on a patched fly, they'll instantly teleport back to where they were before they started falling

**Comment by Janmm14** [comment]
I thought actually that this was already fixed for about a year? I've sawn this once in the aac changelog.

**Comment by v0idst4r** [comment]
Aac?

**Comment by v0idst4r** [comment]
Yes it's fixed in aac but not ncp

**Comment by Janmm14** [comment]
Oh I thought I was in a different issue tracker

**Comment by asofold** [comment]
Well it's a matter of taste, really. NCP has not been built for skywars and you need a different behavior there, acknowledged. What NCP does prevents other types of abuse that are not so relevant for skywars, so i wouldn't call it a fix if AAC sets you back to ground underneath, or keeps you flying in-air.

In theory you could reach places that a vanilla client can't reach if you don't do what NCP does (short version) - admittedly that's for most cases not so relevant, as in practice those types of setups are very rare.

This ticket duplicates already existing tickets, thus closing as a duplicate, please add your vote to the other ticket(s) and keep following that/those from now on :).

Continue here: https://github.com/NoCheatPlus/Issues/issues/8
