### ISSUE TITLE
Not compatible with latest spigot build

### ISSUE THREAD

**Issue by Kakifrucht** [NoCheatPlus/Issues#289]
After updating from git-Spigot-047f737-744e1a1 to git-Spigot-850da7e-8e5e90d a player can no longer jump. SurvivalFly checks seem to pull back all the time, causing additional issues with the servers own "moved wrongly" checks. It would be nice if you could fix this soon, as that new build did include a patch to the getTo() issue with teleport event.

Nocheat build b1022

**Comment by MidnightSugar** [comment]
I'm having the same problem!

**Comment by RoboMWM** [comment]
Oh, glad to finally discover I'm not the only one. Here's the commit that's causing issues: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/8e5e90d5eba3253fc7d77943b64a71d50ff1422c

**Comment by PabloMA98** [comment]
Same problem.

**Comment by Black-Hole** [comment]
Should be fixed in Paper with https://github.com/PaperMC/Paper/commit/557c26bec44d8eb2ae3fe8b2a19dc1e6366e5afa

**Comment by Kakifrucht** [comment]
Unsure if longer relevant, since Spigot reverted the commit aswell.

**Comment by RoboMWM** [comment]
Likely not. Probably can close now

**Comment by Kakifrucht** [comment]
Issue no longer reproducible.

**Comment by ScuroK** [comment]
Is NCP discontinued? i found no updates since more than 3 months. back in the days it updated quite often on jenkins

**Comment by Kakifrucht** [comment]
Do you expect updates everyday? @asofold worked very hard before to update to 1.9/1.10, the project is afaik not officially discontinued.

**Comment by ScuroK** [comment]
Dont take me wrong. im happy if it doesnt update daily! :D it just seems a bit unusuual for me so i worried about it. so many plugins died in the recent year :/

**Comment by asofold** [comment]
A just question, though :).
