### ISSUE TITLE
Unable to Open/Close Doors From Back Side, Trap Doors from bottom side [DBO 729]

### ISSUE THREAD

**Issue by MyPictures** [NoCheatPlus/Issues#29]
What is the problem? What do you expect to see instead?
Players are unable to open/close doors from the "back" side (the side opposite of the block face where the door is located). NCP blocks the action claiming the block is "out of sight". The issue also affects trapdoors when the player is under them/on the far face.

The issue only started appearing when we updated to 1.7.x. The issue did not exist in 1.6 (or at least was not reported to my admin team by my players)

Can it be reproduced systematically and if so: How?

Place Door (framed/in a wall)
Walk to other side
Try to open/close door... repeat multiple times and the errors will start streaming!

Dig a hole
Place a trapdoor at top of said hole, open, and climb inside
Try to open/close trap door... repeat multiple times and NCP errors will start to fly!
How easy is it to reproduce? Does it always happen? Does it happen to all players? Does it happen with vanilla clients?
Very easy to reproduce, happens very consistently (99/100 times). Happens to all players (except those exempted from NCP using /ncp exempt). Issue occurs with both modded and vanilla clients.

*Versions of NCP and server: Post the output of the "ncp version" command!

[19:06:39 INFO]: ---- Version information ----
[19:06:39 INFO]: #### Server ####
[19:06:39 INFO]: git-Spigot-1361 (MC: 1.7.5)
[19:06:39 INFO]: #### NoCheatPlus ####
[19:06:39 INFO]: Plugin: 3.10.7-BETA-sMD5NET-b651
[19:06:39 INFO]: MCAccess: 1.4.6|1.4.7|1.5.x|1.6.1|1.6.2|? / Bukkit-API
Details about the configuration file of NCP.
(Examples: What version of NCP was the config generated with? Did you change anything - if so: add a quick description.)

Issue persists with default configuration file, generated with version listed above.

Do you run any other special plugin next to NC+ (adding skills, machines, adding/changing blocks)?
(Examples: SpoutPlugin, mcMMO, Heroes, MachinaCraft and others.)
I'll just leave this here and let you decide if any of these are relevant...

Plugins (42): TuxTwoLib, WorldEdit, Simple_Prefix, VoxelSniper, Simple-AutoSave, Vault, PermissionsEx, PlotMe, Multiverse-Core, WorldGuard, dynmap, FakeMessager, HeroicDeathPlus, AutoMessage, PerformanceMonitor, CoreProtect, ServerLaws, MasterPromote, CommandHelper, NoSpawnEggs2, McftChat, CompatNoCheatPlus, TimeLock, BanManager, Lockette, Modifyworld, ProtocolLib, RestartAnnounce, Essentials, NoCheatPlus, EssentialsSpawn, Multiverse-Portals, Multiverse-Inventories, TagAPI, Multiverse-SignPortals, EssentialsGeoIP, VanishNoPacket, Multiverse-NetherPortals, PlayerHeads, Duties, CraftBook, EssentialsChat

Please provide any additional information below!
(Examples: Logs, screenshots, plugin list, player amount, NCP configuration files ... use http://dev.bukkit.org/paste/ or http://pastebin.com/ and add the link here if linked resources are longer than a few lines.)
![jbajp5b](https://cloud.githubusercontent.com/assets/1159235/11612976/8bd455ac-9c10-11e5-9aa4-7219769c1688.gif)

**Comment by MyPictures** [comment]
**ZoomerX:** "Just received a report that users are also having trouble breaking torches. Same error claiming user is interacting with a "block out of sight."

To re-create issue:

Place torch, place block next to torch, stand on said block, try to break torch multiple times, watch errors fly.

I've got staff looking to see if any other blocks are affected, and will get back to you if we find any more."

**Comment by MyPictures** [comment]
**asofold:** "Nice animated picture :).

Same issue as Ticket 677 - this is due to the BukkitAPI only mode being in place, so NCP can't look up the block shapes.

We should fix this at some point of time, however for new Minecraft versions NCP usually needs to update as well to have native access to block shapes. Development build 676 supports Minecraft 1.7.5 and i assume we will just push a release this weekend (at least a beta, so for those always check the BukkitDev project page, not just the "latest download" on curse or so).

Maybe i will still try to provide hot fixes to the BukkitAPI-only mode on basis of block-flags. On the long term we will want to implement the block shape stuff to make it fully configurable, such that we don't depend on hooking into the server-mod itself anymore, also to be able to support modded blocks better, as the shapes returned from the server too often don't exactly match how the player can move on/through.

If Bukit allows it or provides support for it, we could some day also make configuration hot fixes available at some json web-service, so block shapes can update automatically with new Minecraft versions.

Edit: i am getting dizzy from looking at that picture from the side - need more coffee."

**Comment by MyPictures** [comment]
**ZoomerX:** "asofold: Updated to build 676 from Jenkins. The issue seems to be 99% fixed in this build. Still get the errors occasionally if someone spam-clicks a door/trapdoor, but otherwise it appears to be fixed. Granted, I've not had time to do real thorough testing, but using the same procedures I used to recreate the issue prior to update, seems fine."

**Comment by MyPictures** [comment]
**asofold:** "ZoomerX:

Spam clicking can mean that at the point of time of arrival of a click onto a door that was open client side, the door might be closed on server side already - so with latency false positives are possible, and have to be accepted for the moment, if you want to have that kind of protection. All provided it does not happen at the first click on a previously static door.

Tracking all the doors changing is appealing for making them rock solid safe like stone walls, but it's pretty complicated and won't happen too soon, if people want to be more lenient on latency while still having protection."

**Comment by MyPictures** [comment]
**MyPictures:** "Yes this only seems to happen if NC+ is forced to only use the bukkitAPI (no correct NMS access available or set in config file). Trapdoors and other stuff is also affect and I think we should make 1 ticket that collects all bukkitAPI only mode limitations/bugs."

**Comment by MyPictures** [comment]
**asofold:** "Do need retest - ensure to test both with CB-MCAccess and with bukkitapionly set to true."

**Comment by asofold** [comment]
Reproduced on bukkitapionly mode. Assume it's that.

**Comment by asofold** [comment]
Assume superseded by updating the CompatCBReflect module for most.

The issue with CompatBukkit would stay though, but it's currently too far out of range to implement per-block classes with sensible default shapes. Not that difficult, but a lot of blocks/changes, so it's not going to happen too soon, unless people team up to build a new (mod independent) core, e.g. with attempting to support sponge as well.
