### ISSUE TITLE
Many false positives.

### ISSUE THREAD

**Issue by UltimaA380** [NoCheatPlus/Issues#294]
My players are getting many SurvivalFly, FastBreak, and Passable false positives, to combat this I add the permission to them as I know they aren't using a cheating client. I have MCMMO but I also have CompatNoCheatPlus

**Comment by asofold** [comment]
For cncp and latest NCP please check out: http://ci.md-5.net/job/CompatNoCheatPlus/
Not sure which version you have right now.

For passable with 2-high ceiling, NCP build 1023 contains a fix: http://ci.md-5.net/job/NoCheatPlus/ (be careful with builds marked as [BLEEDING]: http://ci.md-5.net/job/NoCheatPlus/changes).

Concerning SurvivalFly, is your Spigot version at 'latest' right now?

**Comment by UltimaA380** [comment]
Yes, I have the latest version of spigot.

**Comment by asofold** [comment]
* Have you tried NCP build 1023? 
* Do you run multi-protocol support plugins like ViaVersion?

**Comment by asofold** [comment]
Closing as superseded. Some related fixes/improvements are still pending, though.
