### ISSUE TITLE
NCP Not triggering with Spigot but working just fine on CraftBukkit (SurvivalFly, and most moving checks)

### ISSUE THREAD

**Issue by blok601** [NoCheatPlus/Issues#295]
Hello,

Recently I have been trying to figure out why my ncp config isn't stopping fly anymore. I tested the config on my test server on localhost (my computer hosted server) and on my production server. The only difference between the two servers is that my test server (which always gets triggered) is running CraftBukkit. However, it doesn't work on Spigot. The spigot and Bukkit servers are running the exact same settings and everything.

Do you know what could be causing this? 

Thanks!
-blok601

**Comment by asofold** [comment]
The survuvalfly actions could be of relevance, have you set them to not always cancel?

Otherwise i don't have a clue yet, other than 'differences between CB and Spigot'...

**Comment by blok601** [comment]
Here are my survivalfly actions and ncp version.

https://gyazo.com/70abb29da7c2004d85f3e479ead59f68 -> NCP Version

 actions: log:flyshort:3:10:if cancel vl>100 log:flyshort:0:10:if cancel vl>400 log:flylong:0:5:cif cancel vl>1500 log:flylong:0:5:cif cancel cmd:kickfly

**Comment by asofold** [comment]
Have you considered running one of the latest builds of NCP like 1023 (http://ci.md-5.net/job/NoCheatPlus/)?

Build 925 won't receive backport fixes or the like, so any type of fix would be for the latest line of development, which currently is still intended to support MC 1.8.8.

**Comment by blok601** [comment]
Oh I wasn't aware of that. I will try out the new version.

**Comment by blok601** [comment]
Worked perfectly, thanks.
