### ISSUE TITLE
Swimming now flags on version #1025

### ISSUE THREAD

**Issue by DoubleParallax** [NoCheatPlus/Issues#296]
You can no longer swim. Jesus allows moving with less flags than regular swimming.

**Comment by Michelele** [comment]
Para <3 :)

**Comment by asofold** [comment]
* Please provide more version information as given with 'ncp version', it really helps :).
* Is multi-client-protocol plugins in use?
* How can this be reproduced in a consistent way? I can't let it trigger myself, are you just swim-jumping forward? Can trusted players reproduce it?

**Comment by asofold** [comment]
Build 1026 will contain an adaption of the limting parameter for 1.8.8 clients.

**Comment by DoubleParallax** [comment]
Server: git-Spigot-e4d4710-e1ebe52 ~MC: 1.8.8~
NCP: 3.15.0-SNAPSHOT-sMD5NET-b1025 build #1025
Not entirely sure about the multi-client-protocol plugins

**Comment by asofold** [comment]
So, do the latest builds resolve this issue?

**Comment by DoubleParallax** [comment]
Yes
