### ISSUE TITLE
fals positive on piston with slimeblock. flags MOVING_SURVIVALFLY

### ISSUE THREAD

**Issue by PatrickBang504** [NoCheatPlus/Issues#305]
if a player stands on a slimeblock with a piston beneath, and the player is pressing a button its flagging survival fly

little gif animation to repruduce it:
https://i.gyazo.com/0fa9ce964de9356ed0b3083af3e76a7f.gif

//EDIT:

NCP Version: Build #1030 (Nov 6, 2016 2:07:07 PM)

**Comment by asofold** [comment]
Duplicates: https://github.com/NoCheatPlus/Issues/issues/5
