### ISSUE TITLE
False Claims

### ISSUE THREAD

**Issue by Meglaoch4** [NoCheatPlus/Issues#308]
Hi I USE to be a mod MGN minecraft server, but one day I got kicked from the group on skype I message the admin fright away why did I get kicked and he said that he has noticed me using hacks and I haven't used a hacked client in like 2 years, so he sends me a pictures (on screen) I see my name saying fly in survival now my admin tells me that it was in eggs wars that's in the mini game server not sure if that makes a difference, the first thing I think of is that someone is setting me up and that this is false. Now I love this server I get in a call with the admins and mods all the time so I don't know who would be stupid enough to hack with admins in your call. I also knew that they receive the notification if someone hacks so why would i do it. I didn't hack, but since nocheatplus says I did then I did straight from the admins text. So I probably can't get mod back I did breakdown over it and have a meltdown but this is straight false I will show you my logs, so please fix it.
![82fa90dc51c86fa59d891d72131593180ec87fd9d93f0608e2 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/23515234/20375687/b05ab188-ac4e-11e6-8a59-e8447bb77460.jpg)

**Comment by asofold** [comment]
A) Don't worry, modern nuclear power plants can take a couple of meltdowns before anything serious starts to happen (e.g. Fukushima)...

B) For the case of (HOVER) violations it'll be crucial to know a little bit more.
* You got demoted for this one sf/hover violation (ncp info)? Mind that hover adds a fixed violation amount always, and to trigger it, you'll roughly stay a litlte more than 4 seconds in the air without any moving. False positives could happen with block shape issues (see version question below).
* What does/did the map look like at the position shown in the violation message picture?
* Server and NCP versions might matter for judging false positives as well, but it is not likely they'll publish for every ban-appeal. If they run multi protocol support plugins, things can look different too, as some block shapes might need manual configuration entries with (certain) different client versions connecting, as sometimes between Minecraft versions some block shapes differ in height.

**Comment by Meglaoch4** [comment]
Omg you just reminded me of something, now look I play minecraft on a crappy computer I only can have my view distance at 4 and sometimes I have to move it down to 2, so when we were playing egg wars the admin was coming after me and my game hasn't loaded the full world so I was trying to cross the bridge and it was just black on the other side because the world hasn't loaded and i fell down to the void i just kept falling and not taking damage about 40 seconds later then I started to take damage and i died. I Think this is the reason why it says I was trying to fly because I was just falling into the void. I am going to try to tell the admin and owner and hopefully I get back on the server. If I can't then I'm going to try to make it happen again but record it and see if they get a notification if I was flying but it was me just falling.

**Comment by asofold** [comment]
Shortly after join this could happen with weaker clients, especially on cross world teleportation / setup specialties.

Note that hover means that no distance is taken, so it's important to check where / how it happened, especially with punishments.

**Comment by asofold** [comment]
Closing as superseded (by time or yet unknown events).
