### ISSUE TITLE
Your profiling data in here (all welcome, still prefer: BlockCache methods, moving checks).

### ISSUE THREAD

**Issue by asofold** [NoCheatPlus/Issues#310]
Rather for advanced server owners/admins ~ I'd love to see some profiling data for _populated_ servers if possible. Specifically i am interested in:
* BlockCache methods with build 1030 or earlier. Implementation will be switched slightly, and i would really like to see what impact that will have.
* Moving checks in general (also consider how heavy permission checks are in average).
* Anything else is secondary for now.

Please post 'ncp version' as well (also to know if there are hooks), at least the build of NCP and the Minecraft version, the java version could also be of interest. I'd love to see profiling repeated for similar conditions with upcoming builds that contain the new implementation of the BlockCache internals (not such a big deal, but somewhat rewarding to see the difference), probably next week/end. _-> Implementation of BlockCache with nodes is done, a build will be pushed as soon as i have tested a little bit myself. So it'll be a comparison of build 1031 or later with build 1030 or earlier._

Other optimizations like permission caching are still hot topics, so any more detailed profiling data will be interesting in general. (Note that spigot timings won't be as useful, because those don't measure more fine grained method timings.)

If you can and want to confine profiling to few methods for use on an actually busy server, let me know, so i can pick some :).

**Comment by Howaner** [comment]
We use a custom nocheatplus version on commit https://github.com/NoCheatPlus/NoCheatPlus/commit/b2b5cd1e0377426d3383c125ba1883a6740954a6.
I could profile a 128 players survivalgames server with yourkit and upload the results. Would that help you?

**Comment by asofold** [comment]
That would certainly be useful, also for comparison with other servers. The BlockCache implementation hadn't changed for ages, essentially. Best would be to have the comparison between build 1030/before and 'latest', but it'll also be telling to see profiling data for varying setups - impact of permissions and other balance of timings.

**Comment by Platinteufel** [comment]
Medium big server, Paper 1.10.2, 50 Slots, ~20-30 players online. 

What do you need exactly? Here are some violations from today. I think the most SurvivalFly VLs are false postives. 
build 1041: http://pastebin.com/wuAzggh6
build 1030: http://pastebin.com/M8bLpkUG

**Comment by asofold** [comment]
@Platinteufel That's another interesting comparison, violation logs...

I was having in mind profiling information, such as generated by java profilers like "yourkit" or whichever, i.e. per-method timings, which can't be obtained via spigot only (spigot timings show events and tasks, but not sub-methods - could be interesting if there are bigger differences between builds of NCP, though).

**Comment by asofold** [comment]
Later again perhaps...
