### ISSUE TITLE
Grasspath issue 1.11

### ISSUE THREAD

**Issue by Sikatsu** [NoCheatPlus/Issues#315]
#### Short description of the issue.
You are unable to walk over a grasspath block. (Worked on 1.10)
#### Complete output of the _ncp version_ command (please prefer text here).
3.15.0-SNAPSHOT-sMD5NET-b1035
#### How to reproduce the issue (is it random / always happens / side conditions)?
Place a grasspath and try to walk over it
#### Have you made any (noteworthy) changes to the default configuration of NCP?
I am using MarkElf's his configuration file.
#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
No, I do not.
#### Use GitHub gists or http://pastebin.com/ or similar for huge logs! Link images/videos, for issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players
Is a log needed for this? I think it's easy to reproduce.

**Comment by asofold** [comment]
Can't reproduce on 1.11 with a 1.11 client and the latest build of NCP. 

* Have you kept an entry for grass_path in compatibility.blocks.overrideflags? In that case probably just remove it (NCP build 1035 and later).
* Is this a 1.10 client on a 1.11 server ? (full output of ncp version would tell a little more here :) ...) Are Protocol support plugins in use?
* Are there any violation messages / logs about this?

**Comment by Sikatsu** [comment]
Let me just get you the information you need.

**Comment by Sikatsu** [comment]
It's a basic survival server running on 1.11 Spigot (4 versions behind). Version output: http://pastebin.com/qYCNYgEK

In a recent build of MarkElf's his configuration, he added a GRASS_PATH line as followed:

`  blocks:
    allowinstantbreak: []
    overrideflags:
      snow: default
      piston_moving_piece: default+ign_passable+ground_height
      WATER_LILY: default+ign_passable+ground_height+height8_1
      GRASS_PATH: default+ign_passable+ground_height+height8_1`

There are violation messages of 200+ up to 2000+ for Fly.

**Comment by Sikatsu** [comment]
Issue is solved.
