### ISSUE TITLE
1.11 - Kicked for spam when using longer chat.

### ISSUE THREAD

**Issue by 0XE4** [NoCheatPlus/Issues#317]
1.11 introduced longer message length. Messages can now be 256 characters long instead of 100.

Using Build 1037, players are being kicked for spam when posting messages that are over 100 characters.

**Comment by asofold** [comment]
Build 1038 contains an adaption, so one long message shouldn't get prevented from start.

Can't really tell about overall balancing.

**Comment by 0XE4** [comment]
Thank you @asofold this has fixed the issue.

**Comment by asofold** [comment]
Thank you for the feedback, closing then.
