### ISSUE TITLE
Mining field of stone with diamond pickaxe ruins game experience

### ISSUE THREAD

**Issue by Michelele** [NoCheatPlus/Issues#320]
I simply can't mine a large area of just stone with a diamond pickaxe without enchants.
When I mine, I get alot of Visible and Direction flags, these makes the blocks reappear quite often and therefore ruins the game experience.

I have tested this on 3 different servers with nocheatplus, including my own, and I get the same problem. No lag was present.

All of them run the latest jenkins as of now using exactly the default configuration.

**Comment by asofold** [comment]
What happened, has this been resolveD? Just vanilla client without skill-related plugins?
