### ISSUE TITLE
Slabs, Chests, Fences and other various non-full blocks bug

### ISSUE THREAD

**Issue by Zootable** [NoCheatPlus/Issues#322]
When users try to step on a slab, or run into a fence, chest, enchant table ect they get teleported back and cant walk over it

 [Server] INFO ---- Version information ----
 [Server] INFO #### Server ####
 [Server] INFO git-Spigot-de459a2-51263e9 ~MC: 1.10.2~
 [Server] INFO detected: 1.10.2
 [Server] INFO #### NoCheatPlus ####
 [Server] INFO Plugin: 3.13.7-RC-sMD5NET-b925
 [Server] INFO MCAccess: 1.4.5-1.8.8|? / CB-Reflect
 [Server] INFO Features:
 [Server] INFO blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
 [Server] INFO checks: FastConsume
 [Server] INFO defaults: pvpKnockBackVelocity
 [Server] INFO Hooks: AllViolations~NCP~ 1.0 | Citizens2~cncp~ 2.0 | mcMMO~cncp~ 2.3
 [Server] INFO #### Related Plugins ####
 [Server] INFO CompatNoCheatPlus v6.6.2-RC-sMD5NET-b83 | ProtocolLib v4.1.0

Always happens

no

Mcmmo

**Comment by Janmm14** [comment]
Update NoCheatPlus to the latest version and test again.
http://ci.md-5.net/job/nocheatplus/

**Comment by asofold** [comment]
@Zootable  What @Janmm14 suggests :) - i'm a little bit on the redundant side here, but it's the best thing to do.

You could skip the latest [BLEEDING] changes, unless they've been out for one of those 'a while'-s.

**Comment by FirstReplay** [comment]
For what it's worth, we also have been seeing this behavior for months while keeping NCP updated.

**Comment by asofold** [comment]
@FirstReplay Which NCP which MC ... which month :) ... build 925 is clearly outdated, no chance with latest versions of MC.

**Comment by MarkElf** [comment]
@asofold Some people simply have a hard time navigating both to and through the site, i.e finding the download button to obtain the latest version of ncp, as it isn't made clear what they need to do once they reach ci.md-5.net/job/NoCheatPlus. 

@zootable @FirstReplay Here's a direct download link to the latest version of ncp which will more than likely resolve your movement issues: ci.md-5.net/job/nocheatplus/lastSuccessfulBuild/artifact/target/NoCheatPlus.jar

**Comment by asofold** [comment]
@MarkElf Concerning @FirstReplay, it looks like they have/had the latest builds in use  at some point of time (see other tickets). I still can't judge what "recent months" means in terms of combinations of plugins + server. :)

Closing as superseeded, due to NCP build 925 + 1.10.x and/or later.
