### ISSUE TITLE
Some commands can be used

### ISSUE THREAD

**Issue by Skilzar** [NoCheatPlus/Issues#327]
Hello!
Server version: spigot 1.8.8
Using version: NCP #1042
Use ProtocolLib 4.1.0
I banned commands, but some commands are still available

protection:
  plugins:
    hide:
      active: true
      nopermission:
        message: '&cI''m sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is in error.'
        commands:
        - plugins
        - version
        - icanhasbukkit
        - banker
        - drain
        - superpickaxe
        - //pos1
        - //sell poly
        - //hpos1
        - stop
        - reload
        - restart
        - mute
        - trader
        - save
        - save-all
        - save-off
        - save-on
        - whitelist
        - /worldedit:/set
        - /worldedit:/undo
        - /worldedit:/walls

But some commands are still available
For example: //hpos1, /worldedit:/set
If commands to forbid in this configuration, it is not available

commands:
    consoleonly:
      active: true
      message: '&cI''m sorry, but this command can''t be executed in chat. Use the console instead!'
      commands:
      - op
      - deop
      - /worldedit:/set
      - /worldedit:/undo
      - /worldedit:/walls

What's the problem ?

**Comment by asofold** [comment]
_- /worldedit: ..._ <- Which variants work? worldedit:/set ... /worldedit:/set ... /worldedit://set ...
Have you tested, which command actually has been used? Logging might log the used alias or it might log the command name not the alias... this needs to be ensured.

Have you tried both /pos and //pos  in the list? (also for others...)?

**Comment by Skilzar** [comment]
Yes, I added /hpos1 and //hpos1 in the config, but still not locked
Also I tried to add a command, which is not available on the server
Example: /trololo
I wrote the message, which is configured in spigot, but not in NCP

**Comment by asofold** [comment]
I might've overlooked something -

The nopermission section is meant to override the message for not having the permission to run the command, just for the commands listed there. The idea is to hide commands, because the typical "you don't have permissions +-" message would reveal the existence of the command. So that list isn't suitable to prevent use of commands, in case you have the permission to use the command.

The consoleonly section should restrict use to console only. That works?

**Comment by Skilzar** [comment]
Yes, config consoleonly perfectly blocks these commands
Then I will use it

**Comment by asofold** [comment]
Note that it should always be preferred to pinpoint with permissions, on the other hand this is another type protection, and not all plugins distinguish permissions alike.

Closing as 'resolved' (somehow).

**Comment by asofold** [comment]
Oh thank you :), forgot to close.
