### ISSUE TITLE
NullPointerException ReflectBase

### ISSUE THREAD

**Issue by ChrisLane** [NoCheatPlus/Issues#334]
#### Short description of the issue.
Null pointer exception on startup: ReflectBase

#### Complete output of the _ncp version_ command (please prefer text here).
---- Version information ----
#### Server ####
1.7.10-1614.58 ~MC: 1.7.10~
  detected: 1.7.10
#### NoCheatPlus ####
Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1046
MCAccess: 1.4.6|1.4.7|1.5.x|1.6.x|1.7.x|1.8.x|1.9.x|? / Bukkit-API
Features:
  blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2
  checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
  defaults: enforceLocation | storePlayers
  packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | CatchAllAdapter
Hooks: AllViolations~NCP~ 1.0 | mcMMO~cncp~ 2.3
#### Related Plugins ####
CompatNoCheatPlus v6.6.3-SNAPSHOT-sMD5NET-b87 | ProtocolLib v3.7.0

1.7.10-1614 build 58 of Thermos: https://github.com/CyberdyneCC/Thermos/releases/tag/58

#### How to reproduce the issue (is it random / always happens / side conditions)?
Produced at every startup.

#### Have you made any (noteworthy) changes to the default configuration of NCP?
Vanilla config.

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
Vanilla Thermos server.

#### Provide additional information, such as error/debug/violation logs.
-Startup-
https://gist.github.com/ChrisLane/6dfc88c93f7dae3036532920e6b07c59
-Shutdown-
https://gist.github.com/ChrisLane/dc9f0e7bffe392fc36d06d6cfdc65e9f

**Comment by asofold** [comment]
I'd assume the server type to not support nms, which means the reflection module can't possibly work. Perhaps i should add an exclusion check for this very constellation. For the time being you can force disable the reflection based module (compatibility ~ something ~ cbreflect: false).

Later perhaps, one could think about adding a compatibility module for Bukkit+forge type of servers, not sure it's possible/feasible though.

**Comment by ChrisLane** [comment]
After setting cbreflect to false, the same errors still occur.

**Comment by asofold** [comment]
May be fixed with the latest build (1046).

Overlooked where that one was coming from. With the output of the 'ncp version' command i would've seen this faster :). Perhaps the permissions were missing or are somehow incompatible. Does the command work from the console?

**Comment by ChrisLane** [comment]
Fixed! I wasn't able to reproduce the command issue via console or in-game so I've updated the version info (with my non-vanilla NCP server).

Thanks! I assume it would be best to have cbreflect set to false from now on.
