### ISSUE TITLE
Damage Hack

### ISSUE THREAD

**Issue by reded1** [NoCheatPlus/Issues#340]
I want to report a hak that many people use to damage themselves, and then use it as an advantage. Ex: Speed.
Code:
`PlayerUtils.damagePlayer()`

**Comment by UlisesOcana** [comment]
i actually can vouch for this. i hate it

**Comment by Janmm14** [comment]
#338?

**Comment by asofold** [comment]
What kind of advanages, just speed?

Indeed related: https://github.com/NoCheatPlus/Issues/issues/338

Perhaps we should see this as a duplicated ticket and use the earlier one,

**Comment by jonesdj1** [comment]
@asofold  it has no advantage other then they spam damage then they can use bunnyhop for about 10s then they have to spam damage about 10 more times and repeat.
