### ISSUE TITLE
New NoCheatPlus issue on 1.11.1 Spigot

### ISSUE THREAD

**Issue by Fonzee9** [NoCheatPlus/Issues#344]
http://pastebin.com/rK058gcx

**Comment by asofold** [comment]
I'd kindly ask the developers of this plugin...

com.kirelcodes.miniaturepets..??ע???????????????????????????????????????????י?????????????????????ט??????????ו??ץ??א??????????????.במ.א(SteerVechileInHandler.java:28), com.kirelcodes.miniaturepets..??ע???????????????????????????????????????????י?????????????????????ט??????????ו??ץ??א??????????????.ה.channelRead(PacketHandler.java:43),

... if it could be that they cause standard Bukkit events (e.g. vehicle exit) to fire off the primary server thread (asynchronous to it). If they do, i strongly suggest to alter the plugin not to do. It actually looks like they let the player force-exit a vehicle from within a packet handler that receives packets asynchronously to the primary server thread.

That being said (sorry if confused), this + the error log should be interesting to the makers of ~ something with miniaturepets.

**Comment by DrPigi** [comment]
We call leaveVehicle() off of the main thread.

**Comment by asofold** [comment]
@DrPigi Could it be indirectly caused somehow? The detection code in NCP is guarded by Bukkit.isPrimaryThread() {...} else { // complain about API use here.

So i am not sure what we are dealing with. One thing you can see in the trace is that leaving a vehicle triggers a teleport event, just for reference. We've had other plugin authors assuming that leaving a vehicle is trivial enough to be ok to do off primary thread. The early parts of the trace look like packet handling code causing an asynchronous teleportation event.

In this paste, a SteerVehicleInHandler is directly calling leaveVehicle on an entity.
org.bukkit.craftbukkit.v1_11_R1.entity.CraftEntity.leaveVehicle(CraftEntity.java:454), com.kirelcodes.miniaturepets..??ע???????????????????????????????????????????י?????????????????????ט??????????ו??ץ??א??????????????.במ.א(SteerVechileInHandler.java:28), com.kirelcodes.miniaturepets..??ע???????????????????????????????????????????י?????????????????????ט??????????ו??ץ??א??????????????.ה.channelRead(PacketHandler.java:43), io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)

**Comment by DrPigi** [comment]
Thats weird, in my testings it calls it on the main thread but once in a while its off the main. I will just wrap it in a BukkitRunnable runTask to make sure it's consistent. Will be fixed next update. Thank you asofold

**Comment by asofold** [comment]
@DrPigi You only need to schedule, if Bukkit.isPrimaryThread() returns false, though.

Some plugins might force ProtocolLib to process packets within the primary thread (worse performance though), and it may/should be different with a different combination of plugins - possibly it also depends on the number of cores/threads present/configured and/or server load. Whatever the reason is (i had that with flying packets too, once!), the ProtocolLib API specifies somewhere with the PacketAdapter classes or with listeners, that incoming packets may be processed asynchronously, so that's what one needs to account for.

**Comment by DrPigi** [comment]
@asofold Yes, I took account if that. :)

**Comment by asofold** [comment]
Assume resolved externally.
