### ISSUE TITLE
Elytra: touching water (vines/cobweb), boost + water, similar.

### ISSUE THREAD

**Issue by RoboMWM** [NoCheatPlus/Issues#346]
So yes when I get the time I will add more information.

Hopefully it is possible to still check if a player is flying/using the elytra when in water? If so, they should still be checked with creativefly, not survivalfly.

**Comment by asofold** [comment]
There is no increased friction !?

**Comment by RoboMWM** [comment]
Hmm... well I've temporarily disabled CreativeFly to allow rocket boosted elytras; I haven't observed if they're supposed to acquire friction when in water... but I would still think they should be checked with CreativeFly, yes?

**Comment by asofold** [comment]
If elytra mechanics are the same or 'special enough' in water, then perhaps yes.

But perhaps it's just an odd friction behavior when diving into water (friction would be on ground too and elytra turn off).

I'll need to reproduce + debug log to see what exactly triggers + why.

**Comment by MidnightSugar** [comment]
I'd like to also add, some players like to create elytra launch pads using cobwebs. This also causes survival fly checks to trigger.

**Comment by asofold** [comment]
Cobweeb should be a similar issue technically, though different friction/other envelopes.

**Comment by asofold** [comment]
Build 1101 contains fixes. This won't be perfect, but should be much better than before.

Rather: build 1104
