### ISSUE TITLE
1.11.2 Elytra Boost Freezing (fireworks, rockets)

### ISSUE THREAD

**Issue by MidnightSugar** [NoCheatPlus/Issues#347]
[####] Short description of the issue.
When firework rockets are used to boost elytras, they are frozen in place, causing very odd flight.

#### Complete output of the _ncp version_ command (please prefer text here).
21.12 18:04:12 [Server] INFO ---- Version information ----
21.12 18:04:12 [Server] INFO #### Server ####
21.12 18:04:12 [Server] INFO git-Spigot-7d78b81-a867313 ~MC: 1.11.2~
21.12 18:04:12 [Server] INFO detected: 1.11.2
21.12 18:04:12 [Server] INFO #### NoCheatPlus ####
21.12 18:04:12 [Server] INFO Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1046
21.12 18:04:12 [Server] INFO MCAccess: 1.4.5-1.11|? / CB-Reflect
21.12 18:04:12 [Server] INFO Features:
21.12 18:04:12 [Server] INFO blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11
21.12 18:04:12 [Server] INFO checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
21.12 18:04:12 [Server] INFO defaults: pvpKnockBackVelocity
21.12 18:04:12 [Server] INFO packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
21.12 18:04:12 [Server] INFO Hooks: AllViolations~NCP~ 1.0 | mcMMO~cncp~ 2.3
21.12 18:04:12 [Server] INFO #### Related Plugins ####
21.12 18:04:12 [Server] INFO CompatNoCheatPlus v6.6.3-SNAPSHOT-sMD5NET-b86 | ProtocolLib v4.2.0

#### How to reproduce the issue (is it random / always happens / side conditions)?
Use rockets while gliding with the elytra. It always happens. I tried using the default configuration for the latest version of NCP, and people couldn't fly with elytras at all.

#### Have you made any (noteworthy) changes to the default configuration of NCP?
I use the latest version of the config here:
[http://www.mc-market.org/resources/475/](url)
I do not have permission to post the config here.

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)? 
I have no other plugins that affect elytras.

#### Provide additional information, such as error/debug/violation logs. (For reproducible issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) Use GitHub gists or http://pastebin.com/ or similar for huge logs, or attach a (zip-) file here. For image uploads, please prefer a site that allows viewing without JavaScript, you can upload file attachments for issues right here.

[https://gist.github.com/MidnightSugar/78ee65d56a99998849b9487f0fe73220](url)

**Comment by jonesdj1** [comment]
yeah ncp did not update yet for 1.11.2

**Comment by Sikatsu** [comment]
Same issue.

**Comment by FirstReplay** [comment]
Yep, awaiting 1.11.2 compatibility.

**Comment by asofold** [comment]
Not sure how to detect when fireworks are active, at present. Any hints, anyone?

**Comment by jonesdj1** [comment]
@asofold its client sided damn mojang

**Comment by asofold** [comment]
@jonesdj1 Are you 100% sure? In that case what happens with the fireworks (entity?) server-side? Usually it would have to take it's ordinary course and be visible to others, or it just gets removed and display is client side only. In the latter case, the removal needs some type of server side packet.

All in all i am convinced that there is _something_ the server can notice, at least for the case that other players can see the elytra+fireworks wearing player (includes seeing the fireworks effect with the elytra).

**Comment by Janmm14** [comment]
@asofold I think it might cause a PlayerInteractEvent to appear.

**Comment by jonesdj1** [comment]
@asofold looking at server code there is nothing I can see so far.

**Comment by asofold** [comment]
Can players see another player using elytra + fireworks? This would be proof of something being sent... one of my guesses would be some nbt tag/content sent with the elytra item, so it propagates to other players too. But we need to know if you can see another player using elytra  + fireworks ...

**Comment by Chnkr** [comment]
The latest protocol version had some NBT changes related to fireworks, so i would guess that is the case

**Comment by WhiteNoizes** [comment]
@asofold 
Yes bro, I have just tested it, players can see the firework being used ( the partical trial )
Hope this helps

**Comment by asofold** [comment]
"Perfect". Now we need someone to detect/know/find-out what makes it appear so.

With nbt being a strong hint, one could log all nbt content for players with elytra and possibly for fireworks too, for reference.

**Comment by Chnkr** [comment]
@asofold https://matsv.nl/PAaaS/ you can view the protocol changes between `1.11` and `1.11.2` here. There seems to be a extra integer field being added, which could be interesting to look at.

**Comment by DmitryRendov** [comment]
Hello guys, is this still not solved? Im getting lots of survivalfly notifications when users are trying fireworks. Thank you! Great job and great plugin anyway...

**Comment by jonesdj1** [comment]
Nope not yet

**Comment by asofold** [comment]
Doesn't setting horizontal (and if necessary ascend) speeds work for the elytra model?

That should be MUCH preferred over deactivating the creativefly check.

**Comment by FirstReplay** [comment]
The problem is that while fireworks are causing false-positives, there are current (1.10-1.11.2) working modules in hacked clients like Impact and Wurst that allow endless elytra flying, hovering, insane speeds and vertical movement all on NCP 1054, ProtocolLib 346 and Paper 1029. I think finding a cure for both is a fairly difficult task.

**Comment by bigpresh** [comment]
Right, I've verified that a PlayerInteractEvent fires when a player uses a firework to boost, and that `event.getMaterial()` returns FIREWORK - so it's definitely possible, server-side, to detect that they're using a firework on an air block.  I imagine combining that with a check that they're in the air and have Elytra equipped should be enough to know that they're using a firework to boost their Elytra flight, and that it should be allowed?

**Comment by asofold** [comment]
@bigpresh That looks good, i'll check that then.

**Comment by bigpresh** [comment]
Please let me know if I can help in any way!

As a temporary workaround I was considering using NCPHookManager to catch the survivalfly violation events, and check if the user is flying with Elytra and holding a rocket, and cancel NCP's action if so.  Or, better still, also hook PlayerInteractEvent and remember the last time the user fired a rocket, and only cancel the NCP action if they've fired a rocket recently enough, in order to prevent a hacked client to provide continuous boosting without using up fireworks, only holding them.

I'm not much of a Java coder though, to be honest!

**Comment by asofold** [comment]
You could use the hook manager, test if the player is wearing elytra, and cancel the violation processing (and possibly subtract the addedVL from the  MovingData.survivalFlyVL) - you could also monitor the speed yourself and NCP has some past move tracking, so you could relate moves to past moves for reference...

i assume i'll get something done around monday/tuesday, so it'll probably not pay.

**Comment by bigpresh** [comment]
Yeah, I don't really want to go to all that work bodging around it if you think you'll be able to have NCP working with Elytra boost in the near future - I'm not that desperate for it, we've held off 1.11.2 for a good while, and even if I upgrade tonight like I was considering, it's just a new feature that players didn't have before, it's not game-breaking.

If I can be of any help in testing etc, let me know, and good luck :)

**Comment by asofold** [comment]
Thank you, i'll make a distinct attempt on tuesday :). With the interact event it'll be much easier.

**Comment by asofold** [comment]
Sorry, got stuck the week, and i have a stupid device with a stupidly sounding fan here now.

If i don't turn 100% mad, i'll do this right after the fall damage issue, supposedly coming monday/tuesday (didn't specify which tuesday, last time).

**Comment by bigpresh** [comment]
:)

**Comment by asofold** [comment]
Basic fumbling reveals, this appears to be a PlayerInteractEvent (ok...) just as you mentioned, but in cancelled state, with useItemInHand() returning Result.DEFAULT. Setting it to DENY seems to cancel the boost.

So this is entirely doable with Bukkit, i'll need to access some duration property (assume Bukkit has that), then allow some extra speed to any direction with minimum physics/friction/max-speeds applied. For the latter i am hesitating what kind of effect to use (velocity doesn't seem appropriate, thinking ahead of generic effects perhaps, or most likely another type of effect done with an integer and a double for starters. Thus perhaps this wednesday is a realistic estimate for a development build containing some support for the boost feature.

**Comment by asofold** [comment]
Very close now. Getting power is easy, flight duration is something like (20 + power) ticks. One can fly up with it and faster horizontal (descend isn't doing that much).

**Comment by bigpresh** [comment]
Awesome! :)  As mentioned, if you'd like assistance testing let me know, I'd be happy to throw a dev build on my test server and try it out.

**Comment by ScuroK** [comment]
@asofold are you able to fix it?

**Comment by asofold** [comment]
Yes, i've been having a slight cold and had to rearrange some things. I'm still/now at it.

Implementation-wise, few things are missing, which will still need testing and balancing. This sunday i'll certainly have a dev build with the first version of it.
* Modeling the effect in data + invalidation mechanics (rather simple).
* Adding the altered physics to creativefly (not difficult, but needs testing and repetition to find suitable paramters).

**Comment by ScuroK** [comment]
You are awesome!!!! No rush <3 be well soon :)

**Comment by asofold** [comment]
Did the latest build(s) do something on that account? (CAREFUL with production / auto banning :))

I let it allow the vdist part (more). There may still be all sorts of edges left.

**Comment by ScuroK** [comment]
@asofold 
I just did some testing and it seems much much better now! I did not use the standard config but i still can see an impprovement! :) you are the protector of minecraft servers! ^^ thx alot!

**Comment by DmitryRendov** [comment]
@asofold the same for me - your latest dev build works pretty fine - my players are happy! Thank a lot!

**Comment by ScuroK** [comment]
but im not 100% sure. now i  just had some problems... but it works better than before. 
i went to another world (seperate config but same settings) and there i had the old issues again.

**Comment by bigpresh** [comment]
I have given this a good test on our test server, and all seemed well.  I'm happy to say that I pushed it to our live server tonight, and players are happily boosting about :)

@asofold - thank you :)

**Comment by bigpresh** [comment]
One issue I have had reports of is SurvivalFly triggering when using a boost when in / skimming water (e.g. coming too low and your feet touch the water) - and also trying to boost-fly through vines - but I haven't yet had a chance to reliably reproduce those myself.

**Comment by asofold** [comment]
Water - vines :) - most certainly issues.

I

**Comment by asofold** [comment]
Concerning edge cases such as shortly touching water/vines: https://github.com/NoCheatPlus/Issues/issues/346
