### ISSUE TITLE
KillAura hack

### ISSUE THREAD

**Issue by UlisesOcana** [NoCheatPlus/Issues#352]
#### Short description of the issue.
Hits near entity and its almost undetectable for ncp!

**Comment by MarkElf** [comment]
Did you really have to create a duplicate of an open issue just below this one that does not contribute anything?

Please refer to #349.

**Comment by MarkElf** [comment]
Did you really have to create a duplicate of an open issue just below this one that does not contribute anything? I get that kill-aura is a "hot topic" but we don't need multiple open tickets covering the same content.

Please refer to #349.

**Comment by asofold** [comment]
It does duplicate at least one existing issue :).
