### ISSUE TITLE
Teleporting from eating a chorus fruit freaks out the anticheat.

### ISSUE THREAD

**Issue by AndrewSumsion** [NoCheatPlus/Issues#358]
#### Short description of the issue.
Teleporting from eating a chorus fruit freaks out the anticheat.

#### Complete output of the _ncp version_ command (please prefer text here).
[09:37:42 INFO]: ---- Version information ----
[09:37:42 INFO]: #### Server ####
[09:37:42 INFO]: git-Spigot-7d78b81-e2a288c ~MC: 1.11.2~
[09:37:42 INFO]:   detected: 1.11.2
[09:37:42 INFO]: #### NoCheatPlus ####
[09:37:42 INFO]: Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1035
[09:37:42 INFO]: MCAccess: 1.4.5-1.11|? / CB-Reflect
[09:37:42 INFO]: Features:
[09:37:42 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10
[09:37:42 INFO]:   checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter
[09:37:42 INFO]:   defaults: pvpKnockBackVelocity
[09:37:42 INFO]: Hooks: AllViolations~NCP~ 1.0
[09:37:42 INFO]: #### Related Plugins ####
[09:37:42 INFO]: CompatNoCheatPlus v6.6.2-RC-sMD5NET-b83

#### How to reproduce the issue (is it random / always happens / side conditions)?
Just eat a chorus fruit. It always happens
#### Have you made any (noteworthy) changes to the default configuration of NCP?
Nope
#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
Nope
#### Provide additional information, such as error/debug/violation logs. (For reproducible issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) Use GitHub gists or http://pastebin.com/ or similar for huge logs, or attach a (zip-) file here. For image uploads, please prefer a site that allows viewing without JavaScript, you can upload file attachments for issues right here.
It says "(Player) has moved wrongly!" whenever someone eats a chorus fruit. For instance "El_Chupe has moved wrongly!"

**Comment by jonesdj1** [comment]
sounds like the mojang server "anticheat" can you list your plugins as you may think they dont do anything when they could be making it happen by canceling a event etc.

**Comment by jonesdj1** [comment]
@asofold can you close this as they have not responded in almost a week and it sounds like another plugin not related to ncp or it could even the server jar they are running.

**Comment by asofold** [comment]
It's ME who hasn't responded for a week :).

The messages like "moved wrongly" and "moved too quickly" come from the vanilla server code. It may still be related to plugins, but it could also be a bug in the server version. Possibly it's also a result of latency issues (player sends moves the server has sent a teleport, so NCP sets back, and the player sends moves for the teleport position still due to latency, so the server sets the m back for "moved wrongly").

What does 'ncp info' show before+after getting set-back like this, are there any violation logs/alerts with NCP on this?

**Comment by asofold** [comment]
Assume fixed/superseded.
