### ISSUE TITLE
1.7 / 1.8 Teleport in air is bugged

### ISSUE THREAD

**Issue by Aangiix3** [NoCheatPlus/Issues#36]
There is a major bug in this version (#895) with 1.7.10!
When I set a warp in the air, and people teleport there, they cannot move once they get teleported!

With #853 it works perfectly fine (Version I'm currently running)

Spigot Version: 1.7.10 PaperSpigot (latest Version)
ProtocolLib: No Version used
Warp Plugin: "player.teleport(loc, TeleportCause.COMMAND);"  - No special things, just a simple teleport command
Plugins: WorldEdit, WorldGuard, NoCheatPlus, Custom ServerSystem

Log:
15-12-07 12:36:14 [FEIN] | canceldead 36 (36/0) | illegalitem 0 | boatsanywhere 0 | throwenderpearl 0 | fakeinvulnerable 0 | eggonentity 0 | event.player.move.handled 522393 (522393/0) | event.player.move.handled.pos 202743 (202743/0) | event.player.move.handled.look 42414 (42414/0) | event.player.move.handled.pos_look 277236 (277236/0) |

**Comment by asofold** [comment]
Oh PaperSpigot.

Could you add the full output of the "ncp version" command? Need check what compat module is activated and what NCP assumes for the server version, just post the full thing.

Has your configuration file been kept unaltered for a long time? There might be some things disabled by default now, that had been enabled before. (not knowing, perhaps you could paste it or tell when it#s been last regenerated). The other guess is that the version isn't recognized and NCP might activated some nasty feature incompatible/unneeded with PaperSpigot, quick guesses are setting the enforcelocation settings to false.


Have you ever made an on-the-fly debug log ?

https://github.com/NoCheatPlus/Docs/blob/master/Development/Debugging.md#on-the-fly-debug-output-for-individual-players

This would be best to do for a player who can reproduce the issue.

**Comment by Aangiix3** [comment]
[15:17:16] [Server thread/INFO]: ---- Version information ----
[15:17:16] [Server thread/INFO]: #### Server ####
[15:17:16] [Server thread/INFO]: git-PaperSpigot-63fe5e4 (MC: 1.7.10)
[15:17:16] [Server thread/INFO]: (detected: 1.7.10)
[15:17:16] [Server thread/INFO]: #### NoCheatPlus ####
[15:17:16] [Server thread/INFO]: Plugin: 3.13.3-BETA-sMD5NET-b895
[15:17:16] [Server thread/INFO]: MCAccess: 1.7.10 / CB3100
[15:17:16] [Server thread/INFO]: Features:
[15:17:16] [Server thread/INFO]:   blocks: BlocksMC1_4(base) | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2
[15:17:16] [Server thread/INFO]:   checks: FastConsume | Gutenberg
[15:17:16] [Server thread/INFO]: Hooks: AllViolations(NCP) 1.0


CONFIG: http://pastebin.com/Wx9dFKBJ

Tested it out on our testserver.
VIDEO: https://www.youtube.com/watch?v=KPDOnZzafKg (Censored name of my server)

**Comment by asofold** [comment]
1. You should disable the vanilla fly check, if you have survivalfly enabled. It can lead to conflicts and obviously is kicking the player (perhaps it's just enabled on the test server).

2. We need to know more about the in-air-rubberbanding. Could you re-test, but before testing run "ncp remove *" or "ncp remove PLAYERNAME" and after testing run "ncp info PLAYERNAME" for the player? We'd like to see which checks trigger at all, as it looks like check set backs.

**Comment by Aangiix3** [comment]
1. Yes, only on the test server. It happened on the main server exactly the same as on the test server. (The set-back part)
2. moving.survivalfly is the only check that gets triggered

**Comment by asofold** [comment]
Good, survivalfly may be mendable.

Could you do the moving debug log on the test server?

It's explained here: https://github.com/NoCheatPlus/Docs/blob/master/Development/Debugging.md#on-the-fly-debug-output-for-individual-players

Not sure that's enough explanation, essentially running the command will let ncp write lots of output to the log file (in plugins/NoCheatPlus...), then reproduce the issue, then maybe remove the data to end debugging or reload the config to switch the log file, in case you're using a folder for log file name.

**Comment by Aangiix3** [comment]
Done the /ncp debug player:
http://pastebin.com/zDYynifh

**Comment by asofold** [comment]
Wonderful - that might help removing the loop. Check out build 896 for a blind (untested) fix attempt.

One small point for the debug log - it looks like the part you pasted starts late. Best is to start before issuing the command, so we can be sure to catch the initial violation (not sure it's in or not). So you could include a short part from before, e.g. move a tiny bit and then issue the command. I made the special case pretty tight, could be it's too strict, but you'll see.

**Comment by Aangiix3** [comment]
Hey, 896 works somewhat fine.
If I teleport and stay still, it works perfect.
However, if I teleport while going forward I get set-back
It's normal falling, so you shouldn't be set-back.

Video: https://www.youtube.com/watch?v=BDd8WBmA6Ek&feature=youtu.be

To the comment: What I posted from the log is all what happened after /ncp debug player <name>

**Comment by asofold** [comment]
According to the log, the player is making a microscopic move upwards before falling. Not sure this is on PaperSpigot only, i couldn't reproduce it on Spigot.

Build 898 contains an adaption to allow moving horizontally.

**Comment by asofold** [comment]
Note the beta release with build 901 containing another fix for this context.

**Comment by asofold** [comment]
Assume fixed for most.
