### ISSUE TITLE
Can't walk up slabs.

### ISSUE THREAD

**Issue by OniOniOn-** [NoCheatPlus/Issues#364]
#### Short description of the issue.
Going from ground to half slab doesn't work. (also jumping doesnt work)

#### Complete output of the _ncp version_ command (please prefer text here).
[04:36:28 INFO]: ---- Version information ----
[04:36:28 INFO]: #### Server ####
[04:36:28 INFO]: git-Spigot-7d78b81-96f03d9 ~MC: 1.11.2~
[04:36:28 INFO]:   detected: 1.11.2
[04:36:28 INFO]: #### NoCheatPlus ####
[04:36:28 INFO]: Plugin: 3.13.7-RC-sMD5NET-b925
[04:36:28 INFO]: MCAccess: 1.4.5-1.8.8|? / CB-Reflect
[04:36:28 INFO]: Features:
[04:36:28 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
[04:36:28 INFO]:   defaults: pvpKnockBackVelocity
[04:36:28 INFO]: Hooks: AllViolations~NCP~ 1.0
[04:36:28 INFO]: #### Related Plugins ####
[04:36:28 INFO]: ProtocolLib v4.2.0

#### How to reproduce the issue (is it random / always happens / side conditions)?
Walk up to half slab. Also walking on or jumping to grass path, chest block is completely broken.

#### Have you made any (noteworthy) changes to the default configuration of NCP?
Reinstalled NCP and was same.

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating?
X

#### Provide additional information, such as error/debug/violation logs. (For reproducible issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) Use GitHub gists or http://pastebin.com/ or similar for huge logs, or attach a (zip-) file here. For image uploads, please prefer a site that allows viewing without JavaScript, you can upload file attachments for issues right here.

**Comment by MarkElf** [comment]
Download and use the latest development build. Build 925 has no support for 1.11.2.

http://ci.md-5.net/job/NoCheatPlus/lastSuccessfulBuild/artifact/target/NoCheatPlus.jar

**Comment by OniOniOn-** [comment]
@MarkElf Oh thanks it works perfectly. I downloaded it from bukkit site but it must be outdated, where can I get latest build?

**Comment by Janmm14** [comment]
@OniOniOn- He linked it for you...

**Comment by asofold** [comment]
http://ci.md-5.net/job/NoCheatPlus/

Also consider checking out the changes list: http://ci.md-5.net/job/NoCheatPlus/changes
(Be wary about [BLEEDING] tags, if they're not older than a few days, for sure, have backups anyway :) ).
