### ISSUE TITLE
Moving-passable issue

### ISSUE THREAD

**Issue by sleepytm** [NoCheatPlus/Issues#366]
This is just a report of a false positive i recently found on a testserver.

Even though the phase (MOVING_PASSABLE) check is amazing, it false positives a lot when u move towards the side of an not-connected(its connected in one direction) iron bar.
Example for better comprehension: block located at x=12 y=2 z= 3 and the iron bar at x=13 y=2 z=3 , now if the player collides with the unconnected side of the iron bar (he comes from x=11 y =2 z=3) he gets false flagged for moving passable.

**Comment by Janmm14** [comment]
@sleepytm
The template has a reason!

Most mportant is /ncp version output (please no screenshot, copy from console)

Do you use protocol hacks like 1.9 on a 1.8 server?

**Comment by asofold** [comment]
Absolutely: Need the output of the 'ncp version' command. At least tell us the build number of NCP and the server version for a quick start. Issues with block shapes can always remain, especially with multiple different client versions connected to one server (like @Janmm14 suggested: protocol support plugins involved?), but they can also happen if the server is updated, but NCP is not, thus NCP can't judge block shapes.

**Comment by asofold** [comment]
This might've been due to
*  MC version vs. NCP version, 
* Passable not re-checking with alternate order of axes. Added in build 1098.
* Bugs (shape done wrongly, other).

**Comment by asofold** [comment]
Closing as superseded - due to related updates/fixes/inactivity. If issues persist, please drop a note.

**Comment by ygtdmn** [comment]
Issue persist:
https://github.com/NoCheatPlus/Issues/issues/505
