### ISSUE TITLE
NoCheatPlus Isue

### ISSUE THREAD

**Issue by Mineacer** [NoCheatPlus/Issues#368]
http://pastebin.com/qKH12q1Y

I have not made any configuration changes to NCP or CompatNCP.

**Comment by MarkElf** [comment]
Update to the latest development build of Cncp and attempt to recreate the error. Please also post the output of /ncp version. 

http://ci.md-5.net/job/CompatNoCheatPlus/87/artifact/CompatNoCheatPlus/target/cncp.jar

**Comment by Mineacer** [comment]
Doing /ncp version on my current state looks like this: (divided into two pictures)
1) http://puu.sh/tgw4T/6dd75ef198.jpg
2) http://puu.sh/tgw4T/6dd75ef198.jpg

I've updated to the latest development build of Cncp. 

Hope this fixes

**Comment by asofold** [comment]
@Mineacer Using the latest cncp with the latest NCP is best at present (sorry for the not-ever-present official releases, but it's what we have at present). 

Concerning screenshots:
* You do know there is a client log (or do you take screen shots from a mobile device (...))? On a PC you could check the launcher, and/or activate 'keep launcher open' in your (testing-) profile, so you can copy any text from there conveniently.
* You can upload the images to any of your posts here at GitHub directly (there may be problems with mobile devices again :p) - when editing, just underneath the ~ blue dashed line inside the blue rectangle bounds of the editing area, there is the hints: "Attach files by dragging & dropping, selecting them, or pasting from the clipboard. " You can click on _selecting them_ for classic file upload.

**Comment by asofold** [comment]
Both NCP and cncp have official releases at dev.bukkit.org (NCP also on spigotmc and of course both at jenkins).

Closing as 'superseded', assuming using the new set of NCP+cncp will not have this issue.
