### ISSUE TITLE
Draconic Evolution Mob Grinder

### ISSUE THREAD

**Issue by ToXIQuE** [NoCheatPlus/Issues#370]
#### NoCheatPlus ####
 Plugin: 3.11.1-RC-sMD5NET-b743
MCAccess: 1.4.6|1.4.7|1.5.x|1.6.x|1.7.x / Bukkit-API

#### Example:
 NCP: [Draconic-Evolution] failed Speed: tried to attack with too high a frequency. VL 673.
NCP: [Draconic-Evolution] failed Improbable: meets the improbable more than expected. VL 127713.
 NCP: [Draconic-Evolution] failed Speed: tried to attack with too high a frequency. VL 603.
NCP: [Draconic-Evolution] failed NoSwing: didn't swing arm. VL 48.
 NCP: [Draconic-Evolution] failed Improbable: meets the improbable more than expected. VL 51760.
NCP: [Draconic-Evolution] failed Speed: tried to attack with too high a frequency. VL 628.

Any help would be appreciated. I tried the obvious exempt but player is not online, tried to add it to groupmanager but player does not exist, 

Thanks!

**Comment by MarkElf** [comment]
Assuming that you actually are still running build 743 (for whatever reason), update to the latest development build linked here: http://ci.md-5.net/job/NoCheatPlus/1054/artifact/target/NoCheatPlus.jar

And before you ask,  yes, it'll work on whatever outdated version of mc that you are running as ncp contains support from 1.4.5 - 1.11.

**Comment by asofold** [comment]
It also matters which server version this is, so after updating NCP showing the full output of 'ncp version' would be good.

**Comment by asofold** [comment]
Likely a compatibility thing for some skill-like thing.

Can't do much without more information.
