### ISSUE TITLE
NoFall is detected incorrectly 

### ISSUE THREAD

**Issue by Xayanix** [NoCheatPlus/Issues#372]
#### Short description of the issue.
NoFall is detected incorrectly 
#### Complete output of the _ncp version_ command (please prefer text here).
http://scr.hu/0duk/wcy4z
#### How to reproduce the issue (is it random / always happens / side conditions)?
Happens always (tested on 1.7.10)
#### Have you made any (noteworthy) changes to the default configuration of NCP?
no
#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
no
#### Provide additional information, such as error/debug/violation logs. (For reproducible issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) Use GitHub gists or http://pastebin.com/ or similar for huge logs, or attach a (zip-) file here. For image uploads, please prefer a site that allows viewing without JavaScript, you can upload file attachments for issues right here.

NoCheatPlus absorbs every fall damage.

**Comment by Xayanix** [comment]
Disabling NoFall detection fixes issue.
It PROBABLY started to happen after fixing: https://github.com/NoCheatPlus/Issues/issues/354

**Comment by Janmm14** [comment]
> Disabling NoFall detection fixes issue.

Oh really.

So what actually happens?

You tell it incorrectly detects NoFall while you also say it absorbs fall damage.

Providing debug logs (at least normal cheat detection logs) is heavily recommended.

**Comment by Xayanix** [comment]
NoCheatPlus detects every fall damage as NoFall and causes to absorb it.

**Comment by asofold** [comment]
@Xayanix You mean the player takes fall damage and NoFall is triggering a violation?

**Comment by Xayanix** [comment]
I will post video soon.

**Comment by asofold** [comment]
A video can help too :).

Is fall damage dealt?

Perhaps a plugin list could be interesting too, if that's possible to show.

**Comment by Xayanix** [comment]
NoCheatPlus cancels EVERY fall damage. Tested on clear 1.7.10 server with only NCP installed.

**Comment by asofold** [comment]
Looks like Spigot 1.7.10 and  1.8.9 are affected (didn't test on 1.8.3).

**Comment by Xayanix** [comment]
Yeah thats what im talking about.

**Comment by asofold** [comment]
Currently it looks like multiple or nested events fire, should get fixed soon.

Just for reference, this issue seems to result from this commit: https://github.com/NoCheatPlus/NoCheatPlus/commit/b6ae8049b73d42682cf2637cbb9bd3a06884914f

**Comment by asofold** [comment]
Build 1057 should fix it for 1.7.10. 

(MC 1.8.8 is not affected, i just had a plugin cancelling all damage in the plugin directory.)
