### ISSUE TITLE
1.11.2 Build1060 applying speed potions while sprinting kicks for flying VL 9223372036854775807

### ISSUE THREAD

**Issue by i9hdkill** [NoCheatPlus/Issues#377]
#### Complete output of the _ncp version_ command (please prefer text here).
---- Version information ----
[19:03:28 INFO]: #### Server ####
[19:03:28 INFO]: git-Paper-1042 ~MC: 1.11.2~
[19:03:28 INFO]:   detected: 1.11.2
[19:03:28 INFO]: #### NoCheatPlus ####
[19:03:28 INFO]: Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1060
[19:03:28 INFO]: MCAccess: 1.11-1.11.2 / Spigot-CB-1.11_R1
[19:03:28 INFO]: Features:
[19:03:28 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11
[19:03:28 INFO]:   checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[19:03:28 INFO]:   defaults: pvpKnockBackVelocity
[19:03:28 INFO]:   packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
[19:03:28 INFO]: Hooks: AllViolations~NCP~ 1.0
[19:03:28 INFO]: #### Related Plugins ####
[19:03:28 INFO]: ProtocolLib v4.2.1-SNAPSHOT-b346

#### How to reproduce the issue (is it random / always happens / side conditions)?
We are using a plugin that applies potion effects when clicking an item that functions as a weapon to give a "scope" vision effect.
It applies these effects:
http://prntscr.com/e43jjc
If "scoping" when standing still, it's fine. But when scoping while in running, (scoping stops the player), he gets kicked for flying or related. with VL 9223372036854775807
That did work fine with spigot 1.8.8/1.11.2 and ncp 1012
The player gets a zoom effect and stands still (I guess due to the potion effect)

#### Have you made any (noteworthy) changes to the default configuration of NCP?
no changes

Debug info:
https://pastebin.com/KU6Mqx5p

**Comment by asofold** [comment]
This could be related to Ticket https://github.com/NoCheatPlus/Issues/issues/367 - looks like the given information could help resolve both.

**Comment by asofold** [comment]
I'd be interested in tracking down the build at which it starts failing.

E.g. 1046 works and 1047 has the issue? (Despite odd, there has been some changes like checking with Double.isInfinite instead of '== Double.NEGATIVE_INFINITY'). Binary search would be really cool :) - not sure you have the resources to do such. If it still works with 1046 we'd have one more data point here. Build 1053 seems to create infinite VLs too (see other ticket).

**Comment by i9hdkill** [comment]
Hi,
as it's 100% reproducible, I can and will test some builds later.
Thanks for your information!

**Comment by i9hdkill** [comment]
Did some further testing.
When clicking the item that gives speed potion that "roots" the player, while running, this shows up in log:
NCP 1012:
17-02-05 02:05:24 [INFORMATION] HexagonMC failed SurvivalFly: tried to move unexpectedly. VL 20.
17-02-05 02:05:28 [INFORMATION] HexagonMC failed SurvivalFly: tried to move unexpectedly. VL 101.
17-02-05 02:05:58 [INFORMATION] HexagonMC failed SurvivalFly: tried to move unexpectedly. VL 140.
17-02-05 02:06:03 [INFORMATION] HexagonMC failed SurvivalFly: tried to move unexpectedly. VL 63.
NCP: 1023:
17-02-05 02:10:02 [INFORMATION] HexagonMC failed SurvivalFly: tried to move unexpectedly. VL 34.
17-02-05 02:10:10 [INFORMATION] HexagonMC failed SurvivalFly: tried to move unexpectedly. VL 103.
NCP 1024:
17-02-05 02:08:02 [INFORMATION] HexagonMC failed SurvivalFly: tried to move from 2523.20, 73.25, 1853.73 to 2523.20, 73.18, 1854.02 over a distance of 0.30 block(s). VL 9223372036854775807.
17-02-05 02:08:02 [INFORMATION] (CONSOLE) Kicked HexagonMC : Kicked for flying (or related)
Instant kick.

**Comment by asofold** [comment]
Feels like i could point at the line of code, something like "hAllowedDistance = ... * speedMultiplier", with the latter being -inifinite - unfortunately i'm currently knocked out, so i can't even guarantee hitting the screen 100% of the time. I'll review this as soon as possible.

**Comment by asofold** [comment]
Build 1063 contains a cap for hacc - in this case it might still lead to rubberbanding, provided it prevents the infinity issue at all. The debug log also shows that hacc is at infinity before survivalfly triggers, it just doesn't trigger before having counted to 30.

**Comment by i9hdkill** [comment]
Seems to be fixed! Thank you.

**Comment by asofold** [comment]
Please drop a note if issues persist.
