### ISSUE TITLE
On my server the cheaters can walk(fly) on the water

### ISSUE THREAD

**Issue by Skilzar** [NoCheatPlus/Issues#378]
#### Short description of the issue.

Hello! :)
On my server the cheaters can walk(fly) on the water
Here is an example found on youtube: https://www.youtube.com/watch?v=-BBJk95nStA

#### Complete output of the _ncp version_ command (please prefer text here).

---- Version information ----
#### Server ####
git-Spigot-21fe707-e1ebe52 ~MC: 1.8.8~
  detected: 1.8.8
#### NoCheatPlus ####
Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1060
MCAccess: 1.8.4-1.8.8 / Spigot-CB-1.8_R3
Features:
  blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
  checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
  defaults: pvpKnockBackVelocity
  packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | CatchAllAdapter
Hooks: AllViolations~NCP~ 1.0
#### Related Plugins ####
ProtocolLib v4.1.0

#### How to reproduce the issue (is it random / always happens / side conditions)?

Cheat

#### Have you made any (noteworthy) changes to the default configuration of NCP?

There is, but only on the blocked commands

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?

ViaVersion

**Comment by jonesdj1** [comment]
its not flight its called waterwalk/jesus and there not "flying" just walking on the water

**Comment by asofold** [comment]
Doesn't this simply duplicate Ticket https://github.com/NoCheatPlus/Issues/issues/34 ?

Our primary focuse will be speeding on water rather.
