### ISSUE TITLE
A User of the CMI spigot Forum posted this error in the CMI Forum

### ISSUE THREAD

**Issue by CloudeLecaw** [NoCheatPlus/Issues#380]
#### Short description of the issue.
Since the Lattest Version of CMI he gets an Error inside his console with the latest NCP version.
This error spamms his console.

#### Complete output of the _ncp version_ command (please prefer text here).
latest jenkis Version:

#### How to reproduce the issue (is it random / always happens / side conditions)?
Run CMI Latest Version and NCP Latest Version on a Server together

#### Have you made any (noteworthy) changes to the default configuration of NCP?
i dont know, i would say he use the default config.

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
He has not say anything of other AntiCheatPlugins

#### Provide additional information, such as error/debug/violation logs. (For reproducible issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) Use GitHub gists or http://pastebin.com/ or similar for huge logs, or attach a (zip-) file here. For image uploads, please prefer a site that allows viewing without JavaScript, you can upload file attachments for issues right here.
Errorlog:
08.02 11:23:08 [Server] ERROR Failed to add .silent child permission for nocheatplus.checks: NullPointerException
08.02 11:23:08 [Server] ERROR java.lang.NullPointerException
08.02 11:23:08 [Server] INFO org.bukkit.craftbukkit.v1_11_R1.entity.CraftHumanEntity.recalculatePermissions(CraftHumanEntity.java:139)
08.02 11:23:08 [Server] INFO org.bukkit.plugin.SimplePluginManager.dirtyPermissibles(SimplePluginManager.java:642)
08.02 11:23:08 [Server] INFO org.bukkit.plugin.SimplePluginManager.calculatePermissionDefault(SimplePluginManager.java:630)
08.02 11:23:08 [Server] INFO org.bukkit.plugin.SimplePluginManager.recalculatePermissionDefaults(SimplePluginManager.java:623)
08.02 11:23:08 [Server] INFO org.bukkit.permissions.Permission.recalculatePermissibles(Permission.java:165)
08.02 11:23:08 [Server] INFO org.bukkit.permissions.Permission.addParent(Permission.java:206)
08.02 11:23:08 [Server] INFO fr.neatmonster.nocheatplus.permissions.PermissionUtil.addChildPermissionBySuffix(PermissionUtil.java:250)
08.02 11:23:08 [Server] INFO fr.neatmonster.nocheatplus.NoCheatPlus.postEnable(NoCheatPlus.java:1109)
08.02 11:23:08 [Server] INFO fr.neatmonster.nocheatplus.NoCheatPlus$PostEnableTask.run(NoCheatPlus.java:257)
08.02 11:23:08 [Server] INFO org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
08.02 11:23:08 [Server] INFO org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
08.02 11:23:08 [Server] INFO net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730)
08.02 11:23:08 [Server] INFO net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
08.02 11:23:08 [Server] INFO net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
08.02 11:23:08 [Server] INFO net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
08.02 11:23:08 [Server] INFO java.lang.Thread.run(Thread.java:745

**Comment by MarkElf** [comment]
Error identical or similar to issue #379; the error likely doesn't have anything to do with CMI.

**Comment by CloudeLecaw** [comment]
Hello MarkElf,
Sometime im realy blind :§
I told Cittrus to report here on hithub but didnt saw that this post is from him ;)
So the user i meant allready posted in [#379](https://github.com/NoCheatPlus/Issues/issues/379)

**Comment by asofold** [comment]
Closing as dupölicate of Ticket https://github.com/NoCheatPlus/Issues/issues/379 .
