### ISSUE TITLE
Elytra freezing on creative

### ISSUE THREAD

**Issue by SecretlyJealous** [NoCheatPlus/Issues#382]
I've been having crashes like this: https://hastebin.com/ibasaxerer.md which seem to be related to speed. I want to use NoCheatPlus for the speed limiter feature it has but for some reason it messes up flying with elytra's on creative. No matter how much I mess around with the values in the config file I can't fix the elytra freezing when people are flying with it. Not sure if I'm doing something wrong or if it is just a bug but here's what the config for it looks like: https://hastebin.com/ulokikadit.cpp
Using build: 1064

**Comment by Platinteufel** [comment]
#266

**Comment by asofold** [comment]
The creative flying model is more lenient in terms of where you can move to, so to mitigate the issue temporarily, you could increase the allowed speeds  -  however at the risk of creative mode players flying at those speeds with a cheat client all the time.

**Comment by asofold** [comment]
Is this fixed with build 1066? Let's regard edge cases in a different ticket (such as shortly touching water/vines: https://github.com/NoCheatPlus/Issues/issues/346).

**Comment by asofold** [comment]
Assume fixed for the basic part.
