### ISSUE TITLE
Can't Move When Slowed Down

### ISSUE THREAD

**Issue by TheNoodleMan** [NoCheatPlus/Issues#384]
Running Spigot 1.11.0, using a plugin called "PlayerWeight" that slows-down players depending on how many items they have. Problem is, it's incredibly buggy when they drop below 100% speed. They rubberband while jumping, or can't move at all.

Plugins In Interest?:
-NoCheatPlus
-CompatNoCheatPlus
-ProtocolLib
-mcMMO
-PlayerWeight
-PermissionsEX
-Essentials

I've tried changing multiple different settings in the config. Disabling SurvivalFly fixes it, but I'd rather not disable it entirely. Forgive me if the fix is really easy, I can be blind sometimes.

I get the regular "Player tried SurvivalFly" error messages. Here's the SurvivalFly config:
    survivalfly:
      active: true
      extended:
        vertical-accounting: true
      stepheight: default
      hbufmax: 4.0
      setbackpolicy:
        falldamage: true
        voidtovoid: true
      actions: log:flyshort:3:10:f cancel vl>100 log:flyshort:0:10:if cancel vl>400 log:flylong:0:5:cif cancel vl>1500 log:flylong:0:5:cif cancel cmd:kickfly
      hover:
        active: true
        step: 5
        ticks: 85
        loginticks: 60
        falldamage: true
        sfviolation: 500

Thanks in advance!

**Comment by CaptainObvious0** [comment]
#42

**Comment by asofold** [comment]
Concerning ArmorWeight, it's an existing ticket: https://github.com/NoCheatPlus/Issues/issues/144 :), which already might be a duplicate.

To be fair, lowering walk speed by attributes is another thing than the ordinary walk speed setting, i assume the plugin is using attributes.

**Comment by asofold** [comment]
Does it work with build 1065 ?

**Comment by TheNoodleMan** [comment]
Yep, flawlessly! (So far) Using Build #1066 and it seems to be all good, thank you!

**Comment by asofold** [comment]
Thank oyu for the feedback - i will close this as fixed then. For balancing and/or prevent abuse, perhaps more will be necessary, though we just allow Ardinary sprinting speed when slowed down and officially sprinting, so at least it is limiting by the food level. If issues arise/persist, feel free to comment here or open a new ticket.
