### ISSUE TITLE
Some useful checks (Movement, Combat)

### ISSUE THREAD

**Issue by v0idst4r** [NoCheatPlus/Issues#385]
Prevent the player from sneaking/unsneaking too quickly. Most if not all sneak cheats work by sending a stop sneaking packet, sending the player updates then sending a start sneaking packet.

Prevent the player from moving their full walking speed while using an item. In a vanilla client your speed is multiplied by 0.2 when using an item. Also maybe cut the player some slack when they first start using the item to prevent false positives.

Prevent the player from hitting entities they can't actually see. When a player is behind a wall and the entity is on the other side for example.

Prevent the player from moving down faster than normal. This will possibly patch reverse step and some speed methods.

**Comment by asofold** [comment]
Sneak+unsneak or unsneak+action+sneak are hot topics too.

"While using an item" <- this is client side for most. We just receive "right clicked item" and then "item consumed". So in this case we can only look back, how the player has been moving. This isn't out of reach either, we even have built in capabilities to monitor (potentially arbitrarily many) past moves in detail, including information about side conditions, such as ground, liquid, velocity use, and other.

Prevent hitting through walls is another interesting topic that we should add. We do have some infrastructure we could rely on.

Moving down faster than normal? This is not meant to be fast falling (should be caught to some extent)? Could you give more context for what they're doing?

**Comment by v0idst4r** [comment]
Fast falling as in a player setting their motionY to -1

**Comment by jonesdj1** [comment]
yes this allows people to step down blocks instantly but only works for 1 blocks or something

**Comment by v0idst4r** [comment]
It works for as many blocks as you want, it can also be used for speeds

**Comment by asofold** [comment]
I still can't disambiguate 100% :), so for moving down, which one applies, A or B?

A)

X
XX
XXX
XXXX
XXXXX
XXXXXX

B)

X
X
X
X
X
XXXXXX

**Comment by jonesdj1** [comment]
you cant just teleport down 10 blocks

**Comment by CaptainObvious0** [comment]
It would be option A. The current step bypass allows the user to step, just at a slower pace.

**Comment by v0idst4r** [comment]
A, but you can teleport down up and down 0.4 which is how most speeds work

On Feb 24, 2017 10:37 PM, "jonesdj1" <notifications@github.com> wrote:

you cant just teleport down 10 blocks

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/NoCheatPlus/Issues/issues/385#issuecomment-282459538>,
or mute the thread

**Comment by jonesdj1** [comment]
@v0idst4r that is known would not be a thing still if he dident just put a bandage over the bhop/yport fix survival fly check needs a redo tbh or at-least fully fixing bhop and yport

**Comment by asofold** [comment]
You can jump 0.42 upwards for an initial gain value, usually :), wouldn't call that teleporting.

0.4 Downwards ~ this really depends on the context, with 0.5 high blocks a lot used to be possible, perhaps rather short term, and these cheats optimize to stay as much on ground as possible for maximum (horizontal) gain.

It probably needs some reference data (debug logs), under which conditions you can or can not move down more than gravity commands, for the first descending move. It could also be that there is a special case abused, such do exist (can't recall right now, but there can be oddities like y-distance inversion on the high slope, thus something like 0.4 -> -0,4), in which case we'll need to nail down side conditions better, e.g. using past move tracking, or perhaps we can patch it up with a mid term monitoring.

Example would be the special case resetting with being on ground, but moving 0.4 up and down in succession is not the intended use of that workaround, so you could count setting "low jump" for a short/mid-term duration and trigger another sub-check if too high. Best would be a debug log, as workaround use should get logged.

**Comment by v0idst4r** [comment]
Nice

On Feb 25, 2017 5:48 PM, "asofold" <notifications@github.com> wrote:

You can jump 0.42 upwards for an initial gain value, usually :), wouldn't
call that teleporting.

0.4 Downwards ~ this really depends on the context, with 0.5 high blocks a
lot used to be possible, perhaps rather short term, and these cheats
optimize to stay as much on ground as possible for maximum (horizontal)
gain.

It probably needs some reference data (debug logs), under which conditions
you can or can not move down more than gravity commands, for the first
descending move. It could also be that there is a special case abused, such
do exist (can't recall right now, but there can be oddities like y-distance
inversion on the high slope, thus something like 0.4 -> -0,4), in which
case we'll need to nail down side conditions better, e.g. using past move
tracking, or perhaps we can patch it up with a mid term monitoring.

Example would be the special case resetting with being on ground, but
moving 0.4 up and down in succession is not the intended use of that
workaround, so you could count setting "low jump" for a short/mid-term
duration and trigger another sub-check if too high. Best would be a debug
log, as workaround use should get logged.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/NoCheatPlus/Issues/issues/385#issuecomment-282521270>,
or mute the thread

**Comment by asofold** [comment]
Misinterpreting the debug log in ticket 369, i think the too fast stepping / height change may could be tracked efficiently with the past move tracking. This way we're able to distinguish cases, and we'd have the choice of triggering stuff, e.g. a penalty action to increase the improbable level, to make another step further with (potentially) fixing something like this.

**Comment by asofold** [comment]
Closing in favor of individual tickets for remaining issues/enhancements.
