### ISSUE TITLE
I cannot change the messages or figure out the source of them! PLEASE Help me as soon as possible.

### ISSUE THREAD

**Issue by bitnibbles** [NoCheatPlus/Issues#386]
So today i was trying to change the flag messages as such "Hey! Sorry, but you can't build here!" and things like that... I was looking through the codes but I couldnt find the source for the messages. I looked everywhere and spent 3 hours trying to find them. Nothing! Please tell me how to modify the messages. ~bitnibbles

**Comment by jonesdj1** [comment]
@bitnibbles this has nothing todo with nocheatplus if you where smart you would know it was worldguard after all it is your server.

**Comment by asofold** [comment]
The build message should be WorldGuard or a similar plugin (region protection) - are there other messages you want to change, related to cheating? 

Some messages in NCP can't yet be customized, so one of those could still be on your list.

**Comment by bitnibbles** [comment]
@asofold i meant worldguard, sorry please tell me how if you know :P

**Comment by asofold** [comment]
@bitnibbles You're best off checking the worldguard (and for some cases worldedit) configuration files... also check their official wiki and perhaps irc?
