### ISSUE TITLE
Switching field in hotbar delays hitting

### ISSUE THREAD

**Issue by Johandrex** [NoCheatPlus/Issues#387]
If PLAYER1 scrolls in his hotbar he's unable to hit PLAYER2 for around 0,5-1 seconds, this must be fixed as it's essentials to have a working pvp for kit pvp servers. When installing a much older NoCheatPlus version or completely removing NCP it fixes the issue.

This issue occurs on both 1.8.8 & 1.11.2 servers (tested multipled times)
Server running 1.8.8: https://fnpaste.com/DoM9
Server running 1.11.2: https://fnpaste.com/qYyn

You may see the issue in action here - https://www.youtube.com/watch?v=rkgl6rjL0gU&feature=youtu.be
I've removed NoCheatPlus after 0:20 in the video, pvp works fine.

I've also attempted to set everything in the NoCheatPlus configuration to "false", but the issue still persists. Kindly fix ASAP.

**Comment by MarkElf** [comment]
You can lower the value of tool penalty to resolve your issue, it should be 500 by default or .5 seconds.

**Comment by asofold** [comment]
Yes, the toolchangepenalty is the issue here (for most, there may be other penalty time settings kicking in on occasion): _checks.fight.toolchangepenalty_  set in milliseconds, with 500 as the default value.

**Comment by Johandrex** [comment]
Alright seems to be working now thanks.

**Comment by asofold** [comment]
500 ms perhaps is not a good default value ...
