### ISSUE TITLE
Rubberbanding in vanilla circumstances

### ISSUE THREAD

**Issue by polkovnikov-ph** [NoCheatPlus/Issues#391]
When running and jumping of top of ice and trapdoors with speed II beacon, NCP declines to admit movement as valid.

I'm not an owner of the server. NCP is the only installed plugin.

**Comment by MarkElf** [comment]
Hi, 

Without the output of /ncp version, I can only assume that the server that you are referring is running an outdated version of ncp as a very similar issue was resolved quite some time ago. Have them install the latest development build from Jenkins and attempt to reproduce the issue. 

https://ci.md-5.net/job/NoCheatPlus/lastSuccessfulBuild/artifact/target/NoCheatPlus.jar

**Comment by polkovnikov-ph** [comment]
@MarkElf Thanks, that's probably the case.
