### ISSUE TITLE
Duplication Glitch

### ISSUE THREAD

**Issue by FirstReplay** [NoCheatPlus/Issues#395]
#### Short description of the issue.
Ability to duplicate any item in the chest of a Donkey

#### Server ####  
git-Paper-1063 MC: 1.11.2 
detected: 1.11.2
#### NoCheatPlus ####
Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1066
MCAccess: 1.11-1.11.2 / Spigot-CB-1.11_R1
Features:
blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11
checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
defaults: pvpKnockBackVelocity
packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
Hooks: AllViolations NCP 1.0
#### Related Plugins ####
ProtocolLib v4.2.1-SNAPSHOT-b348

#### How to reproduce the issue (is it random / always happens / side conditions)?

1. Create a nether portal. On the nether side put a cactus one block high.
2. Tame a donkey. Place a saddle on the donkey. Place a chest on the donkey.
3. Place items in the donkey's chest.
4. Hit the donkey until it has 1/2 a heart left.
5. Ride donkey into the nether portal and hop off.
6. Donkey will die dropping items and in the process duplicating them.

#### Have you made any (noteworthy) changes to the default configuration of NCP?
None

Video: https://youtu.be/xC1GvN8UwrA?t=2612

**Comment by Chnkr** [comment]
This is a paperspigot issue.
