### ISSUE TITLE
NCP kicking for standing still.

### ISSUE THREAD

**Issue by DK-Theodor200** [NoCheatPlus/Issues#396]
#### 
20.03 15:54:56 [Server] INFO [NoCheatPlus] xAimeeMarie failed SurvivalFly: tried to move from -7547.43, 64.88, 48407.43 to -7547.43, 64.88, 48407.39 over a distance of **0.04** block(s). VL 150.
20.03 15:55:05 [Server] INFO xAimeeMarie > Then i get stuck on this
20.03 15:55:12 [Server] INFO xAimeeMarie > Soon it will start kicking me off
20.03 15:55:13 [Server] INFO [NoCheatPlus] xAimeeMarie failed SurvivalFly: tried to move from -7547.43, 64.88, 48407.45 to -7547.43, 64.88, 48407.45 over a distance of **0.00** block(s). VL 368.
20.03 15:55:18 [Server] INFO [NoCheatPlus] xAimeeMarie failed SurvivalFly: tried to move from -7547.42, 64.88, 48407.39 to -7547.51, 64.88, 48407.34 over a distance of **0.10** block(s). VL 548.
20.03 15:55:23 [Server] INFO [NoCheatPlus] xAimeeMarie failed SurvivalFly: tried to move from -7547.42, 64.88, 48407.39 to -7547.40, 64.88, 48407.26 over a distance of **0.13** block(s). VL 774.

#### Happens kinda random, when people teleport, log in etc.
But can be reproduced by standing on a chest and opening it, thats the text ive pasted above.

#### Have you made any (noteworthy) changes to the default configuration of NCP?
No. but I want it to be less strict

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
Nope

#### Provide additional information, such as error/debug/violation logs. (For reproducible issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) Use GitHub gists or http://pastebin.com/ or similar for huge logs, or attach a (zip-) file here. For image uploads, please prefer a site that allows viewing without JavaScript, you can upload file attachments for issues right here.

I want to make the config, so it becomes less strict and only kicks if people are really obviously hacking.

**Comment by DK-Theodor200** [comment]
Can the config be changed, so it only takes action, if its over a distance for 5 blocks or something like that?

**Comment by MarkElf** [comment]
Output of /ncp version? 

I can guarantee you're running an outdated version of ncp on a 1.9+ server or have a conflicting plugin. 

https://ci.md-5.net/job/NoCheatPlus/

**Comment by DK-Theodor200** [comment]
![image](https://cloud.githubusercontent.com/assets/26546749/24114577/0edb4b10-0da1-11e7-8fef-52b486260edd.png)

just installed it

**Comment by DK-Theodor200** [comment]
Paths are unwalkable, and if you run on top of a check you are kicked for flying. I barely have any plugins, Its a semi-vanilla server

**Comment by DK-Theodor200** [comment]
Thank you, bukkit was redirecting to the old version, THANK YOU
