### ISSUE TITLE
Cant Walk on Non-Solid Blocks

### ISSUE THREAD

**Issue by EcoExe** [NoCheatPlus/Issues#397]
I've downloaded NCP for my server to reduce the impact of hackers but now no players can walk on blocks such as tilled soil or path blocks and can't walk through doors, it just lags them back or kicks them for flying. i'm not sure where the problem is I've looked through the config.yml folder and can't see anything on there

**Comment by jonesdj1** [comment]
Update NoCheatPlus to a dev build here http://ci.md-5.net/job/NoCheatPlus/ as this just sounds like a outdated version.

**Comment by EcoExe** [comment]
Thanks its working now
