### ISSUE TITLE
Add inventory opened check [DBO 254]

### ISSUE THREAD

**Issue by MyPictures** [NoCheatPlus/Issues#4]
If the Inventory of a Player is not opened, don´t let him move items in his inventory (execlude HotBar of course).

--> Add to Inventory FastClick?

**Comment by MyPictures** [comment]
"We could though detect inconsistent behavior, like (active!) moving with managing items in a too fast or irregular/unlikely sequence." -asofold

**Comment by MyPictures** [comment]
"We could though detect inconsistent behavior, like (active!) moving with managing items in a too fast or irregular/unlikely sequence." -asofold

**Comment by MyPictures** [comment]
asofold: "This might be coming indirectly, because against autosoup type hacks it might make sense to also account for inventory opening and combine it with fastclick to either improbable directly or another accumulation thing like improbable."

**Comment by MyPictures** [comment]
asofold: "Technically we can't know if the player has the inventory open or not, because the client doesn't seem to tell, simply.

This could only be done for container-inventories. For the player inventory we might need to detect strange behavior in another way (spot unlikely event sequences, which slots are items moved from/to how quickly, meta conditions and triggers)."

**Comment by MyPictures** [comment]
asofold: "We could though detect inconsistent behavior, like (active!) moving with managing items in a too fast or irregular/unlikely sequence."

**Comment by MyPictures** [comment]
MyPictures: "https://www.spigotmc.org/threads/security-force-close-inventorys-on-impossible-player-actions.3555/"

**Comment by asofold** [comment]
Closing as superseded / postponed. In-medium speed tracking and past move tracking may be used to catch stuff like this.
