### ISSUE TITLE
Latest NCP

### ISSUE THREAD

**Issue by yodabosten** [NoCheatPlus/Issues#400]
Wo i can download the latest NCP?

**Comment by asofold** [comment]
Currently here: http://ci.md-5.net/job/NoCheatPlus/

Experiments are marked with [BLEEDING] or [INSTABLE], after a while people will use it and it's probably safe to use. Usually i'd have a release up, but things have been too shifty recently, so i can't get around the QA stuff. Likely i'll upload the current state as release soon-ish and see what happens. So currently the jenkins is the location to go. Note the links to the jenkins change list, the build-infos and for MC version overview: notable builds, found there.

**Comment by asofold** [comment]
Assume resolved.
