### ISSUE TITLE
Does not allow to move

### ISSUE THREAD

**Issue by Skilzar** [NoCheatPlus/Issues#402]
#### Short description of the issue.

Hello! :)
After it was updated from NCP 1066 to NCP 1067, a hang-up problem started after teleportation.
For example, I wrote /spawn and I teleported to spawn and did not let me move. In the console writes:
03.04 11:28:38 [Server] INFO (CONSOLE) Kicked rockyro : Kicked for flying (or related)
03.04 11:28:38 [Server] WARN handleDisconnection() called twice
03.04 11:28:38 [Disconnect] User rockyro has disconnected, reason: Kicked for flying (or related)
03.04 11:28:38 [Server] INFO rockyro failed SurvivalFly: tried to move: -169.53, 75.00, 496.87 -> -169.52, 75.00, 495.52, d=1.36 (permchecks+hbufuse+hspeed). VL 1551.
03.04 11:28:36 [Server] INFO rockyro failed SurvivalFly: tried to move: -169.53, 75.00, 496.87 -> -169.52, 75.00, 495.52, d=1.36 (permchecks+hspeed). VL 405.

#### Server ####
git-Spigot-21fe707-e1ebe52 ~MC: 1.8.8~
  detected: 1.8.8
#### NoCheatPlus ####
Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1067
MCAccess: 1.8.4-1.8.8 / Spigot-CB-1.8_R3
Features:
  blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
  checks: FastConsume | Gutenberg
  defaults: pvpKnockBackVelocity
Hooks: AllViolations~NCP~ 1.0
#### Related Plugins ####
ProtocolLib v4.1.0

#### How to reproduce the issue (is it random / always happens / side conditions)?

Random

#### Have you made any (noteworthy) changes to the default configuration of NCP?

Default

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?

ViaVersion

**Comment by asofold** [comment]
* Once this happens (without kick, possibly just waiting?), can you move after a while, or do you stay frozen forever?
* Which client versions are known to cause or not cause issues? 1.11.2 / 1.8.9 / ?

**Comment by Skilzar** [comment]
1) It is necessary to wait a while and then it will be possible to go. I can make a video if necessary.
2) I've been playing since version 1.8.9

**Comment by asofold** [comment]
If you can reliably reproduce it, it would be really good to have an on-the-fly debug log (see: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players).

That would help fastest. I'll try to reproduce or trackit down, but likely this is related to using a remote server with some latency.

**Comment by Skilzar** [comment]
Sorry, I did not understand how to make a debug.
I'm writing /ncp debug player and nothing happens.
I decided again to go to a random place and I have a file nocheatplus.log

17-04-04 08:38:36 [INFO] Skilzar failed CreativeFly: tried to move: 1354.50, 72.00, 1282.93 -> 1354.50, 72.00, 1281.50, d=1.43 (hfrict+hdist). VL 168.
17-04-04 08:38:37 [INFO] Skilzar failed CreativeFly: tried to move: 1354.50, 72.00, 1282.97 -> 1354.50, 72.00, 1281.50, d=1.47 (hdist). VL 459.
17-04-04 08:38:42 [INFO] Skilzar failed CreativeFly: tried to move: 1354.50, 72.00, 1282.97 -> 1354.50, 72.00, 1281.50, d=1.47 (hdist). VL 2814.
17-04-04 08:38:47 [INFO] Skilzar failed CreativeFly: tried to move: 1354.50, 72.00, 1282.97 -> 1354.50, 72.00, 1281.50, d=1.47 (hdist). VL 5683.
17-04-04 08:38:52 [INFO] Skilzar failed CreativeFly: tried to move: 1354.50, 72.00, 1282.97 -> 1354.50, 72.00, 1281.50, d=1.47 (hdist). VL 8291.
17-04-04 08:38:57 [INFO] Skilzar failed CreativeFly: tried to move: 1354.50, 72.00, 1282.97 -> 1354.50, 72.00, 1281.50, d=1.47 (hdist). VL 11160.
17-04-04 08:39:02 [INFO] Skilzar failed CreativeFly: tried to move: 1354.50, 72.00, 1282.97 -> 1354.50, 72.00, 1281.50, d=1.47 (hdist). VL 14029.
17-04-04 08:39:07 [INFO] Skilzar failed CreativeFly: tried to move: 1354.50, 72.00, 1282.97 -> 1354.50, 72.00, 1281.50, d=1.47 (hdist). VL 16290.
17-04-04 08:39:12 [INFO] Skilzar failed CreativeFly: tried to move: 1354.50, 72.00, 1282.97 -> 1354.50, 72.00, 1281.50, d=1.47 (hdist). VL 19159.
17-04-04 08:39:17 [INFO] Skilzar failed CreativeFly: tried to move: 1354.50, 72.00, 1282.97 -> 1354.50, 72.00, 1281.50, d=1.47 (hdist). VL 22027.
17-04-04 08:39:22 [INFO] Skilzar failed CreativeFly: tried to move: 1354.50, 72.00, 1282.97 -> 1354.50, 72.00, 1281.50, d=1.47 (hdist). VL 24462.
17-04-04 08:39:27 [INFO] Skilzar failed CreativeFly: tried to move: 1354.50, 72.00, 1282.97 -> 1354.50, 72.00, 1281.50, d=1.47 (hdist). VL 27331.
17-04-04 08:39:32 [INFO] Skilzar failed CreativeFly: tried to move: 1354.50, 72.00, 1282.97 -> 1354.50, 72.00, 1281.50, d=1.47 (hdist). VL 30200.
17-04-04 08:39:37 [INFO] Skilzar failed CreativeFly: tried to move: 1354.50, 72.00, 1282.97 -> 1354.50, 72.00, 1281.50, d=1.47 (hdist). VL 32634.
17-04-04 08:39:42 [INFO] Skilzar failed CreativeFly: tried to move: 1354.50, 72.00, 1282.97 -> 1354.50, 72.00, 1281.50, d=1.47 (hdist). VL 35503.
17-04-04 08:39:47 [INFO] Skilzar failed CreativeFly: tried to move: 1354.50, 72.00, 1282.97 -> 1354.50, 72.00, 1281.50, d=1.47 (hdist). VL 38372.
17-04-04 08:39:52 [INFO] Skilzar failed CreativeFly: tried to move: 1354.50, 72.00, 1282.97 -> 1354.50, 72.00, 1281.50, d=1.47 (hdist). VL 40719.
17-04-04 08:39:57 [INFO] Skilzar failed CreativeFly: tried to move: 1354.50, 72.00, 1282.97 -> 1354.50, 72.00, 1281.50, d=1.47 (hdist). VL 43588.
17-04-04 08:40:02 [INFO] Skilzar failed CreativeFly: tried to move: 1354.50, 72.00, 1282.97 -> 1354.50, 72.00, 1281.50, d=1.47 (hdist). VL 46457.

Then I could move again

**Comment by asofold** [comment]
* That log is with being in creative mode (or flying activated)? At least the check meant for flying is running, but that's interesting too, because you don't get kicked so quickly.
* Is the spawn special in any way (blocks used / position / teleportation disabled) ? Is the actual spawn location inside of blocks?

To do the debug logging:
1. Ensure to not be op / creative mode / have bypass permissions for moving / survivalfly.
2. Run the command _/ncp debug Skilzar_  in case the player named Skilzar is testing.
3. Reproduce the issue (e.g. get kicked).
4. Ensure debug logging is deactivated via '/ncp  remove Skilzar' or 'ncp reload'.

The output would be quite large, but it's better not to cut off too much, we always need context from before the teleport/violation, so perhaps make a zipped file or a gist and upload here directly (blue dashed line below a comment).

The above log already gives me some idea, but the fastest way to a fix typically is a full debug log, so that's much desirable from my side.

**Comment by Skilzar** [comment]
For example, I use the / tpr command for a random teleport to a random position.
If in survival mode, then in the big case you can freeze.
If fly or gamemode is on, but you are on the ground, you can also freeze. If you teleport in flight, then it's rare to freeze.

Attached a video for an example, where without creative and fly: https://youtu.be/TwE_CectnIk
And here are the logs when the video froze:
17-04-04 13:49:00 [INFO] BinionGirl failed Passable: moved into a block (2) from 2891.50, 75.00, 2973.50 to 2891.50, 74.90, 2973.50 distance 0.10 . VL 10.
17-04-04 13:49:05 [INFO] BinionGirl failed Passable: moved into a block (2) from 2891.50, 75.00, 2973.50 to 2891.50, 74.90, 2973.50 distance 0.10 . VL 42.
17-04-04 13:49:05 [INFO] BinionGirl failed Passable: moved into a block (2) from 2891.50, 75.00, 2973.50 to 2891.50, 74.90, 2973.50 distance 0.10 . VL 50.
17-04-04 13:49:10 [INFO] BinionGirl failed Passable: moved into a block (2) from 2891.50, 75.00, 2973.50 to 2891.50, 74.71, 2973.50 distance 0.29 . VL 72.

An example of a video when I find myself in the air and teleported in a random place: https://youtu.be/8uGPa_NhehM
Without freezing, everything is basically good.

I do not have an OP.

I test anti-cheat on a test server, then in fact for an individual player debug does not need to include?

**Comment by asofold** [comment]
I don't see much unusual in the video - you are "frozen" for a split second? The passable check should be ok, it has to prevent those 0.1-downwards moves, because they're not "real" (sent by the client to prevent the server kicking them for floating too long while rendering the chunks), especially for world changing or long range teleport.

The debug log is very detailed and contains properties of nearby blocks, all sorts of internal bookkeeping - for finding bugs with moving checks it's the fastest thing, really (no 100% guarantee, though). Most moving-related bugs get resolved quickly once debug logs are there. This would be very good to have for the survivalfly+kicking issue.

I'll try tp reproduce this too, but i can't guarantee i'll have the same plugins and side conditions - i've been expecting bugs like this with the recent changes, but i still need to find a fix...

**Comment by asofold** [comment]
I couldn't reproduce the (survivalfly/kicking) issue yet. Build 1072 might improve things on that account (a little bit of speculation).

**Comment by Skilzar** [comment]
Updated to version NCP 1072.
The problem with tilting back remains.
For a random teleport, you can use, for example, a plugin https://dev.bukkit.org/projects/randomplacer/files/684951

**Comment by asofold** [comment]
It would be good to know if the kicking or higher violations reached after teleporting remain, or if those are gone. This'll probably need waiting/testing for a bit, to be sure.

If you're held back for a short moment (depending on the round trip time rather), then this is rather to be expected. Should that still be "too much", we should try to estimate what the difference is to not having NCP check the player. You can temporarily exempt yourself from all checks via 'ncp exempt Skilzar' and then 'ncp unexempt Skilzar' for comparison, to measure a difference.

If you want to measure from teleport towards when you can move off the spot freely, you could prepare the commands 'ncp sw start' and 'ncp sw stop' for a stopwatch functionality.

**Comment by asofold** [comment]
Build 1073 might improve things here.

**Comment by Skilzar** [comment]
Thank you! The problem has disappeared.

**Comment by asofold** [comment]
Are issues really gone / back to before, evaluating after some time?

That'd be really interesting, as we have some people who still have issues, one with reduced issues (sounds like worse than before 1067 but better than just before).

We have combinations of Spigot/TacoSpigot  MC versions 1.7.10 / 1.8.9 / 1.11.2, ViaVersion and Bungeecord in use. 

So if issues are back to normal, we'd have something like Spigot 1.8.8 + ViaVersion working 'ok'.

**Comment by Skilzar** [comment]
Build 1076 also works well

**Comment by asofold** [comment]
Alright, thank you for the feedback.

I'll close the ticket as fixed then - false positives in general will also be attempted to fix, but such always needs someone who can reliably reproduce them, so/or to get a debug log done.

**Comment by Skilzar** [comment]
[nocheatplus.log.zip](https://github.com/NoCheatPlus/Issues/files/908200/nocheatplus.log.zip)
Debug how quickly put the blocks under him

**Comment by Skilzar** [comment]
Please consider the question # 369

**Comment by asofold** [comment]
I get notified anyway :).
