### ISSUE TITLE
Able to fully disable vehicle checks.

### ISSUE THREAD

**Issue by lbjdaking23** [NoCheatPlus/Issues#405]
I would like a way to fully disable vehicle checks. I don't see a way to do that right now?
Right now the vehicle checks conflict with a plugin I am using for chairs which just teleports and sits a player on a arrow.
If need be I can fix this on my end but I am unsure of the way to properly do that.

Also when I do said teleport and vehicle attach I get
`17-04-07 14:21:32 [WARNING] [MOVING_VEHICLE] [Clutch] Illegal coordinates on checkVehicleMove: from: null , to: null
17-04-07 14:21:32 [WARNING] [MOVING_VEHICLE] [Clutch] Unexpected teleport cause on vehicle set back: PLUGIN`

**Comment by asofold** [comment]
The "Unexpected teleport cause" warning means you're using an older version of NCP (not build 1074 or later), with a newer version of spigot.

Disabling the vehicle checks should be possible via the 'enabled' flags in the configuration (checks.moving.vehicle sub sections). I would suggest to only alter/disable what's causing issues, though.

To resolve issues, probably some analysis would be needed. The above log indicates that there fire events with no locations set, which is a bit problematic to have. For arrows, i'm probably able to add something swiftly, so you needn't disable anything.

**Comment by lbjdaking23** [comment]
Thanks for the swift reply. 
I am using build 1074 with a older spigot for Minecraft 1.8.8. 
Location wise they are getting teleported to the arrow and getting set to the passenger right after which then in turn just kicks them off the arrow with those logs.
If we could have it disabled only for arrows that would be lovely :)

**Comment by asofold** [comment]
Build 1075 contains a fix attempt. Took a little longer than intended, because i stumbled over a couple of other things on the way.

**Comment by lbjdaking23** [comment]
Wow that was really fast. Will test it when I get home later. Thanks a lot! :)

**Comment by lbjdaking23** [comment]
Works perfect 10/10 Thanks :)

**Comment by asofold** [comment]
Ok :), drop a note here or open a new ticket, if issues persist/evolve. Closing as fixed.
