### ISSUE TITLE
Speed Bypasses

### ISSUE THREAD

**Issue by RowinHere** [NoCheatPlus/Issues#414]
**Short description of the issue.**
There are some speed bypasses

**Complete output of the _ncp version_ command (please prefer text here).**
---- Version information ----
#### Server ####
git-PaperSpigot-"8b18730" ~MC: 1.8.8~
detected: 1.8.8
#### NoCheatPlus ####
Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1081
MCAccess: 1.8.4-1.8.8 / Spigot-CB-1.8_R3
Features:
blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
checks: FastConsume | Gutenberg
defaults: pvpKnockBackVelocity
Hooks: AllViolations~NCP~ 1.0
#### Related Plugins ####
ProtocolLib v4.2.1

**Have you made any (noteworthy) changes to the default configuration of NCP?**
No, I used the default NCP configuration.

**Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?**
Nope.

**Provide additional information, such as error/debug/violation logs. (For reproducible issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) Use GitHub gists or http://pastebin.com/ or similar for huge logs, or attach a (zip-) file here. For image uploads, please prefer a site that allows viewing without JavaScript, you can upload file attachments for issues right here.**
"SlowHow" and "Latest" are both fully working without getting detected.
"NCP" is sometimes getting picked up.

https://www.youtube.com/watch?v=vod2SQsKLKU&feature=youtu.be

**Comment by asofold** [comment]
Are you in control of testing the cheats?

There are two things that would be very interesting:
a) Use the 'ncp stopwatch distance 100' command and run 100 blocks straight with the cheat (for each cheat would be really good). This way we have a measure what this really does.
b) A debug log (https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) for a player using the cheat would of course help fixing it.

If such is not possible, could you roughly estimate how much faster than ordinary bunnyhopping they are (5% 10% , ...) ? Moving (almost only / seemingly) on ground also should be compared to bunny hopping, just for reference.

**Comment by RowinHere** [comment]
Command used: /ncp stopwatch distance 100

Legit bunny hopping: 00:00:14.3
SlowHop was 0.3 seconds faster so I don't care about that.
NCP was 2.1 seconds faster.
Latest: Same as NCP but you can't walk backwards or sidewards.

Not as fast as I thought they were.

**Comment by asofold** [comment]
Wow , thank you. Well 14% makes a difference, but it's probably not severe enough to start running in circles.

Of course there will be optimizations for special courses, e.g. with height differences, so one could still compare different kinds of side conditions - but that rather is extra to the ordinary speeding (e.g. larger fields of soul sand that should slow down players).

There'll come more refinements with sprint+jump logic, height difference vs. (past) moving directions and frequency of gaining/losing a block.

**Comment by asofold** [comment]
Closing as superseded in favor of a new INDEV issue.
