### ISSUE TITLE
Lower than default walkspeed (survivalfly) [DBO 828]

### ISSUE THREAD

**Issue by asofold** [NoCheatPlus/Issues#42]
Setting walk speed to lower than default poses problems (survivalfly set-backs).

The original ticket also includes potion effects, but those are to be handled in another ticket.

**Comment by asofold** [comment]
Details needed (whoever can do/debug): Walking vs. sprinting.

**Comment by MyPictures** [comment]
Didn't the original ticket also include negative jump potions?

**Comment by asofold** [comment]
Whatever, i tested lower than default walk speeds, and got set-back.

Need re-test, in order to see, if it's about jumping/sprinting rather than just moving on flat ground (i think it was moving normally on flat ground).

**Comment by BoFone** [comment]
I got the exactly same problem. I have armor weight enabled. So when players wearing heavier armor, they will get set-back when sprint-jumping.

**Comment by asofold** [comment]
Only on sprint+jump or also on waking simply?

**Comment by BoFone** [comment]
what do you mean by "waking simply"? do you mean "walking"?

If you meant by walking, then it's only on sprint+jump. and this is the plug-in that I used for armor weight.

http://dev.bukkit.org/bukkit-plugins/armorweight/

**Comment by asofold** [comment]
Sorry, i meant 'walking' of course. Might demand a special case similar to the one for higher level slowness potion effects (possibly the same special case).

**Comment by BoFone** [comment]
yeah, please try to delve into this problem. It seems like happened before in the previous versions?

**Comment by asofold** [comment]
This should be a problem at least since we support attributes. Might have a look this day.

**Comment by asofold** [comment]
Assume fixed/superseeded.
