### ISSUE TITLE
SurvivalFly // Craftbook (Elevator)

### ISSUE THREAD

**Issue by dweSheppard** [NoCheatPlus/Issues#420]
#### Short description of the issue.
If players are using a Craftbook lift sign, this will trigger a message about survivalfly.
NCP: [17:52:38] player.survivalfly VL 145  (n1a145m145)

#### Complete output of the _ncp version_ command (please prefer text here).
[17:56:56 INFO]: ---- Version information ----
[17:56:56 INFO]: #### Server ####
[17:56:56 INFO]: git-Spigot-b605b31-cf05ccc ~MC: 1.11.2~
[17:56:56 INFO]:   detected: 1.11.2
[17:56:56 INFO]: #### NoCheatPlus ####
[17:56:56 INFO]: Plugin: 3.15.1-RC-sMD5NET-b1084
[17:56:56 INFO]: MCAccess: 1.11-1.11.2 / Spigot-CB-1.11_R1
[17:56:56 INFO]: Features:
[17:56:56 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11
[17:56:56 INFO]:   checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[17:56:56 INFO]:   defaults: pvpKnockBackVelocity
[17:56:56 INFO]:   packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
[17:56:56 INFO]: Hooks: AllViolations~NCP~ 1.0 | Citizens2~cncp~ 2.0 | mcMMO~cncp~ 2.3
[17:56:56 INFO]: #### Related Plugins ####
[17:56:56 INFO]: CompatNoCheatPlus v6.6.4-RC-sMD5NET-b88 | ProtocolLib v4.2.0-SNAPSHOT-b332

#### How to reproduce the issue (is it random / always happens / side conditions)?
Using the Elevator-Sign from Craftbook.

#### Have you made any (noteworthy) changes to the default configuration of NCP?
No.

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
Craftbook, mcMMO

**Comment by asofold** [comment]
I have two questions to start with:
* Do you have a more detailed log message in the nocheatplus log file? (For the case the log file is used, and you're using the default actions, or something with [tags] contained in the strings entry.)
* Could you give more details, like is there specific directions involved, or distances? Up/Down/ short distances / long distances / all distances...

**Comment by dweSheppard** [comment]
I use the the default actions.
The error always occurs when I teleporting down.
In my example, I teleport 34 blocks down, but with smaller values 10-15 nothing happens.

Log:
17-04-21 20:26:52 [INFO] dweSheppard failed SurvivalFly: tried to move: 2020.61, 69.00, 850.88 -> 2020.62, 103.00, 850.93, d=34.00 (EXTREME_MOVE). VL 3400.
17-04-21 20:26:52 [INFO] (CONSOLE) Kicked dweSheppard : Kicked for flying (or related)

**Comment by asofold** [comment]
That looks good, so the 'extreme move' sub/pre-check triggered here.

Are there any compatibility settings with CraftBook that concern the lift feature, like 'use teleport' or so?

I tried to look up the source code, but so far i only found a repository where nothing of relevance seemed to be in (did it go private?)...

**Comment by dweSheppard** [comment]
Here is the debug log: https://pastebin.com/gWTuqQYN
On a response from the developer I am still waiting.

**Comment by asofold** [comment]
That's perfect - it looks like CraftBook is doing nothing odd here. Looks like a move is in the queue and _still gets processed_, despite the teleport.

17-04-22 16:34:35 [INFO] dweSheppard failed SurvivalFly: tried to move: 2020.61, 69.00, 850.56 -> 2020.60, 103.00, 850.22, d=34.00 (EXTREME_MOVE). VL 3400.

To Clarify: You teleported downwards once - like in this message, you used the sign around y-level 103 and expected to be at y-level 69 (roughly)?

**Comment by dweSheppard** [comment]
Yes, that's correct.

**Comment by asofold** [comment]
Ok - in theory there could be side conditions that make the event get through, or it's just always been this way, just no one has noticed (i've been using custom "lift" signs on my server back then (pre-1.7.10), and i don't really remember another issue pointing at this.

Anyway, i'll attempt to add in some leniency option. Ideally i'd just cancel out the packet via ProtocolLib, because it will have the smallest impact on everything, because if i cancel or alter Bukkit events, there will certainly result another teleport. One of the edges to consider with this, is that there can be players with higher latency, thus they'll be sending more moves before receiving the elevator-related teleport position.

Will need to have a look how to balance things here, because it likely needs passing information between the primary server thread (Bukkit moving events) and the packet level (extra networking threads), which complicates things slightly.

**Comment by asofold** [comment]
With ProtocolLib and NCP build 1090 this might be better/fixed (only for Spigot since the 'confirm teleport' packet exists.)
