### ISSUE TITLE
Flying in Creative Mode with Elytra causes Violation

### ISSUE THREAD

**Issue by CaptainObvious0** [NoCheatPlus/Issues#424]
#### Short description of the issue.
If flying with an elytra in creative mode, the player will be setback and flagged for CreativeFly

#### Complete output of the _ncp version_ command (please prefer text here).
[17:23:50 INFO]: ---- Version information ----
[17:23:50 INFO]: #### Server ####
[17:23:50 INFO]: git-Spigot-54ec0b8-7b044de ~MC: 1.11.2~
[17:23:50 INFO]:   detected: 1.11.2
[17:23:50 INFO]: #### NoCheatPlus ####
[17:23:50 INFO]: Plugin: 3.15.2-SNAPSHOT-sMD5NET-b1088
[17:23:50 INFO]: MCAccess: 1.11-1.11.2 / Spigot-CB-1.11_R1
[17:23:50 INFO]: Features:
[17:23:50 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11
[17:23:50 INFO]:   checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[17:23:50 INFO]:   defaults: pvpKnockBackVelocity
[17:23:50 INFO]:   packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | CatchAllAdapter
[17:23:50 INFO]: Hooks: AllViolations~NCP~ 1.0 | NPCDragDownHook | PNCP 1.2
[17:23:50 INFO]: #### Related Plugins ####
[17:23:50 INFO]: ProtocolLib v4.2.0

#### How to reproduce the issue (is it random / always happens / side conditions)?
Go high in the air, set yourself to creative mode, fly with an elytra.

#### Have you made any (noteworthy) changes to the default configuration of NCP?
None, Reproduced on default config

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
None

#### Provide additional information, such as error/debug/violation logs. (For reproducible issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) Use GitHub gists or http://pastebin.com/ or similar for huge logs, or attach a (zip-) file here. For image uploads, please prefer a site that allows viewing without JavaScript, you can upload file attachments for issues right here.
Debug: https://pastebin.com/PTFGn3LK

**Comment by asofold** [comment]
Might duplicate the elytra + gamemode 1 ticket - need to check further if this should supersede the other one.

The log shows that the player is checked via the default creative mode model, which if i am right is not intended - they should be checked by the elytra-specific model.

**Comment by Sitmobedaf** [comment]
I have the same problem. Please fix it.
Asofold, you still support this plugin?! Judging by the number of tickets, your efforts are not enough. Can you get helpers?

**Comment by asofold** [comment]
You can't only judge by the number of tickets :). We keep conceptual stuff open and don't close quickly. In fact MyPictures will help checking tickets, so there is not only one developer - and we close stuff in waves, not right away. We'll probably tag and close 'interesting but far off ones' or add them to a special projects view to be able to keep track of closed tickets, so it looks tidier. There just are some all-time topics, rare edge cases where someone needs to be able to reproduce, and with manpower restrictions i can't deal with all stuff at the same time, naturally creative mode + elytra is not the main focus, despite getting closer to a solution.

We're certainly lacking developers, but i'm also not too optimistic, more detail: https://gist.github.com/asofold/3c1fb425767ca7c56e87d2e3a1a0bded
(I'll update that a couple of times still...)

Edit: Note that NCP on BukkitDev had ca. 1000 closed tickets, and idk ~ 50 were taken over to here.

**Comment by asofold** [comment]
Might duplicate this ticket: https://github.com/NoCheatPlus/Issues/issues/266

Build 1093 contains a related fix - are you setting players to glide with a plugin? (Or is allowflight turned off?)

**Comment by asofold** [comment]
Assume fixed since build 1096.
