### ISSUE TITLE
Spectator mode bug

### ISSUE THREAD

**Issue by RikoDEV** [NoCheatPlus/Issues#436]
#### Short description of the issue.
When a player fly in the spectator mode too fast and wants to fly upwards it is canceled by the antycheat.
Player don't have any permissions.

#### Complete output of the _ncp version_ command (please prefer text here).
Latest NoCheatPlus
#### How to reproduce the issue (is it random / always happens / side conditions)?
Always happens

#### Have you made any (noteworthy) changes to the default configuration of NCP?
No
#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
No

**Comment by asofold** [comment]
Can't reproduce on MC 1.11.2. 
* Is this about speed rather or the flying height? There is a maxheight setting for the creativefly models.
* Is the creativefly configuration altered (general / model -> jetpack.elytra)?
* (Which version of Minecraft is it?)
* (Any other side conditions? Other plugins involved in moving/flying/elytra?)

**Comment by Platinteufel** [comment]
@asofold In Spectator mode you can change your speed by scrolling mousewheel. Haven't tested it yet. ;-)

**Comment by asofold** [comment]
I did test with that .... perhaps there is a way to reproduce this, but we should know more of the side conditions (plugins might be involved, effects  whatever...  Edit: or it is just the maxheight setting).

**Comment by MyPictures** [comment]
Could you provide a /ncp version output in this ticket? Would help me to rebuild your setup on my server and see if something happens.

**Comment by asofold** [comment]
Perhaps it also varies with the client version, thinking of ViaVersion/ProtocolSupport.

**Comment by RikoDEV** [comment]
[Server thread/INFO]: ---- Version information ----
 [Server thread/INFO]: #### Server ####
 [Server thread/INFO]: git-Paper-1094 ~MC: 1.11.2~
 [Server thread/INFO]: detected: 1.11.2
 [Server thread/INFO]: #### NoCheatPlus ####
 [Server thread/INFO]: Plugin: 3.15.2-SNAPSHOT-sMD5NET-b1089
 [Server thread/INFO]: MCAccess: 1.11-1.11.2 / Spigot-CB-1.11_R1
 [Server thread/INFO]: Features:
 [Server thread/INFO]: blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11
 [Server thread/INFO]: checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter
 [Server thread/INFO]: defaults: pvpKnockBackVelocity
 [Server thread/INFO]: Hooks: AllViolations~NCP~ 1.0

I speed by scrolling mousewheel.

**Comment by asofold** [comment]
@RikoDEV Do you any more details about the height at which this happens? Is it above the world build height?

**Comment by RikoDEV** [comment]
@asofold No.

**Comment by asofold** [comment]
So two paths remain:
* Someone reproduces this and adjusts the creativefly / spectator model setting so it works and tells us here what settings can be used.
* Someone reproduces this with debug logging on.

**Comment by Platinteufel** [comment]
@asofold I was just able to reproduce it with max spectator speed.


Video: https://youtu.be/YycgCmEe5S8

debug logs: [nocheatplus.zip](https://github.com/NoCheatPlus/Issues/files/976208/nocheatplus.zip)

**Comment by asofold** [comment]
Does increasing the ascend speed help for the spectator model?

**Comment by asofold** [comment]
Could reproduce - had a higher setting in the configuration for testing. The default value for the checks.moving.creativefly.model.spectator.horizontal.speed has been increased to 450 with build 1102. It still needs removing that entry and reloading the configuration or manual altering.

Does setting the horizontal speed for spectator to 450 resolve this issue?

Edit: Was testing with a different flyspeed setting - also needs increasing vertical ascend speed to about 170 - build 1103.

**Comment by MyPictures** [comment]
Reproduced with:
[19:26:38 INFO]: ---- Version information ----
[19:26:38 INFO]: #### Server ####
[19:26:38 INFO]: git-Spigot-3fb9445-2b6c9f4 ~MC: 1.11.2~
[19:26:38 INFO]:   detected: 1.11.2
[19:26:38 INFO]: #### NoCheatPlus ####
[19:26:38 INFO]: Plugin: 3.15.2-SNAPSHOT-sMD5NET-b1103
[19:26:38 INFO]: MCAccess: 1.11-1.11.2 / Spigot-CB-1.11_R1
[19:26:38 INFO]: Features:
[19:26:38 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11
[19:26:38 INFO]:   checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[19:26:38 INFO]:   defaults: pvpKnockBackVelocity
[19:26:38 INFO]:   packet-listeners: DebugAdapter | UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
[19:26:38 INFO]: Hooks: AllViolations~NCP~ 1.0 | TestNCPHook 1.0
[19:26:38 INFO]: #### Related Plugins ####
[19:26:38 INFO]: CompatNoCheatPlus v6.6.4-RC-sMD5NET-b88 | ProtocolLib v4.2.1

By going in spectator mode, using mouse wheel (up) to gain speed and fly upwards. Triggers CreativeFly check.

[CreativeFly(horizontal).zip](https://github.com/NoCheatPlus/Issues/files/981791/CreativeFly.horizontal.zip)

EDIT: I changed vertical speed of spectator to 170 and it works now.
