### ISSUE TITLE
 Jumping into a pool of lava triggers NoFall.

### ISSUE THREAD

**Issue by Lysandr0** [NoCheatPlus/Issues#439]
#### Short description of the issue.
The title is pretty self-explanatory, jumping into a pool of lava triggers NoFall.
https://i.gyazo.com/0776559714c7ea97813118cd043a8231.mp4

#### Complete output of the _ncp version_ command (please prefer text here).
---- Version information ----
[14:33:05 INFO]: #### Server ####
[14:33:05 INFO]: git-Spigot-3fb9445-fbb47e8 ~MC: 1.11.2~
[14:33:05 INFO]:   detected: 1.11.2
[14:33:05 INFO]: #### NoCheatPlus ####
[14:33:05 INFO]: Plugin: 3.15.2-SNAPSHOT-sMD5NET-b1097
[14:33:05 INFO]: MCAccess: 1.11-1.11.2 / Spigot-CB-1.11_R1
[14:33:05 INFO]: Features:
[14:33:05 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11
[14:33:05 INFO]:   checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[14:33:05 INFO]:   defaults: pvpKnockBackVelocity
[14:33:05 INFO]:   packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
[14:33:05 INFO]: Hooks: AllViolations~NCP~ 1.0
[14:33:05 INFO]: #### Related Plugins ####
[14:33:05 INFO]: ProtocolLib v4.2.1-SNAPSHOT-b353

#### How to reproduce the issue (is it random / always happens / side conditions)?
Always happens.

#### Have you made any (noteworthy) changes to the default configuration of NCP?
No.

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
No.

#### Provide additional information, such as error/debug/violation logs. (For reproducible issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) Use GitHub gists or http://pastebin.com/ or similar for huge logs, or attach a (zip-) file here. For image uploads, please prefer a site that allows viewing without JavaScript, you can upload file attachments for issues right here.

I can provide a debug log if needed / on request

**Comment by asofold** [comment]
Reproduced: It does seem to only trigger with actually falling onto ground through lava, so the pool can't be too deep.

Need to add some kind of exception to this, also the fall damage calculation somehow is a lot off (fall height about halfs with each move in lava, not sure servers really rely on such, technically we don't really monitor if they stop at touching the surface or dive regularly).

**Comment by MyPictures** [comment]
@asofold Doesn't Nofall recognize lava the same as water? It is a liquid that prevents fall damage.

**Comment by asofold** [comment]
@MyPictures Yes, which explains nofall setting fall distance to 0.0, howevere Minecraft about halfs fall distance by 2 with each move within lava (not reported for water, but would be worth debug logging) - currently nofall has a check for faked fall distance and it looks like this one triggers, if you go through lave (?/liquid) and hit the ground with sufficient vanilla fall distance remaining.

Edit: lol divides fall distance by 2 /etc.

**Comment by asofold** [comment]
Build 1100 contains a hot fix type of change, allowing fall damage in lava.

This might allow accumulating fall damage using a lava bucket (...) with fast place +pickup for getting one time fall damage (not sure if feasible). It also doesn't account for all thinkable related cases. 

Which past versions of MC also allow fall damage within lava could be tested with debug logging. Future changes should account for the fall damage halfing with each in-lava move and dealing damage inside lava.
