### ISSUE TITLE
1.8, Flying by using a bow (BowFly)

### ISSUE THREAD

**Issue by Lysandr0** [NoCheatPlus/Issues#448]
#### Short description of the issue.
Well... I really don't know how to explain that
Just watch the video: https://i.gyazo.com/320c6973fcc5dc9a623fd79837114f2e.mp4

#### Complete output of the _ncp version_ command (please prefer text here).
[14:03:57 INFO]: ---- Version information ----
[14:03:57 INFO]: #### Server ####
[14:03:57 INFO]: git-Spigot-21fe707-e1ebe52 ~MC: 1.8.8~
[14:03:57 INFO]:   detected: 1.8.8
[14:03:57 INFO]: #### NoCheatPlus ####
[14:03:57 INFO]: Plugin: 3.15.2-SNAPSHOT-sMD5NET-b1108
[14:03:57 INFO]: MCAccess: 1.8.4-1.8.8 / Spigot-CB-1.8_R3
[14:03:57 INFO]: Features:
[14:03:57 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
[14:03:57 INFO]:   checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[14:03:57 INFO]:   defaults: pvpKnockBackVelocity
[14:03:57 INFO]:   packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | CatchAllAdapter
[14:03:57 INFO]: Hooks: AllViolations~NCP~ 1.0
[14:03:57 INFO]: #### Related Plugins ####
[14:03:57 INFO]: ProtocolLib v4.2.1-SNAPSHOT-b353

#### How to reproduce the issue (is it random / always happens / side conditions)?
Using a version > 1.8 won't work, as the arrow would just get picked up by the player.
It also works with a fishing rod, however Combined.MunchHausen would trigger and prevent the cheat.

#### Have you made any (noteworthy) changes to the default configuration of NCP?
Default config

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
Nope.

#### Provide additional information, such as error/debug/violation logs. (For reproducible issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) Use GitHub gists or http://pastebin.com/ or similar for huge logs, or attach a (zip-) file here. For image uploads, please prefer a site that allows viewing without JavaScript, you can upload file attachments for issues right here.

**Comment by asofold** [comment]
* You don't happen to have a debug log about this?
* Do you know about side conditions, like how long they can fly or how FAST - is it limited somehow? (Thinking of them using more packets than usual and low y-speed.)

**Comment by Lysandr0** [comment]
> You don't happen to have a debug log about this?

Sure, here you go
[BowFly.txt](https://github.com/NoCheatPlus/Issues/files/1007782/BowFly.txt)


> Do you know about side conditions, like how long they can fly or how FAST - is it limited somehow? 

It works as long as you have arrows in your inventory or until you die by using the cheat , so it's 'unlimited' in that aspect; concerning how fast they can fly, it is pretty slow, as the cheat slows the game down in order to work (like a 'reverse-timer' (?) )

**Comment by asofold** [comment]
The log indicates, what i've been waiting for for more than a couple of years.

They appear to use the velocity to go upwards _normally_, i.e. with the ordinary friction of moving upwards, and they create another bit of velocity and keep going upwards.

Need to check further, but it looks like they bypass the nodamageticks by moving 'slow', which only works, if either the server ticks the player, or the client can trigger player ticking without triggering a PlayerMoveEvent on Bukkit side, which i assume they can.

They move like 3-4 times before getting new velocity, which means they abuse nodamageticks. Of course there is multiple ways of attempting to detect.
