### ISSUE TITLE
Boat Placement in recent minecraft versions

### ISSUE THREAD

**Issue by jacob1** [NoCheatPlus/Issues#454]
Boat placement is a bit bugged. In recent minecraft versions, you are now allowed to place boats on land, but NC+ still tries to block it. Even then, it doesn't block it properly. It only blocks oak boats (Material.BOAT), all other boat types (Material.BOAT_BIRCH) can still be placed.

Relevant line of code: https://github.com/NoCheatPlus/NoCheatPlus/blob/0c6cb6577d2ad96b77dff4a1efe97634c78543f9/NCPCore/src/main/java/fr/neatmonster/nocheatplus/checks/blockplace/BlockPlaceListener.java#L334

The proper fix would probably be to completely disable this check in versions of minecraft that allow you to place boats on land. Placing boats on land is a very useful feature for moving villagers, or travelling on ice rails. The workaround i'm using is to set checks.blockplace.preventmisc.boatsanywhere to false.

Version info from /ncp version:

#### Server ####
git-Spigot-6629162-c7920f4 \~MC: 1.12-pre5\~
  detected: 1.12
#### NoCheatPlus ####
Plugin: 3.15.2-SNAPSHOT-sMD5NET-b1111
MCAccess: 1.4.5-1.11.2|? / CB-Reflect
Features:
  blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12
  checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
  defaults: pvpKnockBackVelocity
  packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
Hooks: AllViolations\~NCP\~ 1.0
#### Related Plugins ####
ProtocolLib v4.3.0-SNAPSHOT-b364

**Comment by jacob1** [comment]
Also related is #110

Players were getting that issue on my server but only using oak boats, which is how I found this. Although #110 may be fixed now (I can't reproduce it anymore)

**Comment by asofold** [comment]
Good observation - NCP only checks for one type of boat, and i haven't checked boats on 1.12 yet.

**Comment by asofold** [comment]
Should be fixed in build 1112. _However_, NCP does not deny placing if other boats are between, so this might allow placing many boats on a random ground spot (mightve been possible on water beforehand as well).

**Comment by jacob1** [comment]
Thanks! I think it was actually 1.9 that allowed boats on land though, if you want it to be a little more accurate. I can't find it listed in the wiki, but 1.9 was the boat overhaul: http://minecraft.gamepedia.com/Boat

**Comment by asofold** [comment]
I'm afraid i'll revert the change for now. The point is that boat placement on ground has been possible more or less ever since, however the boatsanywhere check had been added to prevent players cramming lots of boats in one place. 

If the boatsanywhere check protects against something other than placing boats on ground (into air?), then i could add a more precise check.

For now, if you want to allow placing boats on ground, you'll have to set  checks.blockplace.preventmisc.boatsanywhere to false.

**Comment by jacob1** [comment]
Yes, I already have that set. Perhaps it should default to false (maybe it already does?), since it is blocking a vanilla feature by setting it to true. Otherwise having a setting for that seems great to me.

I wasn't aware that versions even before allowed boats on land. Seems odd because I don't think they could move on land back then ...

A proper fix for boat abuse would be nice, i've seen accidental boat abuse with elytra launchers before, the boats in that case come from a dropper I think. If it only checks for players cramming the boats, it might be a useless feature.

**Comment by MarkElf** [comment]
Although not directly related to placing boats on land but rather boat placement and movement in general, I think it's worth noting the following:
Apparently, when there is no block directly below a boat, players tend to get kicked out of the boat immediately upon entry unless they are boarding the boat from a land source.
Being used is PaperSpigot 1.8.8 and only allow 1.7.10, and 1.8.9 protocol versions to join the server, but the issue occurs on both client versions. ncp is on build 1113, default configuration.

Video of issue: https://www.youtube.com/watch?v=Ziy2c5YZb58&feature=youtu.be

Automatic boat kick/dismount: 0:06
No dismount when boat has block below it: 0:24
No dismount when boarding from land: 0:53

As you can see, the auto dismount only occurs when in open ocean, if there is a block directly below the boat while in the water, the issue doesn't occur as often, and there is no problem if the user boards from a land source.

First half of debug log: https://pastebin.com/avuyRat9
Second half of debug log: https://pastebin.com/eFCPa9Ec

If I should open a seperate ticket, please do let me know.

**Comment by asofold** [comment]
@jacob1 It should probably be disabled by default in favor of detecting crammed entities or similar - after all you could easily use some water stream to put many boats in a tight spot. On the other hand, we cold prevent excessive craft+put-on-ground by checking the bounding box vs. other entities.

@MarkElf Very sure this should be an extra issue. It looks like set backs happen, but the teleporting isn't fully done for some reason. For sure some debug logging is missing (i should add: aborted due to what...) - could also mention plugins in use.
