### ISSUE TITLE
Not executing VL Ladder command actions when it should have

### ISSUE THREAD

**Issue by Maxetto** [NoCheatPlus/Issues#463]
#### Short description of the issue.
When a player is cheating (very visible cheating), NoCheatPlus seems to fail to execute command actions, and fall back to normal warnings.

#### Complete output of the _ncp version_ command (please prefer text here).
```
---- Version information ----
#### Server ####
git-PaperSpigot-"4c7641d" ~MC: 1.8.8~
detected: 1.8.8
#### NoCheatPlus ####
Plugin: 3.15.2-SNAPSHOT-sMD5NET-b1113
MCAccess: 1.8.4-1.8.8 / Spigot-CB-1.8_R3
Features:
blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
defaults: pvpKnockBackVelocity
packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | CatchAllAdapter
Hooks: AllViolations~NCP~ 1.0 | NPCDragDownHook | PNCP 1.7
#### Related Plugins ####
ProtocolLib v4.2.1 | ViaVersion v1.1.1 | PNCP v1.7
```

#### How to reproduce the issue (is it random / always happens / side conditions)?
Cheat with absurd values, happens quite randomly.

#### Have you made any (noteworthy) changes to the default configuration of NCP?
Yes, I'm using NoCheatPlus Community Config from Captain_Obvious (I've already tried to contact him to see if it's something configurable)

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
PNCP, nothing else.

#### Provide additional information, such as error/debug/violation logs. (For reproducible issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) Use GitHub gists or http://pastebin.com/ or similar for huge logs, or attach a (zip-) file here. For image uploads, please prefer a site that allows viewing without JavaScript, you can upload file attachments for issues right here.

Take, for example, the Reach actions from Version 3.1 of the community config:
`actions: vl>1 cancel vl>4 log:freach:0:5:i cancel vl>20 cmd:cheatban:0:2 cancel vl>25 cmd:cheatban:0:2 cancel vl>30 cmd:ccheatban:0:2 cancel`

I would say, when the VL is over 20, it would trigger the "cheatban" command from the command section. Instead, it only continuosly prints log:freach.

```
NCP: Displaying SIJo05's violations...
NCP: [20:32:07] inventory.instantbow VL 1  (n1a1m1)
NCP: [20:36:48] player.nofall VL 1  (n1a1m1)
NCP: [20:36:53] player.survivalfly VL 5706  (n41a139m594)
NCP: [20:37:47] net.attackfrequency VL 13  (n13a1m1)
NCP: [20:37:49] fight.angle VL 154  (n2a77m84)
NCP: [20:42:29] combined.improbable VL 2763  (n75a37m68)
NCP: [20:42:29] fight.speed VL 82  (n68a1m6)
NCP: [20:44:36] fight.reach VL 50  (n100a0m2)
NCP: [20:44:36] fight.critical VL 27  (n27a1m1)
NCP: [20:44:38] fight.direction VL 188  (n130a1m3)
```

Given the values of this player, it should have triggered even the 3rd VL ladder (and in multiple checks), instead he didn't trigger anything from NCP.

The player said he was using Wurst.

I would really like to know why this is happening, is this something that has to do with low average VL values? Is something that it needs to be configured (like consistency)?

**Comment by asofold** [comment]
Not sure i'm understanding right here.

Note that the summary with 'ncp info' shows the sum of all vls (50 for fight.reach, not relevant for actions!) - to judge actions you should look at the part in parentheses:
* n100 means 100 violations.
* a0 means an average violation level of below 1 (relevant for actions!).
* m2 means a maximum violation level of below 3 (relevant for actions!).

So it looks like the cheat only produces low violation levels...

The actual flaw may be that NCP allows too many past positions to be hit, because the latency mechanics have not yet been implemented (...).

**Comment by Maxetto** [comment]
> So it looks like the cheat only produces low violation levels...

He was using pretty high killaura settings tho, strange that he had so many low values.


Anyway, so how can I (we) set-up a config in order to ban cheating but not normal players?
Because I often see 1 or 2 false positives with the same average and maximum VL for normal (lagging?) players.

Setting a value of 2 for running actions it seems pretty much suicide. Isn't it better to use the sum of all VLs like in NCP info?

**Comment by asofold** [comment]
Better is relative... there is a lot of alternative possibilities of how to implement violation levels, e.g. use the number of violations and perhaps a cooldown and average values.

Catch all without false positives is not always possible - a lagging player would hit similarly like a killaura (until i implement something better).

**Comment by asofold** [comment]
Closing as superseded.
