### ISSUE TITLE
PlayerMove does lag the server

### ISSUE THREAD

**Issue by Xayanix** [NoCheatPlus/Issues#474]
Timings: https://timings.spigotmc.org/?url=taceduvibi

**Comment by MarkElf** [comment]
The provided sample was 8 seconds. Please provide a longer sample and the output of /ncp version.

**Comment by Xayanix** [comment]
https://timings.spigotmc.org/?url=kiwuhobewo

**Comment by CaptainObvious0** [comment]
I think it's somewhat reasonable for NoCheatPlus to use around 12% of the tick if it has to track around 400 players. 

Show us your NoCheatPlus config and maybe we could see if there are any areas to optimize.

**Comment by Xayanix** [comment]
My AntiCheat also has many checks and it doesnt produce any lag (see NS_Vac).

**Comment by CaptainObvious0** [comment]
@Xayanix Could you explain a little more on what your Anti-Cheat does and blocks? Does your Anti-Cheat have a fly check and how does it work?

Again, could you post your NCP config, there may be some areas to optimize.

**Comment by asofold** [comment]
Long gone, but 12% is a bit much also for a 500 player server - typical is 0.5-5%. For lower event counts (less than a million), higher values can easily happen.  Checking moving is quite intense and does need the JIT to work out at all.

Another question is, what level of checking/tweaking has been done. A 400 player server needs some attention and diligence concerning plugins and configurations, so it could be relevant to check out what plugins are installed and how they interact, in this case concerning NCP (any extensions hooking into NCP, like cncp, NTAC, ...).

Then again i can't see the timings and no version information is present (_ncp version_).
