### ISSUE TITLE
NCP Not Working

### ISSUE THREAD

**Issue by Sunboyz21** [NoCheatPlus/Issues#476]
#### Short description of the issue.

- So basically NCP launches fine and when i do /ncp on my account with the proper perms it works, but on a random normal account, when they do /ncp it say's unknown command. Also, it doesn't detect any hacks **at all** even though it should.

#### Complete output of the _ncp version_ command (please prefer text here).

- [IDK what this is...., but I'm running NoCheatPlus 3.13.5-BETA-sMD5NET-b914]

#### How to reproduce the issue (is it random / always happens / side conditions)?

- It always happens for me

#### Have you made any (noteworthy) changes to the default configuration of NCP?

- Yep, a LOT of changes. Though I don't think it'll effect ncp that much, config: -
https://pastebin.com/nqijX5Gy

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
- No.
#### Provide additional information, such as error/debug/violation logs. (For reproducible issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) Use GitHub gists or http://pastebin.com/ or similar for huge logs, or attach a (zip-) file here. For image uploads, please prefer a site that allows viewing without JavaScript, you can upload file attachments for issues right here.
- https://pastebin.com/wVrtXsrf

**Comment by MarkElf** [comment]
A. Outdated version, download the latest development build. 
B. It clearly shows you what was done wrong in the start up log.

**Comment by CaptainObvious0** [comment]
Taking a look at your config there are a lot of errors with it. Who ever made it, made a lot of errors. You have random logging info such as :if, your commands don't have a repeat and delay label, you will tp a player 200 blocks up when they fail the check Passable, you put doors and trap doors in the ignore passable section meaning anyone can phase through those blocks. 

For the most part the config is a pretty big mess.

**Comment by Sunboyz21** [comment]
@MarkElf 
"A. Outdated version, download the latest development build.
B. It clearly shows you what was done wrong in the start up log"
- Alright so I updated ncp and it still doesn't work
- What do you mean by; 'It clearly shows you what was done wrong in the start up log' I really don't know how to read the console log so.....
-------------------------------------------------------------------------------------------------------------------
@CaptainObvious0 
"Taking a look at your config there are a lot of errors with it. Who ever made it, made a lot of errors. You have random logging info such as :if, your commands don't have a repeat and delay label, you will tp a player 200 blocks up when they fail the check Passable, you put doors and trap doors in the ignore passable section meaning anyone can phase through those blocks.

For the most part the config is a pretty big mess."
- I'm using a edited version of 'FlashConfig - v1' (https://mega.nz/#!M99HzQAZ!qHbHSSuro0XRAC1_Vq9_beBbQYFH_WC4U9QxTbfJAyM)
To be honest, ncp gives you a config with no documentation on how to configure it at all. I'm not surprised that it's a bit messy. 
~~Chief

**Comment by CaptainObvious0** [comment]
@Sunboyz21 I would say the NoCheatPlus wiki (https://github.com/NoCheatPlus/Docs/wiki/Configuration) would be pretty sufficient. That's how I was able to learn about how to configure it correctly.

Both @MarkElf and I offer a premade config similar to the flash config you have. Both of these configs have been edited correctly and should not cause any errors.

My Config
https://www.spigotmc.org/threads/nocheatplus-config-optimized-and-free.158041/

MarkElf's Config
http://www.mc-market.org/resources/475/ 

If you are interested in using a custom config check them both out and you can decide for yourself.

**Comment by asofold** [comment]
Trap doors had been in the list, ages ago :). Closing as ... idk.
