### ISSUE TITLE
Add Support for 1.12.x in CB-Reflect

### ISSUE THREAD

**Issue by CDAGaming** [NoCheatPlus/Issues#486]
This issue is a mirror of #345 which its the same wan/error message, except now for both 1.12 and 1.12.1

**Comment by Superdarco** [comment]
https://ci.md-5.net/job/NoCheatPlus/

**Comment by CDAGaming** [comment]
Should've said earlier but @Superdarco I am running the latest build from source(From that link/build CI)

**Comment by TheZenKitteh** [comment]
I have this issue as well. Spigot 1.12.1 buildtools 63. Using NCP build 1113.

**Comment by seema84** [comment]
can confirm in 1.12.2 and ncp build 1113
