### ISSUE TITLE
Why do i get these messages?

### ISSUE THREAD

**Issue by BloodEko** [NoCheatPlus/Issues#490]
#### Short description of the issue.
Get a lot messages

#### How to reproduce the issue (is it random / always happens / side conditions)?
Happens with a modified config.

#### Have you made any (noteworthy) changes to the default configuration of NCP?
Yes

Screenshot: http://www.bilder-upload.eu/show.php?file=c589f9-1504312423.png

What do these messages mean ? I get them on every login, is there a proper way to disable them ?

**Comment by MarkElf** [comment]
You're running a super outdated config, change the version number at the top, both saved and created,  to 1104.
