### ISSUE TITLE
Error in console after restart.

### ISSUE THREAD

**Issue by TheZenKitteh** [NoCheatPlus/Issues#491]
#### Short description of the issue.
Error in console.

#### Complete output of the _ncp version_ command (please prefer text here).
https://pastebin.com/raw/n4U1cYwc

#### How to reproduce the issue (is it random / always happens / side conditions)?
Seems to happen after server has started and a few times after that.

#### Have you made any (noteworthy) changes to the default configuration of NCP?
https://pastebin.com/raw/k1gBQBRU

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
Not sure, not that I'm aware of.

#### Provide additional information, such as error/debug/violation logs. (For reproducible issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) Use GitHub gists or http://pastebin.com/ or similar for huge logs, or attach a (zip-) file here. For image uploads, please prefer a site that allows viewing without JavaScript, you can upload file attachments for issues right here.

https://pastebin.com/raw/717ZSqAK

**Comment by asofold** [comment]
A plugin with something like 'us.Myles.PWP' in the code base causes a teleport off the primary server thread, which is dangerous to have in general. In case of properly set up NPCs this might be fixed for the latest versions of NCP since build 1136.

**Comment by Janmm14** [comment]
Its PerWorldPlugins

**Comment by asofold** [comment]
Thanks ... PWP - slipped past citizens though: net.citizensnpcs.api.npc.AbstractNPC.teleport seems to be the more obvious thing here. Parts of these will be ignored by latest builds.
