### ISSUE TITLE
Can't walk

### ISSUE THREAD

**Issue by DanielAlves123** [NoCheatPlus/Issues#493]
When I'm playing on 1.8 version I can't walk on this dirt path/road. I can't remember the exact name of it.

**Comment by RoboMWM** [comment]
Grass path or whatever? I'm assuming your server uses a newer version since grass paths were added in 1.9? If so, that's the tradeoff to using protocol plugins... you might be able to play around with the block shapes in the config.

**Comment by DanielAlves123** [comment]
@RoboMWM NoCheatPlus should check player's version and block and not block his movement.

**Comment by RoboMWM** [comment]
There's no way to do that without specifically hooking into protocol plugins to determine that afaik. It's up to you to add exemptions if you want to support different clients on your server.

**Comment by asofold** [comment]
Grass path... like soil perhaps.

I've just added block flags which might make it compatible, provided you add the appropriate entry to compatibility.blocks.overrideflags:
GRASS_PATH: default+height100+ground_height+min_height16_15

This way everything between 1 - 0.0625 and 1 is passable and can be stood on. If this works, i can add a default workaround that will activate, if any of the typical protocol support plugins is present.

Concerning client versions.... detecting those is thinkable, as we hook into ProtocolLib anyway, if simple enough also reflection is an option, HOWEVER ... using different block properties for different clients also means deeper changes to the innerts of NCP.

I can imagine adding a "context flags" entry to block shape stuff, but apart from that being a medium sized change already, i'd also need to ensure that different contexts are applied for things like fight checks, where we might query some properties for the attacked player too.

All in all it seems more feasible to me, to dump all legacy stuff into the 'more coarse workarounds bucket'. So workarounds are possible, and side effects with moving can be tackled too (sprint jump on lilypad at the maximum allowed ground height...), but i'd rather make them coarse, for the sake of maintainability.

It's been thought of giving every player their own view of the world, e.g. allowing to have a different labyrinth for each player, only visible for each player themselves. Implementing that is similarly complex though. If it happens, client-specific precise workarounds will be in range.

There still could be side effects though (I can hit you through a wall made of soil. what ever way that was achieved, but you can't hit back.), so changes to interaction/direction checks may be needed too.

**Comment by asofold** [comment]
Added some default entries with enabling with ProtocolSupport, assume fixed.
