### ISSUE TITLE
Blocks respawning after being mined, or digged

### ISSUE THREAD

**Issue by djstef4u2** [NoCheatPlus/Issues#495]
#### Short description of the issue.
Blocks respawning after mining or digging
#### Complete output of the _ncp version_ command (please prefer text here).
There is no error output for this problem
#### How to reproduce the issue (is it random / always happens / side conditions)?
Its happends very often
#### Have you made any (noteworthy) changes to the default configuration of NCP?
No changes at all
#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
MCMMO, + compactnocheat
#### Provide additional information, such as error/debug/violation logs. (For reproducible issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) Use GitHub gists or http://pastebin.com/ or similar for huge logs, or attach a (zip-) file here. For image uploads, please prefer a site that allows viewing without JavaScript, you can upload file attachments for issues right here.
Players are having the issue that whenever they are mining or digging, it happends that after breaking a block it instantly respawns and has to be broken again.
When removing nocheatplus from the server this does not appear to happen.
I think the nocheatplus plugin thinks that blocks are being broken to fast.
Is there a way to stretch this time? 
Kind Regards, Sfmplayer

**Comment by RoboMWM** [comment]
What tools are they using, do they have any enchantments like efficiency IV or the like?

Also, you didn't provide any debugging information or any way to reproduce, just a "oh this just happens."

**Comment by asofold** [comment]
We need more side conditions for when this happens (block types, tools, enchantments).

Closign as superseeded (many updates).
