### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by OfficialTheosis** [NoCheatPlus/Issues#496]
#### Short description of the issue.
Whenever a user joins the server, a blank message is displayed in chat above the join message. Here is a screenshot showing an example: https://prnt.sc/h2feyl.
#### Complete output of the _ncp version_ command (please prefer text here).
Not sure what this means.
#### How to reproduce the issue (is it random / always happens / side conditions)?
It always happens upon joining the server.
#### Have you made any (noteworthy) changes to the default configuration of NCP?
I attempted running the server using the default configuration and the message still appeared.
#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
I attempted running the server with **only** NCP installed and the message still appeared.

**Comment by MarkElf** [comment]
I really doubt that this has anything to do with ncp. Antiminimap had something like this but with more blank lines. Could also be the essentials join message.

**Comment by Janmm14** [comment]
Did you tried removing NCP?

**Comment by OfficialTheosis** [comment]
I know for a fact that the issue is being caused because NCP is installed. Like I said in the original post, the message still appeared when NCP was the only plugin installed. Running the server _without_ NCP being installed doesn't produce the message.

**Comment by OfficialTheosis** [comment]
Never mind, I have figured out the cause of the problem. The MotD needs to be disabled in the config, that was it.
