### ISSUE TITLE
When remove kick funtion, still NCP kick the Player (end of stream) And Dataman Issue

### ISSUE THREAD

**Issue by DahunDev** [NoCheatPlus/Issues#497]
#### Short description of the issue.

When remove kick funtion, still NCP kick the Player

When Using ProtocolSupport, NCP will kick normal players so need to disable kick funtion.

All Version 

If I remove the config kick cmd, like
    attackfrequency:
      active: true
      limitforseconds:
        half: 10
        one: 15
        two: 30
        four: 60
        eight: 100
      actions: cancel vl>30 cancel log:attackfrequency:0:5:if vl>160 cancel log:attackfrequency:0:0:cif

it still kick the player

Spigot 1.8.8 withe ProtocolSupport

 DataMan inconsistencies: missing online players (2) | wrong number of online players (54 instead of 56)
is appering all version of NCP

#### How to reproduce the issue (is it random / always happens / side conditions)?

Kick: Random, 

Dataman
 DataMan inconsistencies: missing online players (2) | wrong number of online players (54 instead of 56)

: Always
#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?

NO 

#### Provide additional information, such as error/debug/violation logs. (For reproducible issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) Use GitHub gists or http://pastebin.com/ or similar for huge logs, or attach a (zip-) file here. For image uploads, please prefer a site that allows viewing without JavaScript, you can upload file attachments for issues right here.
17-10-31 10:38:26 [미세] [MOVING] [KiteTest] Set back to: CraftWorld{name=world}-1,266.613, 37, -1,374.801
17-10-31 10:38:26 [미세] [MOVING] [KiteTest] TP UNKNOWN (set-back): Location{world=CraftWorld{name=world},x=-1266.6133795027097,y=37.0,z=-1374.8011836963744,pitch=31.95006,yaw=322.7024}
17-10-31 10:38:26 [미세] [MOVING] [KiteTest] TP UNKNOWN (normal): Location{world=CraftWorld{name=world},x=-1266.6133795027097,y=37.0,z=-1374.8011836963744,pitch=31.95006,yaw=322.7024}
17-10-31 10:38:26 [미세] [NET] [Princess_YA] Flying(ground=true)
17-10-31 10:38:26 [미세] [MOVING] [KiteTest] TP UNKNOWN (normal): Location{world=CraftWorld{name=world},x=-1266.6133795027097,y=37.0,z=-1374.8011836963744,pitch=31.95006,yaw=322.7024}
17-10-31 10:38:26 [미세] [MOVING] [KiteTest] TP UNKNOWN (normal): Location{world=CraftWorld{name=world},x=-1266.6133795027097,y=37.0,z=-1374.8011836963744,pitch=31.95006,yaw=322.7024}
17-10-31 10:38:26 [미세] [MOVING] [KiteTest] TP UNKNOWN (normal): Location{world=CraftWorld{name=world},x=-1266.6133795027097,y=37.0,z=-1374.8011836963744,pitch=31.95006,yaw=322.7024}
17-10-31 10:38:26 [미세] [NET] [Princess_YA] Flying(ground=true,x=-949.3000000119209,y=37.0,z=-1253.300000011921)
17-10-31 10:38:26 [미세] [NET] [Princess_YA] Flying(ground=true)
17-10-31 10:38:26 [정보] [VL] [NET_KEEPALIVEFREQUENCY] [Princess_YA] [->[*Kite서버중류층*]Princess_YA] VL=1(+1) health=20.0/20.0
17-10-31 10:38:26 [미세] [NET] [Princess_YA] Flying(ground=true)
17-10-31 10:38:26 [정보] [VL] [BLOCKINTERACT_DIRECTION] [KiteTest] [->[*Kite서버유저*]KiteTest] VL=20.9(+4.3) health=20.0/20.0
17-10-31 10:38:26 [정보] KiteTest failed Direction: tried to interact with a block out of their line of sight. VL 21.
17-10-31 10:38:26 [정보] [VL] [BLOCKINTERACT_DIRECTION] [KiteTest] [->[*Kite서버유저*]KiteTest] VL=24.4(+3.6) health=20.0/20.0
17-10-31 10:38:26 [미세] [NET] [Princess_YA] Flying(ground=true)
17-10-31 10:38:26 [정보] Player KiteTest leaves at location: Location{world=CraftWorld{name=world},x=-1266.6133795027097,y=37.0,z=-1374.8011836963744,pitch=31.95006,yaw=322.7024}

**Comment by asofold** [comment]
Since there has been a similar report (kick, dataman, unable to rejoin) this ticket is put to top now.

**Comment by asofold** [comment]
Closing as 'superseded'. There have been related fixes both in Spigot and NCP, which i can't really relate to this issue. Further i don't see the version information for NCP. Feel free to comment further....
