### ISSUE TITLE
NoCheatPlus is dead?

### ISSUE THREAD

**Issue by Xayanix** [NoCheatPlus/Issues#500]
As in title?

**Comment by 0-x-2-2** [comment]
no @asofold is just busy with irl stuff I think. NCP still works fine on all servers and imo is the best free server-sided anticheat for minecraft out there.

**Comment by DardBrinza** [comment]
@w-o-a-h He got critical bugs on new server versions (long jump, flight and other bypasses)

**Comment by Janmm14** [comment]
Bypasses for Speed did always exist in NoCheatPlus and will likely always exist in the future.

Last time someone showed me a client with a NoCheatPlus flight bypass, I could not fly on my local NoCheatPlus test server with that client.
I just know of two people having a private fly bypass which is really, really slow and just those two do also have a teleport bypass. But they keep the bypass private and do not cheat on servers.

**Comment by 0-x-2-2** [comment]
> He got critical bugs on new server versions (long jump, flight and other bypasses)

long jump/speed was already semi patched to it almost not working at all. flight also is not really a thing unless you are using a outdated ncp version that is like 2 years old.

**Comment by MarkElf** [comment]
Use 3rd party plugins where applicable. This includes Search, ntac (lots of console spam), and pncp.

**Comment by 0-x-2-2** [comment]
ntac is a year old and abandoned and using pncp I had some performance issues but so far search has been fine.

**Comment by Eyremba** [comment]
@w-o-a-h you can also try Reflex, Spartan or AAC.

**Comment by 0-x-2-2** [comment]
aac and spartan causes wierd lag spikes for me haven't tried reflex.

**Comment by MarkElf** [comment]
From my experience, which was quite some time ago, Reflex did throw a few false positives at first but did very well with kill aura. Most issues were likely fixed by now I assume.

**Comment by enterih** [comment]
it finally don't death ans asofold is alive (i'm happy about that)

**Comment by asofold** [comment]
@Janmm14 As always, details are most welcome :). There have been cases of cheats targeting certain configurations, e.g. if you don't always cancel fly check violations.

**Comment by Janmm14** [comment]
@asofold It was default config in all cases and I don't really know much more.
