### ISSUE TITLE
Kicked for flying - Bungee Cord

### ISSUE THREAD

**Issue by Luke1702** [NoCheatPlus/Issues#502]
#### Short description of the issue.
Hello, so whenever I connect to my server with bungeecord I type /server (name) or from bungee portals or something it keeps kicking me saying "Kicked for flying (or related)"

#### Complete output of the _ncp version_ command (please prefer text here).
handleDisconnection() called twice
[NoCheatPlus] (CONSOLE) Kicked {playername} : Kicked for flying (or related)

#### How to reproduce the issue (is it random / always happens / side conditions)?
It literally most of the time happens when I try to connect, sometimes it lets me in (rarely) but most of the times get kicked.

#### Have you made any (noteworthy) changes to the default configuration of NCP?
I couldnt find anything to make changes of flying

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
I dont run any that affects NC+ (I dont think)

**Comment by asofold** [comment]
Closing as superseded - too much has changed (now: build 1147).
