### ISSUE TITLE
False Positive with Half Blocks like Iron Bars or Glass Panes

### ISSUE THREAD

**Issue by ygtdmn** [NoCheatPlus/Issues#505]
#### Short description of the issue.
Player's cant move on Iron Bars or Glass Panes.

#### Complete output of the _ncp version_ command (please prefer text here).
```
[18:50:40 INFO]: ---- Version information ----
[18:50:40 INFO]: #### Server ####
[18:50:40 INFO]: git-PaperSpigot-"8b18730" ~MC: 1.8.8~
[18:50:40 INFO]:   detected: 1.8.8
[18:50:40 INFO]: #### NoCheatPlus ####
[18:50:40 INFO]: Plugin: 3.15.2-SNAPSHOT-sMD5NET-b1116
[18:50:40 INFO]: MCAccess: 1.4.5-1.11.2|? / CB-Reflect
[18:50:40 INFO]: Features:
[18:50:40 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
[18:50:40 INFO]:   checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[18:50:40 INFO]:   defaults: pvpKnockBackVelocity
[18:50:40 INFO]:   packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | CatchAllAdapter
[18:50:40 INFO]: Hooks: AllViolations~NCP~ 1.0
[18:50:40 INFO]: #### Related Plugins ####
[18:50:40 INFO]: ProtocolLib v4.3.0 | ViaVersion v1.3.0

```
#### How to reproduce the issue (is it random / always happens / side conditions)?
It always happens. Watch the video at bottom and do the same things to reproduce.

#### Have you made any (noteworthy) changes to the default configuration of NCP?
I'm using the config of MarkElf. (http://www.mc-market.org/resources/475/) This problems happens because of passable. So here the passable section:
https://www.hastebin.com/bovovadimo.css

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
I do use Reflex and Spartan. But i closed movement checks in there. This plugins are only exist because of KillAura. And this problem even happens without these plugins.

#### Provide additional information, such as error/debug/violation logs. (For reproducible issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) Use GitHub gists or http://pastebin.com/ or similar for huge logs, or attach a (zip-) file here. For image uploads, please prefer a site that allows viewing without JavaScript, you can upload file attachments for issues right here.
Logs: https://www.hastebin.com/rewanabipe.swift (search the name of Ubiets to find out what is happening)
Videos (will be ready in 10 minutes. Uploading  right now):
https://www.youtube.com/watch?v=XKhM34Q13rs&feature=youtu.be
https://www.youtube.com/watch?v=JVo7XZXTrAQ&feature=youtu.be

**Comment by asofold** [comment]
Did it always show "MCAccess: 1.4.5-1.11.2|? / CB-Reflect" ?

If not, perhaps using build 1117 might help there.

**Comment by ygtdmn** [comment]
It always shows "MCAccess: 1.4.5-1.11.2|? / CB-Reflect" 

When i add this to config it solves the problem:

 

```
 overrideflags:
       snow: default
       '101': solid+ground+xz100+height100+ground_height
       '102': solid+ground+xz100+height100+ground_height
```

**Comment by asofold** [comment]
Yes, that'll also make the blocks entirely passable, so they are not fit for walls security-wise  from then on, just to note. (Those blocks are shifty anyway.)

Concerning MCAccess, build 1116 doesn't have the more efficient native-access modules inside, so using any later build should change that.

Concerning the problem with glass panes, i can only guess...
* A special build of PaperSpigot with package names changed?
* Some oddity in the logs - set-back teleportation got overridden now and then. That could in theory cause issues. Are you sure you have disabled all moving/map-related checks in the other plugins, e.g. noclip stuff?

**Comment by ygtdmn** [comment]
- I installed b1119 and problem still occurs.
- It is TacoSpigot.
- Removed every other anticheat plugins but this problem still exist.
- Here all logs:
https://pastebin.com/WxHkYJ44
- I also tried remove every plugin except NoCheatPlus but still have it.
- And lastly i tried with Latest Normal Spigot 1.8.8 build (not Paper) and happened again.

**Comment by asofold** [comment]
I can walk ... on glass panes and iron bars with a 1.8.9 client on a 1.8.8 Spigot server.

If the compatibility.blocks.overrideflags section still contains entries for these blocks (names or ids), we should have a look at those.

The next step could be to use 'ncp debug player PLAYERNAME', then reproduce the issue a couple of times, then '/ncp reload' or 'ncp remove PLAYERNAME'. That would output a lot to the ncp log file. This could also be an option for future reports, because debug logs typically allow fast and precise judgement on such issues (https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players).

**Comment by asofold** [comment]
Assume fixed/superseded by subsequent builds (1147 at present).
