### ISSUE TITLE
Spigot resource name includes a datestamp

### ISSUE THREAD

**Issue by DoNotSpamPls** [NoCheatPlus/Issues#508]
Self-explanatory, I don't think it should be there.

![](https://bitcoin.is-serious.business/2543b1.png)

**Comment by Janmm14** [comment]
I do not see it on spigotmc:
https://www.spigotmc.org/resources/nocheatplus.26/

**Comment by DoNotSpamPls** [comment]
They've just fixed it ¯\\\_(ツ)_/¯

**Comment by asofold** [comment]
Yes :), thank you for the report :). I always thought it was mandatory like the URL part with dot and numbers... but it's not. MyPictures created the project on spigotmc.org initially, and perhaps it's been auto-added back then or he did it for another reason / accidental copy and past, who knows.
