### ISSUE TITLE
Maven error

### ISSUE THREAD

**Issue by alvarocduquia** [NoCheatPlus/Issues#511]
Hello, I'm having trouble compiling the project with Maven. 

Follow the Maven code: https://pastebin.com/66M4MNpj and https://pastebin.com/SSvUGYBr

Can you help me?

Thanks!

**Comment by asofold** [comment]
To build against NCP, com.github is a good guess, but NCP still is set to  'fr.neatmonster' with artifact id 'nocheatplus'.

CompatNoCheatPlus builds against NoCheatPlus: https://github.com/asofold/CompatNoCheatPlus/blob/master/CompatNoCheatPlus/pom.xml#L54

The repostiories to find NoCheatPlus (snapshots/releases) are referenced here: 
* https://github.com/asofold/CompatNoCheatPlus/blob/master/CompatNoCheatPlus/pom.xml#L23
* https://github.com/asofold/CompatNoCheatPlus/blob/master/CompatNoCheatPlus/pom.xml#L26

(If https should work, it's prefereable.)

**Comment by alvarocduquia** [comment]
Worked, thank you!

**Comment by Janmm14** [comment]
https://repo.md-5.net/content/groups/public
to include both snapshots and releases
