### ISSUE TITLE
Trapdoor Passable Bug

### ISSUE THREAD

**Issue by ghost** [NoCheatPlus/Issues#528]
#### Short description of the issue.
In this example, when descending into a trapdoor, but rapidly closing it before fully passing through the trapdoor, the player gets caught "inside of the block" causing passable VLs.
#### Complete output of the _ncp version_ command (please prefer text here).
[01:35:38 INFO]: ---- Version information ----
[01:35:38 INFO]: #### Server ####
[01:35:38 INFO]: git-Paper-1373 ~MC: 1.12.2~
[01:35:38 INFO]: detected: 1.12.2
[01:35:38 INFO]: #### NoCheatPlus ####
[01:35:38 INFO]: Plugin: 3.16.0-RC-sMD5NET-b1134
[01:35:38 INFO]: MCAccess: 1.12-1.12.2 / Spigot-CB-1.12_R1
[01:35:38 INFO]: Features:
[01:35:38 INFO]: blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12
[01:35:38 INFO]: checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[01:35:38 INFO]: defaults: pvpKnockBackVelocity
[01:35:38 INFO]: packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
[01:35:38 INFO]: Hooks: AllViolations~NCP~ 1.0
[01:35:38 INFO]: #### Related Plugins ####
[01:35:38 INFO]: ProtocolLib v4.3.0
#### How to reproduce the issue (is it random / always happens / side conditions)?
An easy way is to descend onto a trapdoor, while closing it on yourself. Try it a few times until it catches you.
#### Have you made any (noteworthy) changes to the default configuration of NCP?
Yes. However, passable has "cancel" as the first option, followed by a logging one, which shows these messages. All else is unrelated.
#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
Nope.
#### Provide additional information, such as error/debug/violation logs. (For reproducible issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) Use GitHub gists or http://pastebin.com/ or similar for huge logs, or attach a (zip-) file here. For image uploads, please prefer a site that allows viewing without JavaScript, you can upload file attachments for issues right here.
Here is a picture of the problem in action: https://cloudup.com/cxbjdba667P

**Comment by asofold** [comment]
Apart from reproducing, this should be ensure to be covered by the block change tracking system. While i can't really work around all the cases with packet processing order inverted (interact first, then move), i can add those clicked blocks to the block change tracker.
* Trap door.
* Ordinary doors.
* (Other ... other cases like entity changer block etc.)

Perhaps i'll add a block flag for this.

**Comment by asofold** [comment]
Build 1144 contains a  fix attempt - in addition to a larger range of internal changes, which may affect exemption, permissions, check activation, debug flags and lag adaption flags :) ~ wouldn't test that on a production server yet, unless people are able to quickly react/rollback if necessary (or where impact just isn't expected to be large).

The fix is introduced via the block change tracker (compatibility.blocks.changetracker...), which is activated by default.

With the latest builds of 1.12.2 i also have a range of new/old survivalfly false positives and oddities. Uncertain if the client has changed or it's newly introduced bugs.

**Comment by MarkElf** [comment]
The issues with survivalfly may be related to the way 1.12.2 handles keepalive packets as that seems to have changed according to some users on spigot. I experienced nearly endless rubberbanding to the point of hardly being able to play.

**Comment by asofold** [comment]
(Assume fixed around build 1147.)
