### ISSUE TITLE
CMI Sit-Animation blocked because of NCP

### ISSUE THREAD

**Issue by ScuroK** [NoCheatPlus/Issues#534]
#### Short description of the issue.
cmi sitting function does not work because of ncp

please see this issue:
https://github.com/Zrips/CMI/issues/256

**Comment by asofold** [comment]
Looks like the developer has already fixed it or worked around it on their side.

**Comment by ScuroK** [comment]
issue was fixed by Zrips (cmi dev) thanks alot.
