### ISSUE TITLE
Holding Q to drop items from inventory flags inventory.fastclick

### ISSUE THREAD

**Issue by MarkElf** [NoCheatPlus/Issues#537]
Posting on behalf of @Joe7670 
#### Short description of the issue.
Holding Q to drop items from inventory flags inventory.fastclick
#### Server ####
git-Paper-1384 ~MC: 1.12.2~
  detected: 1.12.2
#### NoCheatPlus ####
Plugin: 3.16.1-SNAPSHOT-sMD5NET-b1144
MCAccess: 1.12-1.12.2 / Spigot-CB-1.12_R1
Features:
  blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12
  checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
  defaults: pvpKnockBackVelocity
  packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
Hooks: AllViolations~NCP~ 1.0
#### How to reproduce the issue (is it random / always happens / side conditions)?
Open your intentory with a stack of items, hover over said stack of items, hold Q, fastclick is flagged and stops items from dropping.
#### Have you made any (noteworthy) changes to the default configuration of NCP?
None.

**Comment by asofold** [comment]
"Holding Q" <- With a vanilla client?

**Comment by MarkElf** [comment]
Yes, with a vanilla client. I didn't even know that was a method of dropping items till yesterday.

**Comment by Joe7670** [comment]
https://youtu.be/gnIfQiI_ARk

**Comment by asofold** [comment]
If i press the drop-item key, One item drops... i'd have to repeatedly press and release, leading to no violations. Thus...
* Do you have special drivers/settings/features for your keyboard, leading to continuous sequences of 'press-release' for just holding the key pressed?
* Not by accident a 'vanilla optifine client' or so :p ?

Edit: A feature of PaperSpigot ?

**Comment by MarkElf** [comment]
Pure vanilla, no keybinds, as you said, may be paper spigot. I'll test it later today if no one beats me to it.

**Comment by asofold** [comment]
Oh dropping from the inventory not from the hot bar...

Lol idiot me...

**Comment by asofold** [comment]
Confirmed :p. Problem is that we would like to have an inventory open/close event for the player inventory (...). How could we distinguish between dropping from the hotbar while moving and dropping from inventory...

Of course estimating plausibility for having inventory open/closed is something really useful to add, also to tackle other sort of cheats, but it's a somwhat lengthy task to add such.

**Comment by asofold** [comment]
A fix attempt will be in from build 1146 on.

Edit: Note it's 'bleeding' build status.

**Comment by MarkElf** [comment]
Confirmed that build 1146 fixes the issue.
