### ISSUE TITLE
pack kick, event.

### ISSUE THREAD

**Issue by Remski01** [NoCheatPlus/Issues#546]
#### Short description of the issue.
It kick everyone.

#### Complete output of the _ncp version_ command (please prefer text here).
https://pastebin.com/Lhf97ssr

#### How to reproduce the issue (is it random / always happens / side conditions)?
random.

#### Have you made any (noteworthy) changes to the default configuration of NCP?
No.

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?

https://pastebin.com/azczdEku

**Comment by asofold** [comment]
Tecnically this is odd, but easily possible to work around. ~~I assume it's a plugin changing things, so this happens (multi client protocol support, ProtocolLib).

(I don't expect an enum.values() to contain null values.)~~

Edit: Was on the wrong trail here, it can happen, though it's actually odd to have a server sent event behave like that.

Will be fixed next build(s) 1148+.
