### ISSUE TITLE
Joining Chat Spam Default Values

### ISSUE THREAD

**Issue by shoobopper** [NoCheatPlus/Issues#551]
Everytime I login, the chat is spammed with the same message.
https://i.imgur.com/Vz2GU7D.png

How would I go about removing these specific "default value" changing notifications.

**Comment by MarkElf** [comment]
That happens when you update your jar file and your config was for an older version. I don't remember the setting name but it was right at the top of the configuration under 'notify' I believe.

**Comment by shoobopper** [comment]
Fixed
