### ISSUE TITLE
1.13 initial support

### ISSUE THREAD

**Issue by sgdc3** [NoCheatPlus/Issues#552]
@asofold are you planning to start working on a compatible version soon?

**Comment by asofold** [comment]
"Soon"  -  yes!

Technically, first i had trouble building spigot for 1.13, because the OS didn't seem to upgrade to contain jdk 8, and BuildTools wouldn't accept running from a local jdk-8, neither with environment variables set. So i couldn't have a simple and fast way in. Just now im in a remote spot with difficult internet :), then my replacement/mobile system wouldn't accept the bootup/luks password  anymore ;), so reinstalling took many hours - at least now the jdk-8 is on board.

So i'll really soon build and test stuff.

**Comment by sgdc3** [comment]
@asofold if you want i have a nms maven repository, so you can stop going crazy about buildtools xD Build time should improve a lot too.

**Comment by Janmm14** [comment]
@sgdc3 Just because you have a repository it doesn't mean its legal.

**Comment by sgdc3** [comment]
@Janmm14 who said it is, nobody complained about it so far. Also patching at runtime isn' clear to be legal.

**Comment by sgdc3** [comment]
@Janmm14 i sent you a DM on discord to talk about that without flooding this issue report xD

**Comment by asofold** [comment]
I can build everything now, it seems.

Unfortunately i can't log in to any of my Minecraft accounts right now... not sure what that is about, possibly a new stage of alchemy required, or just proffessional maltypism.

**Comment by asofold** [comment]
I had this a while ago on the default machine, at some point login was possible again.

Without Minecraft client i can't test/bump-into stuff.

**Comment by Janmm14** [comment]
@asofold try log in on mojang website and change password

**Comment by asofold** [comment]
Looks like i can't log in from anywhere to anywhere.

**Comment by sgdc3** [comment]
@asofold is it an issue with your account or pc?

**Comment by asofold** [comment]
@sgdc3 Either i am forgetting the passwords or the accounts are somehow blocked.

The last time something similar happened, i had tried lots of times/combinations, and was sure to have seen  the combination that finally worked rejected before, a couple of weeks/months ago. Perhaps it's been an auth server thing back then. But this time its about a week or more that i can't log in.

Neither minecraft.net nor mojang.com nor java version (pc) worked so far. Also looks like i have not received any releated email.

**Comment by sgdc3** [comment]
@asofold do you have an email address?

**Comment by sgdc3** [comment]
@asofold just sent you an email with a surprise.

**Comment by sgdc3** [comment]
also fix the spigot page images, you can find an archived version of the page there: https://web.archive.org/web/20150919084517/https://www.spigotmc.org/resources/nocheatplus.26/

**Comment by sgdc3** [comment]
P.S: https://web.archive.org/web/20130513220848/http://www.spigotmc.org:80/resources/nocheatplus.26 lol dat logo was sexy

**Comment by asofold** [comment]
@sgdc3 Thank you :) - i can test now!

The logos should be in the NCPDocs project typically, not sure what happened there - will have a look a little later, just poke me again some time.

Closing this ticket in favor of: https://github.com/NoCheatPlus/Issues/issues/556
