### ISSUE TITLE
Can't disable nocheatplus log

### ISSUE THREAD

**Issue by luis-guideti** [NoCheatPlus/Issues#564]
#### Short description of the issue.
The nocheatplus.log file is always in use, even if every option in the logging category of the settings file is set to false

#### Complete output of the _ncp version_ command (please prefer text here).
---- Version information ----
#### Server ####
${spigot.desc}null ~MC: 1.11.2~
detected: 1.11.2
#### NoCheatPlus ####
Plugin: 3.16.1-SNAPSHOT-sMD5NET-b1149
MCAccess: 1.11-1.11.2 / Spigot-CB-1.11_R1
Features:
blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11
checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter
defaults: pvpKnockBackVelocity

**Comment by asofold** [comment]
Currently, the categories don't fully match "log file" in general, considering registry and setup logging.

Try setting the log file name to an empty string: **""**

This might fully deactivate the log file (invalid names for files and folders also might work, but could be os-specific).

I should add a note to the wiki...

**Comment by luis-guideti** [comment]
Alright, the empty file name works
