### ISSUE TITLE
SurvivalFly false positive when applying velocity to players

### ISSUE THREAD

**Issue by Lysandr0** [NoCheatPlus/Issues#571]
#### Short description of the issue.
(Posting on behalf of @Kakalavala)
We apply vector velocities to players for a mini game, in order to simulate higher knock back effects since the vanilla knockback enchant stops at level 10, however, SurvivalFly seems to trigger in most scenarios whenever you get hit.

#### Complete output of the _ncp version_ command (please prefer text here).
![ncpversion](https://user-images.githubusercontent.com/20213873/46509332-61435700-c842-11e8-9b68-f794a988dfce.PNG)

#### How to reproduce the issue (is it random / always happens / side conditions)?
Always happens

#### Have you made any (noteworthy) changes to the default configuration of NCP?
Default config

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
Relevant lines of code:
```
public Vector getKnockbackVector(final Player ply) {
    final double xDir = Math.round(ply.getLocation().getDirection().normalize().getX());
    final double zDir = Math.round(ply.getLocation().getDirection().normalize().getZ());
    final double k = this.getKnockbackLevel(ply);
        
    return new Vector(-(k * xDir), 0.2, -(k * zDir));
}
```

```
public double getKnockbackLevel(final Player ply) {
    return Math.floor(1 + (20 - ply.getHealth()) / 2);
}
```
#### Provide additional information, such as error/debug/violation logs. (For reproducible issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) Use GitHub gists or http://pastebin.com/ or similar for huge logs, or attach a (zip-) file here. For image uploads, please prefer a site that allows viewing without JavaScript, you can upload file attachments for issues right here.
Debug log:
[nocheatplus.log](https://github.com/NoCheatPlus/Issues/files/2448489/nocheatplus.log)

**Comment by RoboMWM** [comment]
I've never had issues with plugin-applied velocities, but you should note that any applied velocity is actually capped at 4, and setting it higher can actually cause other issues on the server. Would suggest capping your returned vector.
