### ISSUE TITLE
1.13 FARMLAND false positives

### ISSUE THREAD

**Issue by hurrgurl** [NoCheatPlus/Issues#580]
```
overrideflags:
farmland: default+ign_passable+ground_height+ALLOW_LOWJUMP
```

does not work in 1.13 and produces survival fly false positives.

Anyone managed to find a solution besides disabling survivalfly?

**Comment by ghost** [comment]
`farmland: default+ign_passable+ground+ALLOW_LOWJUMP+XZ100+MIN_HEIGHT16_15`

**Comment by hurrgurl** [comment]
Thank you!
