### ISSUE TITLE
Enhance chat checks [DBO 376]

### ISSUE THREAD

**Issue by MyPictures** [NoCheatPlus/Issues#6]
What is the problem, What do you expect to see instead?<<<
If a player spam a twice. Example:

[Player](hi): hi <----- Disabled

Can it be reproduced systematically and if so: how?
I don' t no

Which version of NC+ are you using? (Check with /version NoCheatPlus on your server)
The Dev for 1.4.6

On which Craftbukkit/Craftbukkit++/Spigot build do you run your server on?
The Cracftbukkt Beta 1.4.6

How easy is it to reproduce? Does it always happen? Does it happen to all players? Does it happen with vanilla clients?
I think this is not needing?

**Comment by MyPictures** [comment]
**MyPictures:** "Thanks for making this ticket. I would also love to see a "ignoreuppercase" option so this get blocked also: 
[Player]: I love music 
[Player]: I LoVe MuSiC 
[Player]: I LOVE music "

**Comment by MyPictures** [comment]
**asofold:** "MyPictures:

It is ignored for the similarity checks.

Repeating messages does "cost more", you will get much faster to the point of cancelled messages with repetition. There should be a weight for message repetition/similarity in the normal words weights section, if you want to let it cost even more. One problem is situations like answering "yes" to several€ different questions, it would be very annoying to get those cancelled a couple of times.

Of course i can imagine features such as preventing/replacing messages completely (without using the scoring system) for...

- Exact message repetition.
- Almost exact message repetition.
- IPs
- Upper case
- Word blacklists

Those could be more simple to add. More complicated would be to try to prevent false positives in terms of context dependent judgement. One could for instance judge if a player repeats stuff and has not received any messages since writing the last one himself. That could help, one could also enforce more use of @mention by giving "answers" to people that mentioned your name a higher chance to pass filters, but that is likely to be annoying for most servers, and more complex ways to determine if a message fits a context are... complex to implement and likely to be pretty faulty :p

One more go at repetition: Currently all weights are to be understood as decreasing with the time difference to the last message, so if you repeat something after 5 seconds it will count much less heavy than repeating it after 1 second.*

**Comment by MyPictures** [comment]
**asofold:** "In fact, if you have enough ram (not that much needed), you could activate the words engine for players (or one of the others). This will penalize word repetitions for each player individually. It might make some typical messages slightly more expensive, but would prevent sequences like "HI...there...hi...there" better."

**Comment by MyPictures** [comment]
**asofold:** "Fighter88:

War das eine automatische Übersetzung? :p

Filtering CAPS would be nice to have. Currently i am not sure if and how (technically) we should extend the chat infrastructure, because that's worth a standalone plugin - is there no standalone chat plugin doing the task?

We will at some point add at least simple direct transformation and filtering support, at least regex-based, but that is clearly not the highest priority right now.*

**Comment by MyPictures** [comment]
**zSwayz:** "Like said in IRC; It would be nice to have a RexEx filter we can use to filter out some spam/advertising and possibly modify to suit our needs.. Custom RegExes would be useful."

**Comment by asofold** [comment]
https://github.com/NoCheatPlus/Issues/projects/6
