### ISSUE TITLE
NoCheatPlus - Fly Damage

### ISSUE THREAD

**Issue by dimtsolakoudis** [NoCheatPlus/Issues#644]
I can't figure out how to make it so when a player is placing invisible blocks and NOT get lag backed, my cheat detection detects it as fly and to fix it is only by making nocheatplus make the player take a one heart damage everytime they place invisible blocks on themselves. Pretty much what I need and can't find is, how to make the player take damage repeatedly while they are placing invisible blocks and floating, this will make my cheat detection not false ban, similar way of doing it on hypixel.

**Comment by Janmm14** [comment]
api of nocheatplus allows you to add fake blocks per player as far as i know. however i never used it. and nocheatplus is not maintained anymore.
