### ISSUE TITLE
How to make the End crystals break with other items than a sword ? 

### ISSUE THREAD

**Issue by akalpr** [NoCheatPlus/Issues#654]
#### Short description of the issue.
A vid is better than everything else so here it is : https://www.youtube.com/watch?v=std_AkGR-p8
PLaying on a 1.12.2 serv.
Basically, i'm using NCP default config on an anarchy server where cheat client are allowed in order to do what we callin "crystal PvP". 
The problem i got is i cant use my mainhand to break crystals after they got placed, i can only break them if i got a sword in my hand. I want to know how can i change that in order to be able to break them while holding any items. 
This is the only prob.
Im using NCP to stop the "creative fly hacks" and timer shit and some other utilities abuse.

#### How to reproduce the issue (is it random / always happens / side conditions)?
Always happen.I'm using default NCP config.

#### Have you made any (noteworthy) changes to the default configuration of NCP?
Nope.

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
Nope.

**Comment by Janmm14** [comment]
Unfortunaly for you, NoCheatPlus is EOL (end of life).

Please go to the folks over at https://github.com/Updated-NoCheatPlus
