### ISSUE TITLE
Bug Report - Harming Potion

### ISSUE THREAD

**Issue by AlonHor** [NoCheatPlus/Issues#659]
Hello. I run a server with NoCheatPlus and when a member drinks a potion of harming (Instant Damage II) it kicks him for "SelfHit".

---- Version information ----
#### Server ####
git-Paper-"b89788a" ~MC: 1.16.5~
detected: 1.16.5
#### NoCheatPlus ####
Plugin: 3.17-SNAPSHOT-Updated-b90
MCAccess: 1.13-1.16|? / Bukkit-API
Features:
blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12 | BlocksMC1_13 | BlocksMC1_14 | BlocksMC1_15 | BlocksMC1_16 | MCAccessBukkitModern
checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
defaults: pvpKnockBackVelocity
packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | WrongTurnAdapter | NoSlow | Fight
Hooks: AllViolations~NCP~ 1.0 | ViolationFrequency~NCP~ 1.0
#### Related Plugins ####
ProtocolLib v4.6.1-SNAPSHOT | ViaVersion v3.2.1

#### How to reproduce: ####
Drink an Instant Damage II potion (potion of harming)
Make sure you don't have bypass permission ;)

#### Changes I've made to the config: ####
Only changed the prefix.

#### Other anti-cheats: ####
Yes. I do use Matrix but the alert of the SelfHit is from NoCheatPlus

#### Additional Information: ####
I tried to investigate that bug and it happens to any member (Doesn't matter which player, happened to all of them)

Thanks :)

**Comment by Janmm14** [comment]
Please head over to https://github.com/Updated-NoCheatPlus

This original NoCheatPlus is no longer maintained.
