### ISSUE TITLE
Instant break blocks with SlimeFun (blockbreak)

### ISSUE THREAD

**Issue by asofold** [NoCheatPlus/Issues#69]
Origin at cncp:

 RoboMWM commented 2 days ago

Currently having an issue with the "gold pan" triggering blockbreak alerts when used on gravel, as Slimefun instantly destroys it. Although ideally CNCP support for SF would be great, I'm more than fine with just an option in CNCP to allow certain blocks to be instantly broken (partly because I would like you guys to focus on vanilla issues anyways :P )

**Comment by asofold** [comment]
General compatibility usually can't really be done, unless we trick the author of the plugin to hook into NCP or use exemption by metadata where appropriate. 

Exemption (by whatever) might not be useful here, if they just use BlockDamageEvent.setInstaBreak. In this case i would prefer to make it compatible in NCP directly.

Now we still don't know what SlimeFun is doing with that feature (add enchantments / potion effects, setInstaBreak, 'manually' break the block firing their own BlockBreakEvent... remains to be checked.

If it is about a certain type of block, you could allow instant breaking by all tools by configuration, but i am not sure if that's what you would want to do.

**Comment by RoboMWM** [comment]
Also triggers noswing and wrongblock.

**Comment by asofold** [comment]
Does it remove blocks one by one or is it an area effect?

**Comment by RoboMWM** [comment]
one by one, the one in front of a player. The player can hold down right click and continue to destroy blocks with this (only the ones they're pointing at).

**Comment by asofold** [comment]
Right click blocks... that'll need another method likely, because that would be a custom event.

Couldn't find the piece of code removing the blocks (at medium quick glance) - might have to contact the author to discuss how to do it.

**Comment by asofold** [comment]
Closing as superseded (possibly fixed in build 1093) - if issues persist, i might need to see a code snippet, or you to contact the author - block breaking/placing can't be so difficult to mend, one knowing what one is dealing with.
