### ISSUE TITLE
Speeding (horizontal speed, sprint, dolphin, Jesus) [DBO 378]

### ISSUE THREAD

**Issue by MyPictures** [NoCheatPlus/Issues#7]
This ticket is meant to aggregate reports about horizontal speeding. Plans are to use the same checking method for all those types of speeding.
- Speeding on ground.
- Bunny hopping.
- Speeding inside of other media (water, lava).
- Dolphin and Jesus (rather a mixture of water + air).

This touches areas like:
- Accounting for the medium / context (mixture with jumping into air, lift off constraints).
- Horizontal velocity modeling.
- Modeling horizontal moving with friction.
- Mid-term accounting for context vs. speed.

With latency-dependent modifiers there could be all sorts of edge cases, especially when modifiers change somehow., which then will need a lot of testing.

_For reports on specific speeding implementations, please measure the time on 100 blocks, using the **'ncp stopwatch distance 100'** command, which measures the time until you reached 100 blocks distance from then+there on._

(Description redone.)

**Comment by MyPictures** [comment]
**asofold:** "Many client features "work", essential is what they actually do... in this case i assume they can gain quite a bit of percentage with sprinting, which is a known problem."

**Comment by MyPictures** [comment]
**asofold:** "Exact speed is tricky, since players can theoretically have lots of factors that change the maximally allowed speed a lot within short time, such as sprinting, sneaking, potions, ice, bunny-hopping, pistons, altered frequency of packet sending, CraftBukkit, Minecraft. Velocity (knockbacks) might be one of the smaller problems, since for those one can exempt the players from the more strict checking.

I would like to make it more precise, but introducing more false positives would also not help. Might try something with keeping track of medium/short range distance covered along with sort of medium the player went through. For horizontal speed it might be easier, since we don't have the possibility of such high entry speeds as with players falling into water or onto ladders.

Actually i will copy and paste this into the ticket. :p"

**Comment by MyPictures** [comment]
**asofold:** "Will be interesting with the new beta.

It might make some sprint hacks slightly outdated. But it might also allow some new tweaks, though those might be slightly harder to implement."

**Comment by asofold** [comment]
Much confined by now, more following. Closing as too broad+old - superseded.
