### ISSUE TITLE
Citizen's 2 Sentrys count in NCP messages

### ISSUE THREAD

**Issue by DeJay6424** [NoCheatPlus/Issues#70]
1. While player's are fighing boss NPC (Sentry) 
2. Steps to reproduce:
Install Citizens 2 (latest build as of 1/11/16)
Install Sentry (latest build as of 1/11/16)
Set up a sentry NPC
Punch said sentry occasionally get message for things like noswing
3. No changes to NCP Config
4. RPGMe
5. Server: git-Spigot-5f38d38-12698ea (MC: 1.8.8)
5. Plugin: 3.11.1-RC-sMD5NET-b743

**Comment by asofold** [comment]
* Those are player-npcs?
* The npcs are added by configuration/manually or by another plugin?

If added manually or by configuration (random guess here):
* Can custom metadata be added to npcs by configuration? Just if there is such an option in their configuration.

Might add another compatibility twist to NCP, could help here. Still need to ask, are you having CompatNoCheatPlus as well? It does have a hook for citizens2, which might work.
