### ISSUE TITLE
Sprint + Fly, then stop flying

### ISSUE THREAD

**Issue by Platinteufel** [NoCheatPlus/Issues#73]
Hey,

I've reported this bug a few month ago, but unfortunately it isn't fixed yet. 
Flying + sprint is no problem with NCP and works very fine. But if you press 2 times space while you are flying + sprinting, you will end up in a violation and get a knockback. It would be nice if you could make it a little bit smoother.
This video is a few month old, but it's still the same in the latest devbuild.
https://www.youtube.com/watch?v=bip6w8LRoT4

/Edit: Hunger has no effect in this case.

**Comment by asofold** [comment]
Need re-test.

**Comment by Platinteufel** [comment]
I didn't chance anything, just put the NCP.jar on my server and started.

[01:30:23 INFO]: NCP: Displaying [...] violations...
[01:30:23 INFO]: NCP: [01:30:10] moving.creativefly VL 144  (n8a18m27)

**Comment by asofold** [comment]
Thanks a lot, that should be enough for fixing it in the next session.

**Comment by asofold** [comment]
Does this improve with build 920?

**Comment by Platinteufel** [comment]
It's working fine now, thank you!

**Comment by asofold** [comment]
Thank you very much for the feedback!
