### ISSUE TITLE
Add check for "headroll" ("derp", impossible pitch).

### ISSUE THREAD

**Issue by RoboMWM** [NoCheatPlus/Issues#77]
When a player moves their head (their pitch?) all the way back beyond a 90 degree angle to the sky to look behind themselves, they're basically telling me "I'm using a hacked client."

**Comment by MyPictures** [comment]
Yeah a check would for sure be possible to make here. It would kinda be in the importance level of noswing ;P

**Comment by asofold** [comment]
It would catch the noobs who would be caught by video or mods, on the other hand it is very simple to do.

**Comment by MyPictures** [comment]
@asofold It is kinda a memory of the old times when NeatMonster used to test hack clients and he always forgot the derp hack on which messed with the freecam checks!

**Comment by Eyremba** [comment]
@asofold hello? This is very simple to implement like you mentioned on 24 Jan. 2016, however, this was 2 years ago.
You should really start to implement a check for this, or close the issue if there is already a check for it.

**Comment by RoboMWM** [comment]
@Eyremba you can get other authors to PR such a "simple" thing as well. This is an OSS project after all. asofold is busy with real-life stuff and hasn't been able to work on NCP for quite some time. Either way, this is a really minor request and something that might not even fit within NCP since it's really more of an indication of hacking and not necessarily something that is used to "cheat." (However, as per the referenced issue, this could cause players to apply knockback in whichever direction they want - in that case, then it is something that should be checked in NCP.)

**Comment by asofold** [comment]
@Eyremba I don't close tickets that might still get implemented. I'd prefer to close more tickets, but to put them in a more or less internal knowledge base. I haven't come to set up such, perhaps JIRA would be another option for better relating/sorting ~ other topic.

@RoboMWM Thank you for noting.

Closing this ticket in favor of the actually relevant one: https://github.com/NoCheatPlus/Issues/issues/473
