### ISSUE TITLE
SUGGESTION concerning notification the OP players about VL.

### ISSUE THREAD

**Issue by Kixot14** [NoCheatPlus/Issues#81]
Can you add option to enable only that VL-notifications, which higher than 20-30...
Because VL 20-30 it's usual just a server lag or something small. But spam from it very much!

**Comment by MyPictures** [comment]
Hi @Kixot14 you can already do this by altering the actions: https://github.com/NoCheatPlus/Docs/wiki/General#actions

It will take some time but you can construct any setup you like.
Be aware that while checks like bedfly have nearly 0 false positives and create low violation levels, others like survivalfly are the complete opposit.

**Comment by asofold** [comment]
Actions allow modifying what/where/when to log. The violation levels wildly vary amongst different checks, and the mechanics of escalation also vary (add one each, increase with non-linear slope). So unfortunately there is no simple sensitivity switch (yet).
