### ISSUE TITLE
Hacks,Cheats WURST

### ISSUE THREAD

**Issue by Someone-NEW** [NoCheatPlus/Issues#83]
I have a lot of trouble with hacked client WURST that alot of things work try better yourself and you will se fly potions like a Creative killer potions OMG can you solve something there?
https://www.wurst-client.tk/news/2015-07-16-Wurst-2.1-released/

**Comment by asofold** [comment]
We can't really keep issues with 'client x can do a lot of things' :), so i suggest giving more details for what you are concerned about.

That there is a switch to activate/adapt cheats is nothing special, also that cheats activate is nothing new. The question is what they can do more than a vanilla player, and if there already is a ticket for that case or if we need to open a new one for that specific issue.

**Comment by Someone-NEW** [comment]
this hacked client use commands like .help and so one /=.  "Dot" but they can use Left Ctrl for menu ok but rely problem are when is on creative they can create killer potions and players can kill players when come to spawn while thats easy to waith and kill him i dont know how is this possible but i am not even try this to make and how to block create potions and using it.

**Comment by asofold** [comment]
The potions thing might be possible to contain by limiting the enchantment levels (low and high limits).

Roughly it would fit in here: https://github.com/NoCheatPlus/Issues/issues/12

That issue is quite old, though.

**Comment by Someone-NEW** [comment]
I dont know im not tested i muss learn how this work but its still possible to use that, better you test this and maybe you can fix something?

**Comment by asofold** [comment]
If we add limiting enchantment levels, we would make it configurable (global + per item). So custom plugins needn't be a problem.

**Comment by Someone-NEW** [comment]
i use Token Enchant plugin with TokenEnchantAPI and Essentials plugins ... nothing else, thanks

**Comment by asofold** [comment]
Have you considered CreativeItemControl (spigotmc) yet?

**Comment by Someone-NEW** [comment]
Umm not fully understand im ban in English but what you mean? i have Spigot 1.8.8 CreativeItemControl? idk. i have umm one world with Creative plots and here is doing this problems.

**Comment by MyPictures** [comment]
He means this plugin: https://www.spigotmc.org/resources/creativeitemcontrol.9471/

If you tried to run it along side NoCheatPlus.

**Comment by asofold** [comment]
Don't know the possibilities of configuration, but as a specialized plugin that might be a candidate for controlling such enchantments too.

**Comment by Someone-NEW** [comment]
I have no Creative control i not need it. And i foun that problem on other servers to with that hack but server not have the same plugins like or example me.

**Comment by asofold** [comment]
Perhaps we should just add something configurable. 

A bit peculiar where/when to check and how to reflect that in the configuration.
* Game mode dependent.
* On clicking an item (Bukkit event).
* On using an item.
* On potion splash or item consumption.

Which defaults to set (likely completely deactivated, but there should be some default levels set).

**Comment by Someone-NEW** [comment]
Hmm nice i hope you can solve this. But leave when happen like using that a message all admins  owners some special msg they can know how enable this they will know its possible prevent this on config to change itd but you will know the best to do rigtht?
Thanks.

**Comment by asofold** [comment]
Closing as 'duplicate' as i can't currently add the item stuff - there exist other plugins for that.
