### ISSUE TITLE
I can't kill anyone in PvP

### ISSUE THREAD

**Issue by HuskyGamingYT** [NoCheatPlus/Issues#92]
I get them down to the last heart and I can't do anything to them, and I end up getting killed. Please tell me how to fix this.

**Comment by HuskyGamingYT** [comment]
Btw im using Wurst :)

**Comment by asofold** [comment]
Which of the Wurst features are you having activated?

**Comment by HuskyGamingYT** [comment]
Sorry wrong client, I'm using Wolfram not sure if you can help me with this
one but I have one kill aura, velocity, reach, aimbot, and aim assist.

**Comment by asofold** [comment]
Is it a server known to have NCP on?

**Comment by HuskyGamingYT** [comment]
Umm uberminecraft I'm not sure

**Comment by MyPictures** [comment]
What happens if you use the vanilla MC client and kill someone that way? Can you do it?

**Comment by asofold** [comment]
@MyPictures Good point.

@HuskyGamingYT 
* Do you certainly know they're using NCP at all? 
* Can you adjust settings to reduce hittinh frequency?

**Comment by asofold** [comment]
Closing as can't fix.
