### ISSUE TITLE
Falling into a 1 layer water block triggers SurvivalFly

### ISSUE THREAD

**Issue by Maxetto** [NoCheatPlus/Issues#94]
Hi, just found out that if you fall into the water and if the water has only 1 layer (and void under), you get moved back for SurvivalFly.

Steps to reproduce:
1) Do a x-1-z water pool and a "trampoline" with some height (I tried with 6 blocks).
2) Walk into water and, when falling, hold space.
3) If reproduced correctly you should get moved back.

EDIT:
`[TestNCP] Maxetto MOVING_SURVIVALFLY vl 0.43 (+0.43) Details: distance=0.81 health=20.0/20.0 locationfrom=-997.36, 28.16, -979.50 locationto=-997.31, 27.35, -979.50 displayname=Maxetto tags=swimdown uuid=bc8e1b4e-9ac5-3558-aadc-362e691dc650 world=Cargo cancel=true Ticks[Lag]: 1200@1.016`

**Comment by Maxetto** [comment]
Works also with longer fall distances:

[TestNCP] Maxetto MOVING_SURVIVALFLY vl 15.638 (+15.638) Details: distance=1.03 health=20.0/20.0 locationfrom=-974.90, 18.69, -929.13 locationto=-974.90, 17.66, -929.12 displayname=Maxetto tags=vdistrel uuid=bc8e1b4e-9ac5-3558-aadc-362e691dc650 world=Carrier cancel=true

Using NoCheatPlus b390

**Comment by asofold** [comment]
Need reproduce with debug log, to see how it relates to expected/possible friction envelopes.

I'll try this weekind (~fr-sun).

**Comment by Maxetto** [comment]
I thought TestNCP was the ultimate Debug log :stuck_out_tongue_closed_eyes: 
Here it is the Debug from NCP:
Low Falling:
[nocheatplus (Low Fall).txt](https://github.com/NoCheatPlus/Issues/files/138334/nocheatplus.Low.Fall.txt)

High Falling:
[nocheatplus (High Fall).txt](https://github.com/NoCheatPlus/Issues/files/138335/nocheatplus.High.Fall.txt)

**Comment by asofold** [comment]
Thanks a lot. With past-move tracking we should be able to add a simple workaround for that case, checking 2 past moves.

**Comment by Maxetto** [comment]
Updating the Debug Paste with newest [version](https://github.com/NoCheatPlus/NoCheatPlus/commit/8b6d1324a3d4e9928cde082d53e71e3b2210ad0f) (As I thought that would have solved the issue :stuck_out_tongue_closed_eyes: )

[new_low_fall.txt](https://github.com/NoCheatPlus/Issues/files/169720/new_low_fall.txt)

**Comment by asofold** [comment]
Are you compiling NCP yourself? Unfortunately it's not building at present.

**Comment by Maxetto** [comment]
No, I used b942 from the Jenkins.

**Comment by asofold** [comment]
I hope we can build again soon, otherwise i'll have to make an NCP build server/thing.

Possibly might upload dev builds to github.

**Comment by asofold** [comment]
I think the slow falling isn't covered yet, couldn't reproduce either. Is that still an issue?

If yes, i'll just add a case based on the debug log from above.

**Comment by Maxetto** [comment]
No, it's completely fixed. Thank you really much! :smile:

**Comment by asofold** [comment]
Alright, thank you for the feedback :).
