### ISSUE TITLE
Levitation (new effect) causes survival-fly false positives

### ISSUE THREAD

**Issue by Platinteufel** [NoCheatPlus/Issues#98]
00:23:27 INFO: ---- Version information ----
00:23:27 INFO: #### Server ####
00:23:27 INFO: git-Spigot-dd155ed-3e3516e ~MC: 1.9~
00:23:27 INFO: detected: 1.9
00:23:27 INFO: #### NoCheatPlus ####
00:23:27 INFO: Plugin: 3.14.0-SNAPSHOT-sMD5NET-b933
00:23:27 INFO: MCAccess: 1.9 / Spigot-CB-1.9_R1

00:23:27 INFO: blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
00:23:27 INFO: checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
00:23:27 INFO: defaults: pvpKnockBackVelocity
00:23:27 INFO: packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter
00:23:27 INFO: Hooks: AllViolations~NCP~ 1.0
00:23:27 INFO: #### Related Plugins ####
00:23:27 INFO: ProtocolLib v3.7-SNAPSHOT-b239

![2016-03-04_01 01 02](https://cloud.githubusercontent.com/assets/13700636/13513934/ba46e61e-e1a4-11e5-910a-2f39fc156d71.png)

**Comment by asofold** [comment]
Also duplicates: https://github.com/NoCheatPlus/Issues/issues/56

Please open once the thing has been implemented at all :). Usually we prefer individual tickets, though. It's just not yet implemented.

**Comment by asofold** [comment]
Assume fixed for the moment, there'll be updates altering things, so we'll prefer tickets for specific issues then.
